import type { ArticleTemplateSet } from "./types";

export const THREE_O_TEMPLATES: Record<string, ArticleTemplateSet> = {
  "3o-bundle-fares-3o-domestic-international": [
    {
      chatEn: "Good news — refund is available on the international Value bundle within 24 hours of booking, though a fee applies. The credit voucher alternative usually works out cheaper if you're open to it.",
      chatAr: "خبر سار - يتوفر الاسترداد على باقة Value الدولية خلال 24 ساعة من الحجز، مع تطبيق رسوم. عادةً ما يكون خيار قسيمة الرصيد أقل تكلفة إذا كنتم منفتحين على ذلك.",
      emailSubjectEn: "Refund option on your 3O Value bundle",
      emailIssueEn: "Thank you for asking about a refund on your international Value bundle cancellation.",
      emailResolutionEn: "Refund is available on the international Value bundle within 24 hours of booking, subject to a fee — please check the current fare chart for the exact amount. The credit voucher alternative is usually the lower-cost option.",
      emailSubjectAr: "خيار الاسترداد على باقة Value الخاصة بكم",
      emailIssueAr: "شكراً لاستفساركم عن استرداد المبلغ عند إلغاء باقة Value الدولية.",
      emailResolutionAr: "يتوفر الاسترداد على باقة Value الدولية خلال 24 ساعة من الحجز، مع تطبيق رسوم - يرجى مراجعة جدول الأسعار الحالي لمعرفة المبلغ الدقيق. عادةً ما يكون خيار قسيمة الرصيد الأقل تكلفة.",
    },
    {
      chatEn: "That's fine — modification on the domestic Basic fare is allowed up to 72 hours prior to departure, and at 80 hours out you're comfortably within that window.",
      chatAr: "لا مشكلة - يُسمح بتعديل باقة Basic الداخلية حتى 72 ساعة قبل المغادرة، وبما أنكم على بعد 80 ساعة، فأنتم ضمن هذه المهلة بشكل مريح.",
      emailSubjectEn: "Modification window for your domestic Basic fare",
      emailIssueEn: "Thank you for your modification request on your 3O domestic Basic fare booking.",
      emailResolutionEn: "Modification on the domestic Basic fare is allowed up to 72 hours prior to departure. As your flight is 80 hours away, you're within this window — please see the current fare chart for the exact fee.",
      emailSubjectAr: "مهلة تعديل باقة Basic الداخلية",
      emailIssueAr: "شكراً لطلبكم تعديل حجزكم على باقة Basic الداخلية.",
      emailResolutionAr: "يُسمح بتعديل باقة Basic الداخلية حتى 72 ساعة قبل موعد المغادرة. وبما أن رحلتكم على بعد 80 ساعة، فأنتم ضمن هذه المهلة - يرجى مراجعة جدول الأسعار الحالي لمعرفة الرسوم الدقيقة.",
    },
    {
      chatEn: "Yes, the same Basic/Value/Ultimate names apply to both domestic and international flights, though the included baggage weights and fees differ — happy to walk you through the specifics for your sector.",
      chatAr: "نعم، تنطبق أسماء الباقات نفسها Basic وValue وUltimate على الرحلات الداخلية والدولية، لكن تختلف أوزان الأمتعة المشمولة والرسوم - يسعدني توضيح التفاصيل الخاصة بمسار رحلتكم.",
      emailSubjectEn: "Bundle names across domestic and international",
      emailIssueEn: "Thank you for asking whether the same bundle names apply to both domestic and international 3O flights.",
      emailResolutionEn: "Yes, the same three bundle names (Basic, Value, Ultimate) apply to both, but the included baggage weights and fees differ between domestic and international. Let us know your sector and we'll confirm the exact figures.",
      emailSubjectAr: "أسماء الباقات على الرحلات الداخلية والدولية",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كانت أسماء الباقات نفسها تنطبق على رحلات 3O الداخلية والدولية.",
      emailResolutionAr: "نعم، تنطبق أسماء الباقات الثلاث نفسها (Basic وValue وUltimate) على النوعين، لكن تختلف أوزان الأمتعة المشمولة والرسوم بين الرحلات الداخلية والدولية. يرجى إخبارنا بمسار رحلتكم وسنؤكد الأرقام الدقيقة.",
    },
  ],

  "3o-excess-baggage-rates-3o": [
    {
      chatEn: "For a no-baggage-fare booking from Casablanca to Turkey, the first 20kg would be MAD 800 — and there's no restriction on the number of pieces within that weight.",
      chatAr: "بالنسبة لحجز بدون باقة أمتعة من الدار البيضاء إلى تركيا، ستكون رسوم أول 20 كجم 800 درهم مغربي - ولا يوجد قيد على عدد القطع ضمن هذا الوزن.",
      emailSubjectEn: "No-baggage-fare excess rate to Turkey",
      emailIssueEn: "Thank you for asking about the first-20kg rate for your no-baggage-fare booking from Casablanca to Turkey.",
      emailResolutionEn: "For a no-baggage-fare customer travelling from Morocco to Turkey, the first 20kg is priced at MAD 800, with no restriction on the number of pieces within that weight.",
      emailSubjectAr: "رسوم الوزن الزائد لحجز بدون باقة أمتعة إلى تركيا",
      emailIssueAr: "شكراً لاستفساركم عن رسوم أول 20 كجم لحجزكم بدون باقة أمتعة من الدار البيضاء إلى تركيا.",
      emailResolutionAr: "بالنسبة للعميل بدون باقة أمتعة المسافر من المغرب إلى تركيا، تبلغ رسوم أول 20 كجم 800 درهم مغربي، دون قيد على عدد القطع ضمن هذا الوزن.",
    },
    {
      chatEn: "From Morocco to the UAE, the excess baggage rate is MAD 250 per kg — that's the highest of our 'from Morocco' rates, so let me know if you'd like to pre-purchase weight to save on it.",
      chatAr: "من المغرب إلى الإمارات، تبلغ رسوم الوزن الزائد 250 درهمًا مغربيًا لكل كيلوغرام - وهي أعلى رسوم ضمن مسارات 'من المغرب'، فأخبروني إذا رغبتم بشراء وزن مسبق للتوفير.",
      emailSubjectEn: "Excess baggage rate to the UAE",
      emailIssueEn: "Thank you for asking about the excess baggage rate from Casablanca to the UAE.",
      emailResolutionEn: "From Morocco to the UAE, the excess baggage rate is MAD 250 per kg — the highest of our 'from Morocco' rates. Pre-purchasing extra weight in advance can often be more economical; let us know if you'd like to add it now.",
      emailSubjectAr: "رسوم الوزن الزائد إلى الإمارات",
      emailIssueAr: "شكراً لاستفساركم عن رسوم الوزن الزائد من الدار البيضاء إلى الإمارات.",
      emailResolutionAr: "من المغرب إلى الإمارات، تبلغ رسوم الوزن الزائد 250 درهمًا مغربيًا لكل كيلوغرام - وهي الأعلى ضمن مسارات 'من المغرب'. قد يكون شراء الوزن الإضافي مسبقًا أكثر اقتصادًا؛ يرجى إخبارنا إذا رغبتم بإضافته الآن.",
    },
    {
      chatEn: "For domestic travel within Morocco, excess baggage is MAD 50 per kg, and if you're on a no-baggage fare, the first 20kg domestic is a flat MAD 300 in either direction.",
      chatAr: "بالنسبة للسفر الداخلي ضمن المغرب، تبلغ رسوم الوزن الزائد 50 درهمًا مغربيًا لكل كيلوغرام، وإذا كان حجزكم بدون باقة أمتعة، فإن رسوم أول 20 كجم داخليًا ثابتة عند 300 درهم مغربي في كلا الاتجاهين.",
      emailSubjectEn: "Domestic excess baggage rates",
      emailIssueEn: "Thank you for asking about excess baggage on your domestic Morocco flight.",
      emailResolutionEn: "Domestic excess baggage is MAD 50 per kg. For a no-baggage-fare customer, the first 20kg domestic is a flat MAD 300 in either direction.",
      emailSubjectAr: "رسوم الوزن الزائد على الرحلات الداخلية",
      emailIssueAr: "شكراً لاستفساركم عن الوزن الزائد على رحلتكم الداخلية ضمن المغرب.",
      emailResolutionAr: "رسوم الوزن الزائد الداخلي هي 50 درهمًا مغربيًا لكل كيلوغرام. بالنسبة للعميل بدون باقة أمتعة، تبلغ رسوم أول 20 كجم داخليًا 300 درهم مغربي ثابتة في كلا الاتجاهين.",
    },
  ],

  "3o-tv-handling-3o": [
    {
      chatEn: "For a 50-inch TV, the charge is MAD 500 and you'll need to sign an indemnity form at the airport — happy to note that on your booking now.",
      chatAr: "بالنسبة لتلفاز بحجم 50 بوصة، تبلغ الرسوم 500 درهم مغربي، وستحتاجون لتوقيع نموذج إخلاء مسؤولية في المطار - يسعدني تسجيل ذلك على حجزكم الآن.",
      emailSubjectEn: "50-inch TV charge and paperwork",
      emailIssueEn: "Thank you for checking in about bringing your 50-inch TV and the paperwork required.",
      emailResolutionEn: "A 50-inch TV falls within the 40–60 inch band: the charge is MAD 500, and you'll need to sign an indemnity form at the airport before check-in.",
      emailSubjectAr: "رسوم ومستندات تلفاز 50 بوصة",
      emailIssueAr: "شكراً لتواصلكم بخصوص إحضار تلفازكم بحجم 50 بوصة والمستندات المطلوبة.",
      emailResolutionAr: "يقع تلفاز 50 بوصة ضمن فئة 40-60 بوصة: تبلغ الرسوم 500 درهم مغربي، وستحتاجون لتوقيع نموذج إخلاء مسؤولية في المطار قبل تسجيل الوصول.",
    },
    {
      chatEn: "I'm sorry, but a 70-inch TV can't be accepted — our maximum size is 60 inches. Could you arrange alternative shipping for it?",
      chatAr: "نأسف، لا يمكن قبول تلفاز بحجم 70 بوصة - الحد الأقصى لدينا هو 60 بوصة. هل يمكنكم ترتيب شحن بديل له؟",
      emailSubjectEn: "TV size exceeds accepted limit",
      emailIssueEn: "Thank you for checking whether your 70-inch TV can be checked in.",
      emailResolutionEn: "Unfortunately TVs over 60 inches cannot be accepted on 3O flights. We'd recommend arranging alternative shipping for this item.",
      emailSubjectAr: "حجم التلفاز يتجاوز الحد المسموح",
      emailIssueAr: "شكراً لاستفساركم عن إمكانية تسجيل تلفازكم بحجم 70 بوصة.",
      emailResolutionAr: "للأسف، لا يمكن قبول أجهزة التلفاز التي يتجاوز حجمها 60 بوصة على رحلات 3O. نوصي بترتيب شحن بديل لهذا الجهاز.",
    },
    {
      chatEn: "No paperwork needed for that size — TVs under 40 inches travel free of charge with no additional forms. The indemnity form only applies to the 40–60 inch band.",
      chatAr: "لا حاجة لأي أوراق بهذا الحجم - تُنقل أجهزة التلفاز الأقل من 40 بوصة مجانًا دون أي نماذج إضافية. يُطلب نموذج إخلاء المسؤولية فقط لفئة 40-60 بوصة.",
      emailSubjectEn: "35-inch TV — no paperwork required",
      emailIssueEn: "Thank you for asking whether you need to sign anything for your 35-inch TV.",
      emailResolutionEn: "TVs under 40 inches travel free of charge with no additional paperwork required. The signed indemnity form only applies to TVs in the 40–60 inch band.",
      emailSubjectAr: "تلفاز 35 بوصة - لا حاجة لمستندات",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كنتم بحاجة لتوقيع أي مستندات لتلفازكم بحجم 35 بوصة.",
      emailResolutionAr: "تُنقل أجهزة التلفاز الأقل من 40 بوصة مجانًا دون الحاجة لأي مستندات إضافية. يُطلب نموذج إخلاء المسؤولية الموقّع فقط لفئة 40-60 بوصة.",
    },
  ],

  "3o-name-change-3o": [
    {
      chatEn: "I'm sorry, but a complete name change to a different traveller isn't permitted under 3O policy — the ticket is nominative. Let me know if there's anything else I can help with instead.",
      chatAr: "نأسف، تغيير الاسم بالكامل إلى مسافر مختلف غير مسموح وفق سياسة 3O - التذكرة اسمية. أخبروني إذا كان هناك أي شيء آخر يمكنني مساعدتكم به.",
      emailSubjectEn: "Full name change not permitted",
      emailIssueEn: "Thank you for your request to change the traveller's name on your domestic ticket entirely.",
      emailResolutionEn: "A complete name change to a different traveller falls outside our free/paid correction categories and is not permitted under 3O policy, as the ticket is nominative. We're happy to help with a spelling correction if that applies to your case.",
      emailSubjectAr: "عدم إمكانية تغيير الاسم بالكامل",
      emailIssueAr: "شكراً لطلبكم تغيير اسم المسافر بالكامل على تذكرتكم الداخلية.",
      emailResolutionAr: "يقع التغيير الكامل لاسم مسافر مختلف خارج فئات التصحيح المجانية أو المدفوعة، وهو غير مسموح وفق سياسة 3O كون التذكرة اسمية. يسعدنا مساعدتكم في تصحيح إملائي إذا كان ذلك ينطبق على حالتكم.",
    },
    {
      chatEn: "Since your passport number and date of birth are already correct, this qualifies for the fee-based correction — MAD 400 for international or MAD 200 for domestic. Shall I proceed?",
      chatAr: "بما أن رقم جواز سفركم وتاريخ ميلادكم صحيحان بالفعل، فهذا يندرج ضمن التصحيح المدفوع - 400 درهم مغربي للرحلات الدولية أو 200 درهم مغربي للداخلية. هل ترغبون أن أتابع؟",
      emailSubjectEn: "Fee-based name correction",
      emailIssueEn: "Thank you for your request to correct the first name on your booking.",
      emailResolutionEn: "As your passport number and date of birth are already correctly on file, this qualifies for our fee-based correction: MAD 400 for international or MAD 200 for domestic. Please confirm if you'd like us to proceed.",
      emailSubjectAr: "تصحيح اسم مدفوع",
      emailIssueAr: "شكراً لطلبكم تصحيح الاسم الأول على حجزكم.",
      emailResolutionAr: "بما أن رقم جواز سفركم وتاريخ ميلادكم مسجّلان بشكل صحيح، فهذا يندرج ضمن التصحيح المدفوع: 400 درهم مغربي للرحلات الدولية أو 200 درهم مغربي للداخلية. يرجى تأكيد رغبتكم في المتابعة.",
    },
    {
      chatEn: "Congratulations! Updating to your spouse's last name is free of charge — I just need a copy of your marriage certificate to process it.",
      chatAr: "تهانينا! تحديث اللقب إلى لقب زوجكم مجاني - أحتاج فقط نسخة من عقد الزواج لإتمام الإجراء.",
      emailSubjectEn: "Free spouse name update",
      emailIssueEn: "Thank you for your request to update your last name to your spouse's following your recent marriage.",
      emailResolutionEn: "This update is free of charge, provided you supply proof of marriage. Please reply with a copy of your marriage certificate so we can process this correction.",
      emailSubjectAr: "تحديث لقب الزواج مجاني",
      emailIssueAr: "شكراً لطلبكم تحديث لقبكم إلى لقب زوجكم بعد زواجكم الأخير.",
      emailResolutionAr: "هذا التحديث مجاني، شريطة تقديم إثبات الزواج. يرجى الرد بنسخة من عقد الزواج حتى نتمكن من معالجة هذا التصحيح.",
    },
  ],

  "3o-cargo-trade-support-3o": [
    {
      chatEn: "For cargo bookings to or from Morocco, please contact +212 666 28 49 02 or email maccargobooking@airarabia.com — happy to note your inquiry down as well.",
      chatAr: "بالنسبة لحجوزات الشحن من وإلى المغرب، يرجى التواصل عبر +212 666 28 49 02 أو البريد الإلكتروني maccargobooking@airarabia.com - يسعدني أيضًا تسجيل استفساركم.",
      emailSubjectEn: "Cargo booking contact for Morocco",
      emailIssueEn: "Thank you for your inquiry about sending cargo from Casablanca.",
      emailResolutionEn: "Please contact +212 666 28 49 02 or maccargobooking@airarabia.com for cargo booking inquiries to/from Morocco.",
      emailSubjectAr: "جهة التواصل لحجوزات الشحن في المغرب",
      emailIssueAr: "شكراً لاستفساركم عن إرسال شحنة من الدار البيضاء.",
      emailResolutionAr: "يرجى التواصل عبر +212 666 28 49 02 أو البريد الإلكتروني maccargobooking@airarabia.com لاستفسارات حجز الشحن من وإلى المغرب.",
    },
    {
      chatEn: "For Germany specifically, your dedicated contact is macsalessupport-Germany@airarabia.com — that's the fastest way to reach the right team.",
      chatAr: "بالنسبة لألمانيا تحديدًا، جهة التواصل المخصصة لكم هي macsalessupport-Germany@airarabia.com - وهي أسرع طريقة للوصول إلى الفريق المختص.",
      emailSubjectEn: "Germany sales support contact",
      emailIssueEn: "Thank you for asking for your dedicated sales support contact in Germany.",
      emailResolutionEn: "Your dedicated contact for Germany is macsalessupport-Germany@airarabia.com, which will connect you directly with the right support team.",
      emailSubjectAr: "جهة دعم المبيعات في ألمانيا",
      emailIssueAr: "شكراً لاستفساركم عن جهة دعم المبيعات المخصصة لكم في ألمانيا.",
      emailResolutionAr: "جهة التواصل المخصصة لكم في ألمانيا هي macsalessupport-Germany@airarabia.com، والتي ستوصلكم مباشرة بفريق الدعم المختص.",
    },
    {
      chatEn: "Turkey has its own dedicated contact, separate from the general UAE line — please reach out to info@airarabiaturkey.com for local support.",
      chatAr: "تركيا لديها جهة تواصل مخصصة، منفصلة عن الخط العام في الإمارات - يرجى التواصل عبر info@airarabiaturkey.com للحصول على الدعم المحلي.",
      emailSubjectEn: "Turkey local support contact",
      emailIssueEn: "Thank you for confirming whether this is a valid local support number for Turkey.",
      emailResolutionEn: "Turkey has its own dedicated contact, separate from the general UAE Sales Support line: info@airarabiaturkey.com, which we'd recommend using for local support.",
      emailSubjectAr: "جهة الدعم المحلي في تركيا",
      emailIssueAr: "شكراً لتأكدكم من صحة رقم الدعم المحلي في تركيا.",
      emailResolutionAr: "تركيا لديها جهة تواصل مخصصة، منفصلة عن خط دعم المبيعات العام في الإمارات: info@airarabiaturkey.com، وننصح باستخدامها للدعم المحلي.",
    },
  ],

  "3o-name-correction-request-decision-flow-3o": [
    {
      chatEn: "This is a straightforward free spelling correction — I'll submit the fix now and you'll receive the updated itinerary by email within 1–2 hours.",
      chatAr: "هذا تصحيح إملائي بسيط ومجاني - سأقدّم الطلب الآن وستستلمون خط الرحلة المحدث عبر البريد الإلكتروني خلال ساعة إلى ساعتين.",
      emailSubjectEn: "Name correction submitted",
      emailIssueEn: "Thank you for flagging the spelling correction needed on your booking.",
      emailResolutionEn: "We've submitted your name correction request. You'll receive your updated itinerary by email within 1–2 hours.",
      emailSubjectAr: "تم تقديم طلب تصحيح الاسم",
      emailIssueAr: "شكراً لإبلاغنا بالتصحيح الإملائي المطلوب على حجزكم.",
      emailResolutionAr: "لقد قدّمنا طلب تصحيح اسمكم. ستستلمون خط رحلتكم المحدث عبر البريد الإلكتروني خلال ساعة إلى ساعتين.",
    },
    {
      chatEn: "I understand this is urgent given your same-day flight — I'm escalating this via Teams right now and will follow up personally until it's fully resolved.",
      chatAr: "أتفهم أن هذا الأمر عاجل نظرًا لرحلتكم اليوم - سأقوم بتصعيده عبر Teams الآن وسأتابع الأمر شخصيًا حتى يُحل بالكامل.",
      emailSubjectEn: "Urgent same-day correction escalated",
      emailIssueEn: "Thank you for reaching out urgently about your same-day-flight name correction.",
      emailResolutionEn: "As this is a same-day-flight case, we've escalated it via Teams immediately and will follow up until it is resolved.",
      emailSubjectAr: "تصعيد طلب تصحيح عاجل لرحلة اليوم",
      emailIssueAr: "شكراً لتواصلكم العاجل بخصوص تصحيح اسم لرحلة اليوم نفسه.",
      emailResolutionAr: "بما أن هذه حالة تخص رحلة اليوم نفسه، قمنا بتصعيدها فورًا عبر Teams وسنتابعها حتى يتم حلها.",
    },
    {
      chatEn: "Since your passport number and date of birth are already correct on file, I can raise this as a paid correction case now — please send proof of documents and expect a reply within 24 hours.",
      chatAr: "بما أن رقم جواز سفركم وتاريخ ميلادكم مسجّلان بشكل صحيح، يمكنني فتح هذا كطلب تصحيح مدفوع الآن - يرجى إرسال المستندات المطلوبة وتوقع الرد خلال 24 ساعة.",
      emailSubjectEn: "Paid name correction — documents requested",
      emailIssueEn: "Thank you for your request to correct a misspelled first name on your booking.",
      emailResolutionEn: "As your passport number and date of birth are already verified on file, we've raised this as a fee-applicable correction case. Please reply with proof of documents, and expect a response within 24 hours of submission.",
      emailSubjectAr: "تصحيح اسم مدفوع - مستندات مطلوبة",
      emailIssueAr: "شكراً لطلبكم تصحيح خطأ إملائي في الاسم الأول على حجزكم.",
      emailResolutionAr: "بما أن رقم جواز سفركم وتاريخ ميلادكم موثّقان بالفعل، فتحنا هذا كطلب تصحيح تُطبَّق عليه رسوم. يرجى الرد بالمستندات المطلوبة، وتوقعوا الرد خلال 24 ساعة من الإرسال.",
    },
  ],
};
