import type { ArticleTemplateSet } from "./types";

export const NINE_P_TEMPLATES: Record<string, ArticleTemplateSet> = {
  "9p-bundle-fares-9p-domestic-international": [
    {
      chatEn: "I'll double check the confirmed bundle chart for Value on the domestic route rather than guess — let me get back to you with the exact inclusions in just a moment.",
      chatAr: "سأتحقق من جدول الباقات المعتمد لباقة Value على المسار الداخلي بدلاً من التخمين - سأعود إليكم بالتفاصيل الدقيقة خلال لحظات.",
      emailSubjectEn: "Confirming Value bundle inclusions",
      emailIssueEn: "Thank you for asking what's included in the domestic Value bundle.",
      emailResolutionEn: "We want to make sure you get the exact, current inclusions rather than an estimate — we're confirming this against the latest Fly Jinnah fare filing and will follow up with the precise details shortly.",
      emailSubjectAr: "تأكيد تفاصيل باقة Value",
      emailIssueAr: "شكراً لاستفساركم عمّا تتضمنه باقة Value الداخلية.",
      emailResolutionAr: "نحرص على تزويدكم بالتفاصيل الدقيقة والمحدثة بدلاً من التقدير - نقوم حاليًا بالتحقق من ذلك مقابل أحدث تسعيرة معتمدة لدى Fly Jinnah وسنتابع معكم بالتفاصيل الدقيقة قريبًا.",
    },
    {
      chatEn: "Happy to help, but full Terms & Conditions are a bit much for a call — let's just cover the modification/cancellation cut-off time and what's included in Ultimate, which is usually what matters most.",
      chatAr: "يسعدني المساعدة، لكن الشروط والأحكام الكاملة مطوّلة بعض الشيء لمكالمة هاتفية - دعونا نغطي مهلة التعديل والإلغاء وما تتضمنه باقة Ultimate، فهذا عادةً ما يهم أكثر.",
      emailSubjectEn: "Ultimate bundle — key terms",
      emailIssueEn: "Thank you for asking about the full terms and conditions of the Ultimate bundle.",
      emailResolutionEn: "Rather than the full T&Cs, here's what matters most: the modification/cancellation cut-off time for Ultimate, and what's included in the bundle. Let us know if you'd like us to walk through either in more detail.",
      emailSubjectAr: "باقة Ultimate - أهم الشروط",
      emailIssueAr: "شكراً لاستفساركم عن الشروط والأحكام الكاملة لباقة Ultimate.",
      emailResolutionAr: "بدلاً من الشروط والأحكام الكاملة، إليكم أهم ما يخصكم: مهلة التعديل والإلغاء لباقة Ultimate وما تتضمنه الباقة. يرجى إخبارنا إذا رغبتم بتفاصيل إضافية حول أي منهما.",
    },
    {
      chatEn: "Yes, 9P uses separate Domestic and International bundle structures, but both follow the same Basic/Value/Ultimate naming — I'll confirm the exact inclusions for your specific sector.",
      chatAr: "نعم، تستخدم 9P هياكل باقات منفصلة للرحلات الداخلية والدولية، لكن كلاهما يتبع نفس التسمية Basic وValue وUltimate - سأؤكد لكم التفاصيل الدقيقة لمسار رحلتكم.",
      emailSubjectEn: "Domestic vs. international bundle naming",
      emailIssueEn: "Thank you for asking whether 9P domestic and international bundles share the same names.",
      emailResolutionEn: "Yes, 9P uses separate Domestic and International bundle structures, but both follow the same Basic/Value/Ultimate tier naming. Let us know your sector and we'll confirm exact inclusions.",
      emailSubjectAr: "تسمية الباقات الداخلية والدولية",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كانت باقات 9P الداخلية والدولية تحمل نفس الأسماء.",
      emailResolutionAr: "نعم، تستخدم 9P هياكل باقات منفصلة للرحلات الداخلية والدولية، لكن كلاهما يتبع نفس تسمية الفئات Basic وValue وUltimate. يرجى إخبارنا بمسار رحلتكم وسنؤكد التفاصيل الدقيقة.",
    },
  ],

  "9p-excess-baggage-rates-9p": [
    {
      chatEn: "I see the item measures 320cm, which is over our 305cm oversize limit — let me escalate this to confirm whether it can be accepted at all before I quote a rate.",
      chatAr: "ألاحظ أن حجم الغرض 320 سم، وهو يتجاوز الحد الأقصى للأحجام الكبيرة البالغ 305 سم - دعوني أصعّد هذا الطلب للتحقق من إمكانية قبوله قبل تحديد أي رسوم.",
      emailSubjectEn: "Oversized item exceeds our limit",
      emailIssueEn: "Thank you for checking in about your 320cm oversized item on your domestic 9P flight.",
      emailResolutionEn: "Our oversize baggage rate of PKR 3,000 applies up to 305cm; your item at 320cm exceeds this maximum. We're escalating this to confirm whether it can be accepted before quoting a rate.",
      emailSubjectAr: "الغرض يتجاوز الحد المسموح للحجم",
      emailIssueAr: "شكراً لتواصلكم بخصوص غرضكم كبير الحجم 320 سم على رحلتكم الداخلية على 9P.",
      emailResolutionAr: "تنطبق رسوم الأحجام الكبيرة البالغة 3,000 روبية باكستانية حتى 305 سم؛ وغرضكم بحجم 320 سم يتجاوز هذا الحد. نقوم بتصعيد الطلب للتحقق من إمكانية قبوله قبل تحديد أي رسوم.",
    },
    {
      chatEn: "For a direct international flight into Pakistan, the excess baggage rate is AED 60 per kg — it would be AED 70 per kg if it were a connecting flight instead.",
      chatAr: "بالنسبة لرحلة دولية مباشرة إلى باكستان، تبلغ رسوم الوزن الزائد 60 درهمًا إماراتيًا لكل كيلوغرام - وتصبح 70 درهمًا لكل كيلوغرام في حال كانت الرحلة عبر محطة وصل.",
      emailSubjectEn: "Excess baggage rate for your arrival to Pakistan",
      emailIssueEn: "Thank you for asking about the excess baggage rate for your direct international flight into Pakistan.",
      emailResolutionEn: "For international sectors arriving in Pakistan on a direct flight, the excess baggage rate is AED 60 per kg (AED 70 per kg for a connecting flight).",
      emailSubjectAr: "رسوم الوزن الزائد لرحلتكم إلى باكستان",
      emailIssueAr: "شكراً لاستفساركم عن رسوم الوزن الزائد لرحلتكم الدولية المباشرة إلى باكستان.",
      emailResolutionAr: "بالنسبة للقطاعات الدولية الواصلة إلى باكستان في رحلة مباشرة، تبلغ رسوم الوزن الزائد 60 درهمًا إماراتيًا لكل كيلوغرام (70 درهمًا لكل كيلوغرام للرحلات عبر محطة وصل).",
    },
    {
      chatEn: "Good news — a carton box is accepted on this route at PKR 3,800, unlike flights arriving into Pakistan where carton boxes aren't accepted at all.",
      chatAr: "خبر سار - يُقبل صندوق الكرتون على هذا المسار مقابل 3,800 روبية باكستانية، على عكس الرحلات الواصلة إلى باكستان حيث لا تُقبل صناديق الكرتون إطلاقًا.",
      emailSubjectEn: "Carton box accepted on this route",
      emailIssueEn: "Thank you for checking whether a carton box can be checked in on your international departure from Pakistan.",
      emailResolutionEn: "A carton box is accepted on this route at PKR 3,800 — this differs from sectors arriving into Pakistan, where carton boxes are not accepted at all (N/A).",
      emailSubjectAr: "قبول صندوق الكرتون على هذا المسار",
      emailIssueAr: "شكراً لاستفساركم عن إمكانية تسجيل صندوق كرتون على رحلتكم الدولية المغادرة من باكستان.",
      emailResolutionAr: "يُقبل صندوق الكرتون على هذا المسار مقابل 3,800 روبية باكستانية - ويختلف ذلك عن القطاعات الواصلة إلى باكستان حيث لا تُقبل صناديق الكرتون إطلاقًا (غير متاح).",
    },
  ],

  "9p-tv-handling-9p": [
    {
      chatEn: "For a 50-inch TV on a domestic sector, the charge is PKR 2,500 plus the airport handling fee — happy to add that note to your booking now.",
      chatAr: "بالنسبة لتلفاز 50 بوصة على رحلة داخلية، تبلغ الرسوم 2,500 روبية باكستانية بالإضافة إلى رسوم مناولة المطار - يسعدني تسجيل ذلك على حجزكم الآن.",
      emailSubjectEn: "50-inch TV charge on your domestic flight",
      emailIssueEn: "Thank you for checking in about bringing your 50-inch TV on your domestic 9P flight.",
      emailResolutionEn: "A 40–60 inch TV on a domestic sector is charged PKR 2,500 plus the airport handling fee. We've noted this for your booking.",
      emailSubjectAr: "رسوم تلفاز 50 بوصة على رحلتكم الداخلية",
      emailIssueAr: "شكراً لتواصلكم بخصوص إحضار تلفازكم بحجم 50 بوصة على رحلتكم الداخلية على 9P.",
      emailResolutionAr: "تُحتسب رسوم تلفاز بحجم 40-60 بوصة على الرحلات الداخلية بمبلغ 2,500 روبية باكستانية بالإضافة إلى رسوم مناولة المطار. لقد سجّلنا ذلك على حجزكم.",
    },
    {
      chatEn: "On international sectors, that 40–60 inch band is AED 150 plus the airport handling fee, rather than the domestic PKR rate — let me know if you'd like this added to your booking.",
      chatAr: "على القطاعات الدولية، تبلغ رسوم فئة 40-60 بوصة 150 درهمًا إماراتيًا بالإضافة إلى رسوم مناولة المطار، بدلاً من الرسوم الداخلية بالروبية - أخبروني إذا رغبتم بإضافة ذلك إلى حجزكم.",
      emailSubjectEn: "55-inch TV charge on your international flight",
      emailIssueEn: "Thank you for checking in about bringing your 55-inch TV on your international 9P flight.",
      emailResolutionEn: "On international sectors, the 40–60 inch band is charged AED 150 plus the airport handling fee, rather than the domestic PKR rate. Let us know if you'd like this noted on your booking.",
      emailSubjectAr: "رسوم تلفاز 55 بوصة على رحلتكم الدولية",
      emailIssueAr: "شكراً لتواصلكم بخصوص إحضار تلفازكم بحجم 55 بوصة على رحلتكم الدولية على 9P.",
      emailResolutionAr: "على القطاعات الدولية، تُحتسب رسوم فئة 40-60 بوصة بمبلغ 150 درهمًا إماراتيًا بالإضافة إلى رسوم مناولة المطار، بدلاً من الرسوم الداخلية بالروبية. يرجى إخبارنا إذا رغبتم بتسجيل ذلك على حجزكم.",
    },
    {
      chatEn: "No cap at all — you're welcome to bring as many TVs as you'd like, each one just charged individually based on its size band.",
      chatAr: "لا يوجد أي حد أقصى - يمكنكم إحضار أي عدد من أجهزة التلفاز، مع احتساب رسوم كل جهاز بشكل منفصل حسب فئة حجمه.",
      emailSubjectEn: "No limit on number of TVs",
      emailIssueEn: "Thank you for asking whether there's a cap on the number of TVs you can bring.",
      emailResolutionEn: "There is no limit on the number of TVs per passenger, though each one is charged individually based on its size band.",
      emailSubjectAr: "عدم وجود حد لعدد أجهزة التلفاز",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كان هناك حد أقصى لعدد أجهزة التلفاز التي يمكنكم إحضارها.",
      emailResolutionAr: "لا يوجد حد أقصى لعدد أجهزة التلفاز لكل مسافر، مع احتساب رسوم كل جهاز بشكل منفصل حسب فئة حجمه.",
    },
  ],

  "9p-name-change-9p": [
    {
      chatEn: "For a name change paid in AED, the charge is AED 350 per passenger plus the fare difference — the PKR 3,500 figure you may have seen is just the local-currency equivalent for domestic payment.",
      chatAr: "بالنسبة لتغيير الاسم المدفوع بالدرهم الإماراتي، تبلغ الرسوم 350 درهمًا لكل مسافر بالإضافة إلى فرق السعر - أما مبلغ 3,500 روبية فهو المكافئ بالعملة المحلية للدفع الداخلي.",
      emailSubjectEn: "Name change fee in AED",
      emailIssueEn: "Thank you for asking about the name change fee payable in AED.",
      emailResolutionEn: "The name change fee is AED 350 per passenger plus the fare difference. The PKR 3,500 figure is the local-currency equivalent used for domestic payment.",
      emailSubjectAr: "رسوم تغيير الاسم بالدرهم الإماراتي",
      emailIssueAr: "شكراً لاستفساركم عن رسوم تغيير الاسم المدفوعة بالدرهم الإماراتي.",
      emailResolutionAr: "تبلغ رسوم تغيير الاسم 350 درهمًا إماراتيًا لكل مسافر بالإضافة إلى فرق السعر. مبلغ 3,500 روبية باكستانية هو المكافئ بالعملة المحلية المستخدم للدفع الداخلي.",
    },
    {
      chatEn: "Since your spouse counts as immediate family, this is permitted — the international fee is AED 350 per passenger plus fare difference. I'll raise a Sprinklr case now; please send proof of relationship.",
      chatAr: "بما أن زوجكم/زوجتكم يُعد من أفراد العائلة المباشرين، فهذا الطلب مسموح - تبلغ الرسوم الدولية 350 درهمًا لكل مسافر بالإضافة إلى فرق السعر. سأفتح حالة على Sprinklr الآن؛ يرجى إرسال إثبات صلة القرابة.",
      emailSubjectEn: "Name change using spousal credit",
      emailIssueEn: "Thank you for your request to use a credit voucher for a name change on your international 9P sector for your spouse.",
      emailResolutionEn: "A spouse qualifies as immediate family, so this is permitted. The international fee is AED 350 per passenger plus fare difference. We've raised a Sprinklr case — please send proof of relationship so we can proceed.",
      emailSubjectAr: "تغيير الاسم باستخدام رصيد الزوج/الزوجة",
      emailIssueAr: "شكراً لطلبكم استخدام قسيمة رصيد لتغيير اسم زوجكم/زوجتكم على القطاع الدولي على 9P.",
      emailResolutionAr: "يُعد الزوج/الزوجة من أفراد العائلة المباشرين، وبالتالي هذا الطلب مسموح. تبلغ الرسوم الدولية 350 درهمًا إماراتيًا لكل مسافر بالإضافة إلى فرق السعر. لقد فتحنا حالة على Sprinklr - يرجى إرسال إثبات صلة القرابة لنتمكن من المتابعة.",
    },
    {
      chatEn: "Congratulations on the wedding! Updating to your husband's last name is free of charge — please send proof of documents like the marriage certificate, and I'll forward this directly to a supervisor.",
      chatAr: "تهانينا بالزواج! تحديث اللقب إلى لقب زوجكم مجاني - يرجى إرسال المستندات المطلوبة مثل عقد الزواج، وسأحيل الطلب مباشرة إلى المشرف.",
      emailSubjectEn: "Free name update after marriage",
      emailIssueEn: "Thank you for your request to update your ticket to your husband's last name.",
      emailResolutionEn: "This update is free of charge. Please send proof of documents (e.g. marriage certificate) — we're forwarding this directly to a supervisor for processing rather than raising a Sprinklr case.",
      emailSubjectAr: "تحديث اسم مجاني بعد الزواج",
      emailIssueAr: "شكراً لطلبكم تحديث تذكرتكم إلى لقب زوجكم.",
      emailResolutionAr: "هذا التحديث مجاني. يرجى إرسال المستندات المطلوبة (مثل عقد الزواج) - سنحيل هذا الطلب مباشرة إلى المشرف للمعالجة بدلاً من فتح حالة على Sprinklr.",
    },
  ],

  "9p-ok-to-board-otb-9p": [
    {
      chatEn: "Good news — Ok to Board processing is free of charge at our Pakistan offices (it's only AED 15–20 per passenger at UAE offices). You'll still need your visa copy, passport and PNR, at least 24 hours before departure.",
      chatAr: "خبر سار - معالجة رسالة الموافقة على الصعود مجانية في مكاتبنا في باكستان (تبلغ فقط 15-20 درهمًا إماراتيًا لكل مسافر في مكاتب الإمارات). ستحتاجون لنسخة التأشيرة وجواز السفر ورقم الحجز، قبل 24 ساعة على الأقل من المغادرة.",
      emailSubjectEn: "Ok to Board is free at Pakistan offices",
      emailIssueEn: "Thank you for asking whether there's a charge for Ok to Board processing.",
      emailResolutionEn: "Ok to Board processing is free of charge at our Pakistan offices (AED 15–20 per passenger at UAE offices). You'll still need to bring your visa copy, passport and PNR, at least 24 hours before departure.",
      emailSubjectAr: "الموافقة على الصعود مجانية في مكاتب باكستان",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كانت هناك رسوم لمعالجة الموافقة على الصعود.",
      emailResolutionAr: "معالجة رسالة الموافقة على الصعود مجانية في مكاتبنا في باكستان (15-20 درهمًا إماراتيًا لكل مسافر في مكاتب الإمارات). ستحتاجون لإحضار نسخة التأشيرة وجواز السفر ورقم الحجز، قبل 24 ساعة على الأقل من المغادرة.",
    },
    {
      chatEn: "I completely understand the urgency — please visit the office as soon as you possibly can. Staff will do their best to help even inside the normal 24-hour window, though it can't be guaranteed.",
      chatAr: "أتفهم تمامًا إلحاح الأمر - يرجى زيارة المكتب في أقرب وقت ممكن. سيبذل الموظفون قصارى جهدهم للمساعدة حتى ضمن مهلة الـ 24 ساعة المعتادة، رغم أن ذلك غير مضمون.",
      emailSubjectEn: "Urgent Ok to Board update",
      emailIssueEn: "Thank you for reaching out urgently as your OTB message still isn't updated with less than 24 hours to departure.",
      emailResolutionEn: "Please visit an office as soon as possible. Our staff will do their best to assist even given the short notice, though this cannot be guaranteed.",
      emailSubjectAr: "تحديث عاجل لرسالة الموافقة على الصعود",
      emailIssueAr: "شكراً لتواصلكم العاجل حيث لا تزال رسالة الموافقة على الصعود غير محدثة وموعد رحلتكم أقل من 24 ساعة.",
      emailResolutionAr: "يرجى زيارة أحد المكاتب في أقرب وقت ممكن. سيبذل موظفونا قصارى جهدهم للمساعدة رغم ضيق الوقت، إلا أن ذلك غير مضمون.",
    },
    {
      chatEn: "Yes — Bangladesh is one of the three origin countries where Ok to Board is mandatory for UAE-bound passengers holding a UAE visa copy, so this does apply to you.",
      chatAr: "نعم - بنغلاديش من ضمن الدول الثلاث التي تُعد فيها الموافقة على الصعود إلزامية للمسافرين إلى الإمارات الحاملين نسخة تأشيرة إماراتية، وبالتالي هذا ينطبق عليكم.",
      emailSubjectEn: "Ok to Board applies to your Dhaka departure",
      emailIssueEn: "Thank you for asking whether Ok to Board applies to your flight from Dhaka to the UAE.",
      emailResolutionEn: "Yes — Bangladesh is one of the three origin countries (with India and Pakistan) where Ok to Board is mandatory for UAE-bound passengers holding a UAE visa copy.",
      emailSubjectAr: "الموافقة على الصعود تنطبق على رحلتكم من دكا",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كانت الموافقة على الصعود تنطبق على رحلتكم من دكا إلى الإمارات.",
      emailResolutionAr: "نعم - بنغلاديش إحدى الدول الثلاث (مع الهند وباكستان) التي تُعد فيها الموافقة على الصعود إلزامية للمسافرين إلى الإمارات الحاملين نسخة تأشيرة إماراتية.",
    },
  ],

  "9p-apwtac-military-vouchers-9p": [
    {
      chatEn: "For a spouse travelling on a military voucher, that would be a TAC certificate rather than APW, since APW covers the officer's own duty movement only. Happy to explain the TAC requirements.",
      chatAr: "بالنسبة لسفر الزوج/الزوجة بقسيمة عسكرية، سيكون ذلك عبر شهادة TAC وليس APW، حيث تغطي APW حركة تنقل الضابط الرسمية فقط. يسعدني توضيح متطلبات TAC.",
      emailSubjectEn: "TAC vs. APW for family travel",
      emailIssueEn: "Thank you for asking about your spouse travelling using your military voucher.",
      emailResolutionEn: "Family members travel under a TAC (Travel Authorization Certificate), not an APW, which is reserved for the officer's own duty movement only. Let us know if you'd like the TAC document requirements.",
      emailSubjectAr: "الفرق بين TAC وAPW لسفر العائلة",
      emailIssueAr: "شكراً لاستفساركم عن سفر زوجكم/زوجتكم باستخدام قسيمتكم العسكرية.",
      emailResolutionAr: "يسافر أفراد العائلة بموجب شهادة TAC (تصريح السفر)، وليس APW المخصصة لحركة تنقل الضابط الرسمية فقط. يرجى إخبارنا إذا رغبتم بمعرفة المستندات المطلوبة لشهادة TAC.",
    },
    {
      chatEn: "Good news — TAC tickets can be booked on any bundle, including Basic, unlike APW which is restricted to Value Flex and Ultimate only.",
      chatAr: "خبر سار - يمكن حجز تذاكر TAC على أي باقة، بما في ذلك Basic، على عكس APW المقتصرة على باقتَي Value Flex وUltimate فقط.",
      emailSubjectEn: "TAC bundle flexibility",
      emailIssueEn: "Thank you for asking whether a TAC voucher can be booked on the Basic bundle.",
      emailResolutionEn: "TAC tickets can be booked on any bundle, including Basic — this is allowed, unlike APW tickets which are restricted to the Value Flex and Ultimate bundles.",
      emailSubjectAr: "مرونة باقات TAC",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كان يمكن حجز قسيمة TAC على باقة Basic.",
      emailResolutionAr: "يمكن حجز تذاكر TAC على أي باقة، بما فيها Basic - وهذا مسموح، على عكس تذاكر APW المقتصرة على باقتَي Value Flex وUltimate.",
    },
    {
      chatEn: "For a brand-new booking using an APW voucher, you'll need to visit a 9P sales office directly rather than book over the phone — happy to point you to your nearest office.",
      chatAr: "بالنسبة لحجز جديد باستخدام قسيمة APW، ستحتاجون لزيارة أحد مكاتب مبيعات 9P مباشرة بدلاً من الحجز عبر الهاتف - يسعدني إرشادكم لأقرب مكتب لكم.",
      emailSubjectEn: "New APW booking requires an office visit",
      emailIssueEn: "Thank you for your request to book a new ticket using your APW voucher over the phone.",
      emailResolutionEn: "New bookings using an APW, TAC, or Parliamentary voucher must be completed at a 9P sales office and can't be processed over the phone. Please visit your nearest 9P sales office to complete this booking.",
      emailSubjectAr: "حجز APW جديد يتطلب زيارة المكتب",
      emailIssueAr: "شكراً لطلبكم حجز تذكرة جديدة باستخدام قسيمة APW عبر الهاتف.",
      emailResolutionAr: "يجب إتمام الحجوزات الجديدة باستخدام قسيمة APW أو TAC أو برلمانية في أحد مكاتب مبيعات 9P، ولا يمكن معالجتها عبر الهاتف. يرجى زيارة أقرب مكتب مبيعات لـ 9P لإتمام هذا الحجز.",
    },
  ],

  "9p-transport-of-dead-body-9p": [
    {
      chatEn: "I'm very sorry for your loss. You'll need a government-hospital-attested death certificate with CNIC copy, a coffin box certificate from a certified provider, a police station NOC, and the deceased's CNIC copy, plus one attendant with a confirmed ticket.",
      chatAr: "نتقدم بأحر التعازي لكم. ستحتاجون إلى شهادة وفاة موثّقة من مستشفى حكومي مع نسخة الهوية الوطنية، وشهادة صندوق النعش من مزوّد معتمد، وخطاب عدم ممانعة من مركز الشرطة، ونسخة الهوية الوطنية للمتوفى، بالإضافة إلى مرافق واحد بتذكرة مؤكدة.",
      emailSubjectEn: "Documents required for transporting a deceased passenger",
      emailIssueEn: "We're very sorry for your loss, and thank you for reaching out about the documents required to transport your relative.",
      emailResolutionEn: "You'll need: a death certificate attested by a government hospital (with CNIC copy), a coffin box certificate from a certified provider, a police station NOC, and the deceased's CNIC copy, plus one attendant travelling with a confirmed ticket.",
      emailSubjectAr: "المستندات المطلوبة لنقل جثمان",
      emailIssueAr: "نتقدم بأحر التعازي لكم، ونشكركم على تواصلكم بخصوص المستندات المطلوبة لنقل جثمان قريبكم.",
      emailResolutionAr: "ستحتاجون إلى: شهادة وفاة موثّقة من مستشفى حكومي (مع نسخة الهوية الوطنية)، وشهادة صندوق نعش من مزوّد معتمد، وخطاب عدم ممانعة من مركز الشرطة، ونسخة الهوية الوطنية للمتوفى، بالإضافة إلى مرافق واحد يسافر بتذكرة مؤكدة.",
    },
    {
      chatEn: "I understand this is a difficult time. The total charge is PKR 20,000 plus applicable airport handling fees — I'm here to help you through the rest of the process too.",
      chatAr: "أتفهم أن هذا وقت عصيب عليكم. تبلغ التكلفة الإجمالية 20,000 روبية باكستانية بالإضافة إلى رسوم مناولة المطار المعمول بها - وأنا هنا لمساعدتكم في باقي خطوات هذا الإجراء.",
      emailSubjectEn: "Cost of transporting a deceased passenger",
      emailIssueEn: "We're very sorry for your loss, and thank you for asking about the total cost of this arrangement.",
      emailResolutionEn: "The charge is PKR 20,000 plus applicable airport handling fees. Please let us know if we can assist with any other part of the arrangements.",
      emailSubjectAr: "تكلفة نقل الجثمان",
      emailIssueAr: "نتقدم بأحر التعازي لكم، ونشكركم على استفساركم عن التكلفة الإجمالية لهذا الترتيب.",
      emailResolutionAr: "تبلغ التكلفة 20,000 روبية باكستانية بالإضافة إلى رسوم مناولة المطار المعمول بها. يرجى إخبارنا إذا كان بإمكاننا المساعدة في أي جزء آخر من الترتيبات.",
    },
    {
      chatEn: "Please plan to arrive strictly one hour before departure, at cargo — not at the standard passenger check-in counter. Our 24/7 line +92 300 8214381 is also available if you need help along the way.",
      chatAr: "يرجى التخطيط للوصول قبل ساعة واحدة بالضبط من موعد المغادرة، عند قسم الشحن - وليس عند كاونتر تسجيل وصول الركاب المعتاد. خطنا المتاح على مدار الساعة +92 300 8214381 جاهز أيضًا لمساعدتكم في أي وقت.",
      emailSubjectEn: "Reporting time at cargo",
      emailIssueEn: "Thank you for asking how late you can arrive before departure.",
      emailResolutionEn: "Last reporting time is strictly one hour before departure, at the cargo terminal — not the standard passenger check-in counter. For urgent assistance at any time, please call our 24/7 line: +92 300 8214381.",
      emailSubjectAr: "موعد الحضور عند قسم الشحن",
      emailIssueAr: "شكراً لاستفساركم عن آخر موعد يمكنكم فيه الوصول قبل المغادرة.",
      emailResolutionAr: "آخر موعد للحضور هو ساعة واحدة بالضبط قبل المغادرة، عند محطة الشحن - وليس عند كاونتر تسجيل وصول الركاب المعتاد. للمساعدة العاجلة في أي وقت، يرجى الاتصال بخطنا المتاح على مدار الساعة: +92 300 8214381.",
    },
  ],
};
