import type { ArticleTemplateSet } from "./types";

export const E5_TEMPLATES: Record<string, ArticleTemplateSet> = {
  "e5-excess-baggage-rates-e5": [
    {
      chatEn: "From Egypt to Sharjah, the excess baggage rate is EGP 450 per kilo — that's actually the highest of our 'from Egypt' rates, so let me know if you'd like to pre-purchase weight to save.",
      chatAr: "من مصر إلى الشارقة، تبلغ رسوم الوزن الزائد 450 جنيهًا مصريًا لكل كيلوغرام - وهي أعلى رسوم ضمن مسارات 'من مصر'، فأخبروني إذا رغبتم بشراء وزن مسبق للتوفير.",
      emailSubjectEn: "Excess baggage rate to Sharjah",
      emailIssueEn: "Thank you for asking about the excess baggage rate from Cairo to Sharjah.",
      emailResolutionEn: "From Egypt to Sharjah, the rate is EGP 450 per kg — the highest of our 'from Egypt' rates. Pre-purchasing extra weight in advance is often more economical; let us know if you'd like to add it now.",
      emailSubjectAr: "رسوم الوزن الزائد إلى الشارقة",
      emailIssueAr: "شكراً لاستفساركم عن رسوم الوزن الزائد من القاهرة إلى الشارقة.",
      emailResolutionAr: "من مصر إلى الشارقة، تبلغ الرسوم 450 جنيهًا مصريًا لكل كيلوغرام - وهي الأعلى ضمن مسارات 'من مصر'. غالبًا ما يكون شراء الوزن الإضافي مسبقًا أكثر اقتصادًا؛ يرجى إخبارنا إذا رغبتم بإضافته الآن.",
    },
    {
      chatEn: "Kuwait isn't listed separately for 'to Egypt' no-baggage pricing, so we'd use the 'all other destinations' rate of AED 50 for your first 20kg.",
      chatAr: "الكويت غير مدرجة بشكل منفصل ضمن تسعير 'إلى مصر' بدون باقة أمتعة، لذا سنستخدم رسوم 'باقي الوجهات' البالغة 50 درهمًا إماراتيًا لأول 20 كجم.",
      emailSubjectEn: "First-20kg rate from Kuwait to Cairo",
      emailIssueEn: "Thank you for asking about the first-20kg rate for your no-baggage-fare flight into Cairo from Kuwait.",
      emailResolutionEn: "Kuwait isn't listed separately for 'to Egypt' no-baggage pricing, so the 'all other destinations' rate of AED 50 applies for your first 20kg.",
      emailSubjectAr: "رسوم أول 20 كجم من الكويت إلى القاهرة",
      emailIssueAr: "شكراً لاستفساركم عن رسوم أول 20 كجم لرحلتكم بدون باقة أمتعة إلى القاهرة من الكويت.",
      emailResolutionAr: "الكويت غير مدرجة بشكل منفصل ضمن تسعير 'إلى مصر' بدون باقة أمتعة، لذا تُطبَّق رسوم 'باقي الوجهات' البالغة 50 درهمًا إماراتيًا لأول 20 كجم.",
    },
    {
      chatEn: "From Amman to Cairo, the excess baggage rate is JOD 6 per kilo — happy to add the extra weight to your booking now if that's helpful.",
      chatAr: "من عمّان إلى القاهرة، تبلغ رسوم الوزن الزائد 6 دنانير أردنية لكل كيلوغرام - يسعدني إضافة الوزن الزائد إلى حجزكم الآن إذا كان ذلك مفيدًا لكم.",
      emailSubjectEn: "Excess baggage rate from Amman",
      emailIssueEn: "Thank you for asking about the excess baggage rate from Amman to Cairo.",
      emailResolutionEn: "The 'to Egypt' rate from Amman is JOD 6 per kg. Let us know if you'd like this added to your booking in advance.",
      emailSubjectAr: "رسوم الوزن الزائد من عمّان",
      emailIssueAr: "شكراً لاستفساركم عن رسوم الوزن الزائد من عمّان إلى القاهرة.",
      emailResolutionAr: "تبلغ رسوم 'إلى مصر' من عمّان 6 دنانير أردنية لكل كيلوغرام. يرجى إخبارنا إذا رغبتم بإضافة ذلك إلى حجزكم مسبقًا.",
    },
  ],

  "e5-tv-handling-e5": [
    {
      chatEn: "Good news — a 38-inch TV travels completely free of charge, with no additional fee at all.",
      chatAr: "خبر سار - يُنقل تلفاز بحجم 38 بوصة مجانًا بالكامل، دون أي رسوم إضافية.",
      emailSubjectEn: "38-inch TV — free of charge",
      emailIssueEn: "Thank you for asking about carrying your 38-inch TV on your E5 flight.",
      emailResolutionEn: "TVs under 40 inches travel free of charge, with no additional fee.",
      emailSubjectAr: "تلفاز 38 بوصة - مجاني",
      emailIssueAr: "شكراً لاستفساركم عن إحضار تلفازكم بحجم 38 بوصة على رحلتكم على E5.",
      emailResolutionAr: "تُنقل أجهزة التلفاز التي يقل حجمها عن 40 بوصة مجانًا، دون أي رسوم إضافية.",
    },
    {
      chatEn: "I'm sorry, but a 65-inch TV can't be accepted — our maximum accepted size on E5 is 60 inches. Could you arrange alternative shipping for it?",
      chatAr: "نأسف، لا يمكن قبول تلفاز بحجم 65 بوصة - الحد الأقصى المسموح به على E5 هو 60 بوصة. هل يمكنكم ترتيب شحن بديل له؟",
      emailSubjectEn: "TV size exceeds accepted limit",
      emailIssueEn: "Thank you for checking whether your 65-inch TV can be checked in.",
      emailResolutionEn: "Unfortunately TVs over 60 inches cannot be accepted on E5 flights — this is our maximum accepted size.",
      emailSubjectAr: "حجم التلفاز يتجاوز الحد المسموح",
      emailIssueAr: "شكراً لاستفساركم عن إمكانية تسجيل تلفازكم بحجم 65 بوصة.",
      emailResolutionAr: "للأسف، لا يمكن قبول أجهزة التلفاز التي يتجاوز حجمها 60 بوصة على رحلات E5 - وهو الحد الأقصى المسموح به.",
    },
    {
      chatEn: "For a 45-inch TV, the charge is EGP 2,000 plus airport handling fees — happy to add that to your booking now.",
      chatAr: "بالنسبة لتلفاز بحجم 45 بوصة، تبلغ الرسوم 2,000 جنيه مصري بالإضافة إلى رسوم مناولة المطار - يسعدني إضافة ذلك إلى حجزكم الآن.",
      emailSubjectEn: "45-inch TV charge",
      emailIssueEn: "Thank you for asking about the fee for your 45-inch TV.",
      emailResolutionEn: "As it falls in the 40–60 inch band, the charge is EGP 2,000 per TV plus airport handling fees.",
      emailSubjectAr: "رسوم تلفاز 45 بوصة",
      emailIssueAr: "شكراً لاستفساركم عن رسوم تلفازكم بحجم 45 بوصة.",
      emailResolutionAr: "بما أنه يقع ضمن فئة 40-60 بوصة، تبلغ الرسوم 2,000 جنيه مصري لكل جهاز بالإضافة إلى رسوم مناولة المطار.",
    },
  ],

  "e5-cargo-trade-contacts-e5": [
    {
      chatEn: "For travel agency support in Egypt, please contact 002-03 419 7635 or 002-011 299 152 99 — the cargo line is separate, for shipment inquiries only.",
      chatAr: "لدعم وكالات السفريات في مصر، يرجى التواصل عبر 002-03 419 7635 أو 002-011 299 152 99 - خط الشحن منفصل ومخصص فقط لاستفسارات الشحنات.",
      emailSubjectEn: "E5 travel agency support numbers",
      emailIssueEn: "Thank you for reaching out to confirm the correct support line for your travel agency.",
      emailResolutionEn: "For travel agency support, please contact 002-03 419 7635 or 002-011 299 152 99. The cargo line (002-0114 708 8814) is for shipment inquiries only.",
      emailSubjectAr: "أرقام دعم وكالات السفريات على E5",
      emailIssueAr: "شكراً لتواصلكم للتأكد من خط الدعم الصحيح لوكالتكم.",
      emailResolutionAr: "لدعم وكالات السفريات، يرجى التواصل عبر 002-03 419 7635 أو 002-011 299 152 99. خط الشحن (002-0114 708 8814) مخصص فقط لاستفسارات الشحنات.",
    },
    {
      chatEn: "For sending cargo from Egypt, please contact 002-0114 708 8814 — they'll be able to help with your shipment directly.",
      chatAr: "لإرسال شحنة من مصر، يرجى التواصل عبر 002-0114 708 8814 - سيتمكنون من مساعدتكم مباشرة بخصوص شحنتكم.",
      emailSubjectEn: "E5 cargo contact",
      emailIssueEn: "Thank you for your inquiry about sending cargo from Egypt.",
      emailResolutionEn: "Please contact our cargo line at 002-0114 708 8814 for assistance with your shipment.",
      emailSubjectAr: "جهة تواصل الشحن على E5",
      emailIssueAr: "شكراً لاستفساركم عن إرسال شحنة من مصر.",
      emailResolutionAr: "يرجى التواصل مع خط الشحن لدينا على الرقم 002-0114 708 8814 للمساعدة بخصوص شحنتكم.",
    },
    {
      chatEn: "Yes, that's correct — E5 Travel Agency Support has two valid lines: 002-03 419 7635 and 002-011 299 152 99, both are fine to use.",
      chatAr: "نعم، هذا صحيح - يوجد لدعم وكالات السفريات على E5 رقمان صالحان: 002-03 419 7635 و002-011 299 152 99، ويمكن استخدام أي منهما.",
      emailSubjectEn: "Confirming your E5 support line",
      emailIssueEn: "Thank you for checking whether this is a valid E5 travel agency support number.",
      emailResolutionEn: "Yes — E5 Travel Agency Support has two valid lines: 002-03 419 7635 and 002-011 299 152 99. Either can be used.",
      emailSubjectAr: "تأكيد خط الدعم الخاص بكم على E5",
      emailIssueAr: "شكراً لتحققكم من صحة رقم دعم وكالات السفريات على E5.",
      emailResolutionAr: "نعم - يوجد لدعم وكالات السفريات على E5 رقمان صالحان: 002-03 419 7635 و002-011 299 152 99. يمكن استخدام أي منهما.",
    },
  ],
};
