import type { ArticleTemplateSet } from "./types";

export const G9_3L_TEMPLATES: Record<string, ArticleTemplateSet> = {
  "g9-bundle-fares-g9": [
    {
      chatEn: "On Basic fare, seat selection is only available at a charge — free seating starts with the Value bundle from row 8, and Ultimate gives you any seat from row 2. Want me to compare the fees for you?",
      chatAr: "في باقة Basic، يتوفر اختيار المقعد فقط مقابل رسوم - يبدأ الاختيار المجاني مع باقة Value من الصف 8، بينما تمنحكم باقة Ultimate أي مقعد من الصف 2. هل ترغبون بمقارنة الرسوم؟",
      emailSubjectEn: "Seat selection on your G9 Basic fare",
      emailIssueEn: "Thank you for asking about free seat selection on your Basic fare booking.",
      emailResolutionEn: "Seat selection on Basic fare is only available at a charge. Free seat selection starts with the Value bundle (row 8 onward) and extends to any seat from row 2 with Ultimate. Let us know if you'd like to upgrade your bundle.",
      emailSubjectAr: "اختيار المقعد على باقة Basic",
      emailIssueAr: "شكراً لاستفساركم عن اختيار المقعد مجانًا ضمن حجز باقة Basic.",
      emailResolutionAr: "يتوفر اختيار المقعد في باقة Basic مقابل رسوم فقط. يبدأ الاختيار المجاني للمقعد مع باقة Value (من الصف 8 فما بعد) ويمتد إلى أي مقعد من الصف 2 مع باقة Ultimate. يرجى إخبارنا إذا رغبتم بترقية باقتكم.",
    },
    {
      chatEn: "Happy to break it down — Ultimate includes checked baggage, any seat from row 2, a hot meal and water, 2 free modifications, and priority check-in is included. Would you like me to apply it to your booking?",
      chatAr: "يسعدني توضيح ذلك - تشمل باقة Ultimate الأمتعة المسجّلة، وأي مقعد من الصف 2، ووجبة ساخنة مع الماء، وتعديلين مجانيين، بالإضافة إلى تسجيل وصول ذي أولوية. هل ترغبون أن أطبّقها على حجزكم؟",
      emailSubjectEn: "What's included in the Ultimate bundle",
      emailIssueEn: "Thank you for asking what's included in our Ultimate bundle.",
      emailResolutionEn: "The Ultimate bundle includes checked baggage, any seat from row 2 onward, a hot meal and water, 2 free modifications, and included priority check-in. Let us know if you'd like this applied to your booking.",
      emailSubjectAr: "ما تتضمنه باقة Ultimate",
      emailIssueAr: "شكراً لاستفساركم عمّا تتضمنه باقة Ultimate.",
      emailResolutionAr: "تشمل باقة Ultimate الأمتعة المسجّلة، وأي مقعد من الصف 2 فما بعد، ووجبة ساخنة مع الماء، وتعديلين مجانيين، بالإضافة إلى تسجيل وصول ذي أولوية. يرجى إخبارنا إذا رغبتم بتطبيقها على حجزكم.",
    },
    {
      chatEn: "Good question — Basic charges baggage, seat and meal separately to keep the fare low, while Value bundles in checked baggage, free seating from row 8, and a sandwich + water. Which matters more to you, price or convenience?",
      chatAr: "سؤال جيد - تُحتسب رسوم الأمتعة والمقعد والوجبة بشكل منفصل في باقة Basic للحفاظ على سعر منخفض، بينما تشمل باقة Value الأمتعة المسجّلة، والمقعد المجاني من الصف 8، وساندويتش مع ماء. أيهما أهم لكم، السعر أم الراحة؟",
      emailSubjectEn: "Basic vs. Value bundle comparison",
      emailIssueEn: "Thank you for asking about the difference between our Basic and Value bundles.",
      emailResolutionEn: "Basic keeps the fare low but charges for baggage, seat and meal separately. Value includes a set checked baggage allowance, free seating from row 8, and a sandwich + water. Let us know which benefits matter most and we'll recommend the best fit.",
      emailSubjectAr: "مقارنة بين باقتَي Basic وValue",
      emailIssueAr: "شكراً لاستفساركم عن الفرق بين باقتَي Basic وValue.",
      emailResolutionAr: "تحافظ باقة Basic على سعر منخفض لكنها تُحصّل رسوم الأمتعة والمقعد والوجبة بشكل منفصل. تشمل باقة Value أمتعة مسجّلة محددة، ومقعدًا مجانيًا من الصف 8، وساندويتش مع ماء. يرجى إخبارنا بأولوياتكم وسنوصي بالأنسب لكم.",
    },
  ],

  "g9-excess-baggage-rates-g9": [
    {
      chatEn: "Excess baggage on G9 is billed per kilo based on your destination and whether it's point-to-point or connecting — let me check the exact rate for your route now.",
      chatAr: "تُحتسب رسوم الوزن الزائد على رحلات G9 لكل كيلوغرام حسب وجهتكم وما إذا كانت رحلة مباشرة أو عبر محطة وصل - دعوني أتحقق من الرسوم الدقيقة لمسارك الآن.",
      emailSubjectEn: "Your Air Arabia excess baggage query",
      emailIssueEn: "Thank you for reaching out about the excess baggage rate for your G9 flight.",
      emailResolutionEn: "Excess baggage on G9 is charged per kilogram based on your destination and whether you're travelling point-to-point or connecting (rates range roughly from AED 45 to AED 105+ per kg by region), with airport handling fees applying on top. You're welcome to add the extra weight in advance or pay the excess at the airport.",
      emailSubjectAr: "استفساركم بخصوص الوزن الزائد",
      emailIssueAr: "شكراً لتواصلكم بخصوص رسوم الوزن الزائد لرحلتكم على G9.",
      emailResolutionAr: "تُحتسب رسوم الوزن الزائد على رحلات G9 لكل كيلوغرام حسب الوجهة وما إذا كانت الرحلة مباشرة أو عبر محطة وصل (تتراوح الرسوم تقريبًا بين 45 و105+ درهمًا إماراتيًا لكل كيلوغرام حسب المنطقة)، مع تطبيق رسوم مناولة المطار إضافةً لذلك. يمكنكم إضافة الوزن الإضافي مسبقًا أو دفع الوزن الزائد في المطار.",
    },
    {
      chatEn: "For a connection through Sharjah onward to a GCC country, that specific combination is marked N/A — but the connecting-to-others rate of AED 55/kg would apply. Could you confirm your exact routing so I quote the right one?",
      chatAr: "بالنسبة لرحلة عبر الشارقة إلى إحدى دول الخليج، هذا المسار تحديدًا غير متاح (N/A) - لكن ستُطبَّق رسوم الاتصال بوجهات أخرى البالغة 55 درهمًا لكل كيلوغرام. هل يمكنكم تأكيد مسار رحلتكم بالتحديد حتى أزودكم بالرسوم الصحيحة؟",
      emailSubjectEn: "Connecting flight excess baggage rate",
      emailIssueEn: "Thank you for asking about the excess baggage rate for your connecting flight through Sharjah.",
      emailResolutionEn: "GCC-to-GCC connections are marked N/A in our table; the connecting-to-others rate of AED 55 per kg would apply instead. Please confirm your exact routing so we can quote the precise rate.",
      emailSubjectAr: "رسوم الوزن الزائد للرحلة عبر محطة وصل",
      emailIssueAr: "شكراً لاستفساركم عن رسوم الوزن الزائد لرحلتكم عبر محطة وصل في الشارقة.",
      emailResolutionAr: "الرحلات المتصلة بين دول الخليج غير متاحة (N/A) في جدولنا؛ وستُطبَّق بدلاً من ذلك رسوم الاتصال بوجهات أخرى البالغة 55 درهمًا لكل كيلوغرام. يرجى تأكيد مسار رحلتكم بالتحديد حتى نزودكم بالرسوم الدقيقة.",
    },
    {
      chatEn: "I'm sorry, but carton boxes aren't accepted at all on G9 flights to Bangladesh, regardless of willingness to pay excess fees — I'd recommend repacking into a standard suitcase instead.",
      chatAr: "نأسف، لا تُقبل صناديق الكرتون إطلاقًا على رحلات G9 إلى بنغلاديش، بغض النظر عن الاستعداد لدفع رسوم إضافية - أنصح بإعادة التعبئة في حقيبة سفر عادية بدلاً من ذلك.",
      emailSubjectEn: "Carton boxes not accepted on Bangladesh flights",
      emailIssueEn: "Thank you for checking whether a carton box can be checked in on your flight to Bangladesh.",
      emailResolutionEn: "Carton boxes are not accepted on G9 flights to Bangladesh under any circumstances, regardless of excess baggage payment. We recommend repacking the contents into a standard suitcase before check-in.",
      emailSubjectAr: "عدم قبول صناديق الكرتون على رحلات بنغلاديش",
      emailIssueAr: "شكراً لاستفساركم عن إمكانية تسجيل صندوق كرتون على رحلتكم إلى بنغلاديش.",
      emailResolutionAr: "لا تُقبل صناديق الكرتون على رحلات G9 إلى بنغلاديش تحت أي ظرف، بغض النظر عن دفع رسوم الوزن الزائد. نوصي بإعادة تعبئة المحتويات في حقيبة سفر عادية قبل تسجيل الوصول.",
    },
  ],

  "g9-tv-handling-g9": [
    {
      chatEn: "I'm afraid a 65-inch TV can't be accepted — our maximum accepted size is 60 inches. Is there a smaller unit you could bring instead?",
      chatAr: "نأسف، لا يمكن قبول تلفاز بحجم 65 بوصة - الحد الأقصى المسموح به هو 60 بوصة. هل يمكنكم إحضار جهاز أصغر بدلاً من ذلك؟",
      emailSubjectEn: "TV size exceeds our accepted limit",
      emailIssueEn: "Thank you for checking in about bringing your 65-inch TV as checked baggage.",
      emailResolutionEn: "Unfortunately, TVs over 60 inches cannot be accepted on G9 flights. We'd recommend arranging alternative shipping for this item, or checking a smaller TV within the accepted size.",
      emailSubjectAr: "حجم التلفاز يتجاوز الحد المسموح",
      emailIssueAr: "شكراً لتواصلكم بخصوص إحضار تلفازكم بحجم 65 بوصة كأمتعة مسجّلة.",
      emailResolutionAr: "للأسف، لا يمكن قبول أجهزة التلفاز التي يتجاوز حجمها 60 بوصة على رحلات G9. نوصي بترتيب شحن بديل لهذا الجهاز، أو إحضار تلفاز أصغر ضمن الحجم المسموح.",
    },
    {
      chatEn: "Good news — TVs under 40 inches travel completely free, counted as one piece of your normal baggage allowance.",
      chatAr: "خبر سار - تُنقل أجهزة التلفاز التي يقل حجمها عن 40 بوصة مجانًا بالكامل، وتُحتسب كقطعة واحدة ضمن الأمتعة المسموح بها.",
      emailSubjectEn: "TV under 40 inches — no charge",
      emailIssueEn: "Thank you for asking whether your 35-inch TV incurs any fee.",
      emailResolutionEn: "TVs under 40 inches travel with no additional charge, counted as one piece within your normal baggage allowance. No further action is needed on your end.",
      emailSubjectAr: "تلفاز أقل من 40 بوصة - بدون رسوم",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كان تلفازكم بحجم 35 بوصة يستوجب أي رسوم.",
      emailResolutionAr: "تُنقل أجهزة التلفاز التي يقل حجمها عن 40 بوصة دون أي رسوم إضافية، وتُحتسب كقطعة واحدة ضمن الأمتعة المسموح بها. لا حاجة لأي إجراء إضافي من جانبكم.",
    },
    {
      chatEn: "You're welcome to bring all 3 TVs — there's no limit on the number per passenger. Each 45-inch unit will be AED 150 plus the airport handling fee, and counts as one piece.",
      chatAr: "يمكنكم إحضار الأجهزة الثلاثة جميعها - لا يوجد حد أقصى لعدد الأجهزة لكل مسافر. ستكون رسوم كل جهاز بحجم 45 بوصة 150 درهمًا بالإضافة إلى رسوم مناولة المطار، ويُحتسب كل جهاز كقطعة واحدة.",
      emailSubjectEn: "Bringing multiple TVs",
      emailIssueEn: "Thank you for checking whether you can bring 3 TVs on your flight.",
      emailResolutionEn: "There is no limit on the number of TVs per passenger. Each 45-inch TV will be charged AED 150 plus the airport handling fee and will count as one piece of baggage.",
      emailSubjectAr: "إحضار أكثر من تلفاز واحد",
      emailIssueAr: "شكراً لاستفساركم عن إمكانية إحضار 3 أجهزة تلفاز على رحلتكم.",
      emailResolutionAr: "لا يوجد حد أقصى لعدد أجهزة التلفاز لكل مسافر. ستُحتسب رسوم كل جهاز بحجم 45 بوصة بمبلغ 150 درهمًا بالإضافة إلى رسوم مناولة المطار، ويُحتسب كل جهاز كقطعة واحدة من الأمتعة.",
    },
  ],

  "g9-airport-services-sharjah-shj-airport-only": [
    {
      chatEn: "I'm sorry, but these premium services are exclusive to Sharjah Airport — since you're departing from Dubai, I'd recommend checking with Dubai Airport's own service provider instead.",
      chatAr: "نأسف، هذه الخدمات المميزة حصرية لمطار الشارقة - وبما أنكم تغادرون من دبي، أنصح بالتواصل مع مزوّد خدمات مطار دبي بدلاً من ذلك.",
      emailSubjectEn: "Sharjah services not available for Dubai departures",
      emailIssueEn: "Thank you for your interest in booking our Meet & Assist service.",
      emailResolutionEn: "These airport services are exclusive to passengers travelling to/from Sharjah Airport. As your departure is from Dubai, we'd recommend checking with Dubai Airport's own service provider for a similar service.",
      emailSubjectAr: "خدمات الشارقة غير متاحة للمغادرين من دبي",
      emailIssueAr: "شكراً لاهتمامكم بحجز خدمة الاستقبال والمساعدة لدينا.",
      emailResolutionAr: "هذه الخدمات المطارية حصرية للمسافرين من وإلى مطار الشارقة. وبما أن مغادرتكم من دبي، نوصي بالتواصل مع مزوّد خدمات مطار دبي للحصول على خدمة مماثلة.",
    },
    {
      chatEn: "Yes, absolutely — the Sharjah Business Lounge includes a shower room with toiletries and towels, available with your lounge access booking. Shall I book that for your early flight?",
      chatAr: "بالتأكيد نعم - تشمل صالة أعمال الشارقة غرفة استحمام مع مستلزمات ومناشف، وهي متاحة ضمن حجز صالة الأعمال. هل ترغبون أن أحجزها لرحلتكم الصباحية المبكرة؟",
      emailSubjectEn: "Shower facilities at the Sharjah Business Lounge",
      emailIssueEn: "Thank you for asking whether you can shower before boarding your early morning flight.",
      emailResolutionEn: "Yes — the Sharjah Business Lounge includes a shower room with toiletries and towels for customer use, available with a lounge access booking starting from AED 145 depending on the number of bags. Let us know if you'd like this booked.",
      emailSubjectAr: "مرافق الاستحمام في صالة أعمال الشارقة",
      emailIssueAr: "شكراً لاستفساركم عن إمكانية الاستحمام قبل صعود رحلتكم الصباحية المبكرة.",
      emailResolutionAr: "نعم - تشمل صالة أعمال الشارقة غرفة استحمام مزوّدة بمستلزمات ومناشف للاستخدام، وهي متاحة ضمن حجز صالة الأعمال بسعر يبدأ من 145 درهمًا حسب عدد الحقائب. يرجى إخبارنا إذا رغبتم بحجزها.",
    },
    {
      chatEn: "The Standard Sedan covers up to 4 passengers with 4 medium bags — you can book it via +971 54 3082573 by call or WhatsApp, or email booking@sayararental.com, up to 24 hours before departure.",
      chatAr: "تستوعب السيارة السيدان القياسية حتى 4 مسافرين مع 4 حقائب متوسطة الحجم - يمكنكم الحجز عبر +971 54 3082573 اتصالاً أو واتساب، أو عبر البريد الإلكتروني booking@sayararental.com، حتى 24 ساعة قبل موعد المغادرة.",
      emailSubjectEn: "Airport transfer booking to Sharjah Airport",
      emailIssueEn: "Thank you for your request to book an airport transfer for your family of 4 to Sharjah Airport.",
      emailResolutionEn: "Our Standard Sedan accommodates up to 4 passengers with 4 medium-sized bags. Please book directly at +971 54 3082573 (call or WhatsApp, 24/7) or via booking@sayararental.com, up to 24 hours prior to departure.",
      emailSubjectAr: "حجز خدمة النقل إلى مطار الشارقة",
      emailIssueAr: "شكراً لطلبكم حجز خدمة نقل لعائلتكم المكونة من 4 أفراد إلى مطار الشارقة.",
      emailResolutionAr: "تستوعب سيارتنا السيدان القياسية حتى 4 مسافرين مع 4 حقائب متوسطة الحجم. يرجى الحجز مباشرة عبر +971 54 3082573 (اتصال أو واتساب، على مدار الساعة) أو عبر البريد الإلكتروني booking@sayararental.com، حتى 24 ساعة قبل موعد المغادرة.",
    },
  ],

  "g9-city-check-in-g9-3l-only": [
    {
      chatEn: "That works — same-day flights just need to check in before 4pm, since the last bus to the airport leaves the office at 5pm. Let's get you booked in now.",
      chatAr: "هذا ممكن - يجب فقط تسجيل الوصول قبل الساعة 4 عصرًا لرحلات اليوم نفسه، حيث تغادر آخر حافلة إلى المطار من المكتب الساعة 5 مساءً. دعونا نكمل تسجيلكم الآن.",
      emailSubjectEn: "Same-day City Check-in cut-off",
      emailIssueEn: "Thank you for reaching out about City Check-in for your same-day flight.",
      emailResolutionEn: "Same-day flights must check in before 4pm, as the last bus to the airport leaves the office at 5pm. Please plan to arrive at the City Check-in center before this cut-off.",
      emailSubjectAr: "مهلة تسجيل الوصول في مركز المدينة لرحلات اليوم نفسه",
      emailIssueAr: "شكراً لتواصلكم بخصوص تسجيل الوصول في مركز المدينة لرحلتكم في اليوم نفسه.",
      emailResolutionAr: "يجب تسجيل الوصول لرحلات اليوم نفسه قبل الساعة 4 عصرًا، حيث تغادر آخر حافلة إلى المطار من المكتب الساعة 5 مساءً. يرجى التخطيط للوصول إلى مركز تسجيل الوصول في المدينة قبل هذه المهلة.",
    },
    {
      chatEn: "I'm afraid at least one passenger from the actual booking needs to attend in person, along with the original passports of everyone traveling — a non-traveling friend can't complete this alone, sorry for the inconvenience.",
      chatAr: "نأسف، يجب أن يحضر شخصيًا مسافر واحد على الأقل من ضمن الحجز الفعلي، مع جوازات السفر الأصلية لجميع المسافرين - لا يمكن لصديق غير مسافر إتمام ذلك بمفرده، ونعتذر عن الإزعاج.",
      emailSubjectEn: "In-person attendance required for City Check-in",
      emailIssueEn: "Thank you for asking whether someone outside the booking can complete City Check-in on your behalf.",
      emailResolutionEn: "At least one passenger from the actual PNR must attend the City Check-in center in person, along with the original passports of all passengers on the booking. A non-traveling representative cannot complete this alone.",
      emailSubjectAr: "الحضور الشخصي مطلوب لتسجيل الوصول في مركز المدينة",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كان بإمكان شخص خارج الحجز إتمام تسجيل الوصول في مركز المدينة نيابة عنكم.",
      emailResolutionAr: "يجب أن يحضر شخصيًا مسافر واحد على الأقل من ضمن الحجز، مصطحبًا جوازات السفر الأصلية لجميع المسافرين على الحجز. لا يمكن لممثل غير مسافر إتمام ذلك بمفرده.",
    },
    {
      chatEn: "Good news — Ras Al Khaimah itself is one of our G9 city check-in locations, so you can use it directly without travelling elsewhere.",
      chatAr: "خبر سار - رأس الخيمة نفسها أحد مواقع تسجيل الوصول في المدينة لرحلات G9، لذا يمكنكم استخدامها مباشرة دون الحاجة للسفر إلى مكان آخر.",
      emailSubjectEn: "Your nearest City Check-in location",
      emailIssueEn: "Thank you for asking about the nearest G9 City Check-in location to you.",
      emailResolutionEn: "Ras Al Khaimah is itself one of our G9 City Check-in locations, alongside Sharjah, Ajman and Dubai — you're welcome to use it directly.",
      emailSubjectAr: "أقرب موقع لتسجيل الوصول في المدينة",
      emailIssueAr: "شكراً لاستفساركم عن أقرب موقع لتسجيل الوصول في المدينة لرحلات G9.",
      emailResolutionAr: "رأس الخيمة نفسها أحد مواقع تسجيل الوصول في المدينة لرحلات G9، إلى جانب الشارقة وعجمان ودبي - يمكنكم استخدامها مباشرة.",
    },
  ],

  "g9-name-change-g9": [
    {
      chatEn: "I'm sorry, but name changes need at least 24 hours' notice before the first sector's departure, so 10 hours out isn't possible through this channel — let me check with a supervisor to see if there's any airport-level exception.",
      chatAr: "نأسف، تتطلب تغييرات الاسم إشعارًا مسبقًا لا يقل عن 24 ساعة قبل مغادرة القطاع الأول، وبالتالي فإن طلبكم قبل 10 ساعات غير ممكن عبر هذه القناة - دعوني أتحقق مع المشرف لمعرفة إمكانية وجود استثناء على مستوى المطار.",
      emailSubjectEn: "Name change request too close to departure",
      emailIssueEn: "Thank you for your name change request ahead of your flight.",
      emailResolutionEn: "Name changes must be requested at least 24 hours prior to the first sector's departure. As your flight departs sooner than that, we're checking with our team to see if any airport-level exception can apply.",
      emailSubjectAr: "طلب تغيير الاسم قريب جدًا من موعد المغادرة",
      emailIssueAr: "شكراً لطلبكم تغيير الاسم قبل موعد رحلتكم.",
      emailResolutionAr: "يجب تقديم طلبات تغيير الاسم قبل 24 ساعة على الأقل من مغادرة القطاع الأول. وبما أن موعد رحلتكم أقرب من ذلك، نقوم بالتحقق مع فريقنا لمعرفة إمكانية وجود استثناء على مستوى المطار.",
    },
    {
      chatEn: "Since a sibling counts as immediate family, this is permitted — I'll raise a Sprinklr case now and just need proof of the relationship (documents showing shared parents) to process it.",
      chatAr: "بما أن الشقيق يُعد من أفراد العائلة المباشرين، فهذا الطلب مسموح - سأقوم بفتح حالة على Sprinklr الآن، وأحتاج فقط إثبات صلة القرابة (مستندات تثبت الأبوين المشتركين) لإتمام المعالجة.",
      emailSubjectEn: "Name change using family credit — proof required",
      emailIssueEn: "Thank you for your request to apply your sibling's credit voucher to your booking with a name change.",
      emailResolutionEn: "A sibling qualifies as immediate family, so this is permitted. We've raised a Sprinklr case for this request — please reply with proof of relationship (e.g. documents showing shared parents) so we can proceed.",
      emailSubjectAr: "تغيير الاسم باستخدام رصيد أحد أفراد العائلة",
      emailIssueAr: "شكراً لطلبكم استخدام رصيد شقيقكم على حجزكم مع تغيير الاسم.",
      emailResolutionAr: "يُعد الشقيق من أفراد العائلة المباشرين، وبالتالي هذا الطلب مسموح. لقد فتحنا حالة على Sprinklr لهذا الطلب - يرجى الرد بإثبات صلة القرابة (مستندات تثبت الأبوين المشتركين) لنتمكن من المتابعة.",
    },
    {
      chatEn: "Not a problem at all — a spelling correction like that is completely free. I'll send this directly to a supervisor to process rather than raising a paid case.",
      chatAr: "لا مشكلة إطلاقًا - تصحيح الإملاء من هذا النوع مجاني بالكامل. سأرسل هذا مباشرة إلى المشرف لمعالجته بدلاً من فتح حالة مدفوعة.",
      emailSubjectEn: "Free spelling correction request",
      emailIssueEn: "Thank you for flagging the spelling discrepancy between your booking and passport.",
      emailResolutionEn: "This qualifies as a free spelling correction. We've forwarded your request directly to a supervisor for processing — no charge applies.",
      emailSubjectAr: "طلب تصحيح إملائي مجاني",
      emailIssueAr: "شكراً لإبلاغنا بالاختلاف الإملائي بين حجزكم وجواز سفركم.",
      emailResolutionAr: "يندرج هذا ضمن التصحيح الإملائي المجاني. لقد أحلنا طلبكم مباشرة إلى المشرف للمعالجة - دون أي رسوم.",
    },
  ],

  "g9-ok-to-board-otb-g9": [
    {
      chatEn: "Yes, this is mandatory for your route — please visit any Air Arabia office at least 24 hours before departure with your visa copy, passport and PNR. There's a charge of AED 15–20 per passenger.",
      chatAr: "نعم، هذا إجراء إلزامي لمسار رحلتكم - يرجى زيارة أي مكتب للعربية للطيران قبل 24 ساعة على الأقل من المغادرة، مصطحبين نسخة التأشيرة وجواز السفر ورقم الحجز. تُطبَّق رسوم تتراوح بين 15 و20 درهمًا لكل مسافر.",
      emailSubjectEn: "Ok to Board (OTB) is required for your flight",
      emailIssueEn: "Thank you for reaching out about your upcoming flight to the UAE.",
      emailResolutionEn: "As you're travelling to the UAE on a UAE visa from India, Pakistan or Bangladesh, an Ok to Board message must be updated. Please visit any Air Arabia office at least 24 hours before departure with your visa copy, passport, and PNR number (a charge of AED 15–20 per passenger applies).",
      emailSubjectAr: "رسالة الموافقة على الصعود مطلوبة لرحلتكم",
      emailIssueAr: "شكراً لتواصلكم بخصوص رحلتكم القادمة إلى الإمارات.",
      emailResolutionAr: "بما أنكم مسافرون إلى الإمارات بتأشيرة إماراتية من الهند أو باكستان أو بنغلاديش، يجب تحديث رسالة الموافقة على الصعود. يرجى زيارة أي مكتب للعربية للطيران قبل 24 ساعة على الأقل من المغادرة مصطحبين نسخة التأشيرة وجواز السفر ورقم الحجز (تُطبَّق رسوم تتراوح بين 15 و20 درهمًا لكل مسافر).",
    },
    {
      chatEn: "I understand the time pressure — please head to the office as soon as you possibly can. Staff will do their best to assist even though it's inside the normal 24-hour window, though I can't guarantee it.",
      chatAr: "أتفهم ضيق الوقت - يرجى التوجه إلى المكتب في أقرب وقت ممكن. سيبذل الموظفون قصارى جهدهم لمساعدتكم رغم أن الطلب ضمن مهلة الـ 24 ساعة المعتادة، لكن لا يمكنني ضمان ذلك.",
      emailSubjectEn: "Urgent Ok to Board update needed",
      emailIssueEn: "Thank you for reaching out urgently about updating your Ok to Board message.",
      emailResolutionEn: "As your departure is under 24 hours away, please visit an Air Arabia office as soon as possible. Our office staff will do their best to assist, although this cannot be guaranteed given the short notice.",
      emailSubjectAr: "تحديث عاجل لرسالة الموافقة على الصعود",
      emailIssueAr: "شكراً لتواصلكم العاجل بخصوص تحديث رسالة الموافقة على الصعود.",
      emailResolutionAr: "بما أن موعد مغادرتكم أقل من 24 ساعة، يرجى زيارة أحد مكاتب العربية للطيران في أقرب وقت ممكن. سيبذل موظفو المكتب قصارى جهدهم للمساعدة، رغم أن ذلك غير مضمون نظرًا لضيق الوقت.",
    },
    {
      chatEn: "Good news — Ok to Board only applies to passengers travelling from India, Pakistan or Bangladesh, so it doesn't apply to your Manila departure. If you're unsure about visa requirements, I'd suggest checking with the relevant embassy directly.",
      chatAr: "خبر سار - تنطبق رسالة الموافقة على الصعود فقط على المسافرين القادمين من الهند أو باكستان أو بنغلاديش، وبالتالي لا تنطبق على رحلتكم من مانيلا. إذا كان لديكم استفسار حول متطلبات التأشيرة، أنصح بالتواصل مباشرة مع السفارة المعنية.",
      emailSubjectEn: "Ok to Board does not apply to your route",
      emailIssueEn: "Thank you for asking whether Ok to Board applies to your flight from Manila.",
      emailResolutionEn: "Ok to Board is specific to passengers travelling from India, Pakistan or Bangladesh — the Philippines is not covered by this rule. If you have visa questions, please check directly with the relevant immigration authority, consulate or embassy.",
      emailSubjectAr: "الموافقة على الصعود لا تنطبق على مسار رحلتكم",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كانت رسالة الموافقة على الصعود تنطبق على رحلتكم من مانيلا.",
      emailResolutionAr: "تنطبق رسالة الموافقة على الصعود فقط على المسافرين القادمين من الهند أو باكستان أو بنغلاديش، ولا تشمل الفلبين. إذا كانت لديكم استفسارات حول التأشيرة، يرجى التواصل مباشرة مع سلطات الهجرة أو القنصلية أو السفارة المعنية.",
    },
  ],

  "g9-pets-animals-falcons-g9": [
    {
      chatEn: "I'm sorry, but pets and animals aren't allowed on board any of our flights, including cats — the only exception on G9 is falcons, under a specific procedure. Is there anything else I can help arrange for your trip?",
      chatAr: "نأسف، لا يُسمح باصطحاب الحيوانات الأليفة على متن أي من رحلاتنا، بما في ذلك القطط - الاستثناء الوحيد على رحلات G9 هو الصقور، وفق إجراء محدد. هل هناك شيء آخر يمكنني ترتيبه لرحلتكم؟",
      emailSubjectEn: "Pets not permitted on board",
      emailIssueEn: "Thank you for asking about bringing your cat in the cabin on your G9 flight.",
      emailResolutionEn: "Pets and animals are not allowed on board any of our flights. The only exception on G9 is falcons, which follow a specific 48-hour-advance booking procedure. Unfortunately your cat cannot be accommodated.",
      emailSubjectAr: "عدم السماح باصطحاب الحيوانات الأليفة على متن الطائرة",
      emailIssueAr: "شكراً لاستفساركم عن اصطحاب قطتكم داخل المقصورة على رحلة G9.",
      emailResolutionAr: "لا يُسمح باصطحاب الحيوانات الأليفة على متن أي من رحلاتنا. الاستثناء الوحيد على رحلات G9 هو الصقور، وفق إجراء حجز محدد يتطلب إشعارًا مسبقًا بـ 48 ساعة. للأسف، لا يمكن استيعاب قطتكم.",
    },
    {
      chatEn: "I'm afraid that's too short notice — falcon bookings need at least 48 hours before departure. Let me refer this to a supervisor so we can look at your options.",
      chatAr: "نأسف، هذا الوقت غير كافٍ - تتطلب حجوزات الصقور إشعارًا مسبقًا لا يقل عن 48 ساعة قبل المغادرة. دعوني أحيل هذا الطلب إلى المشرف لبحث الخيارات المتاحة لكم.",
      emailSubjectEn: "Falcon booking notice period",
      emailIssueEn: "Thank you for your request to book 2 falcons on a flight departing in 24 hours.",
      emailResolutionEn: "Falcon bookings must be completed at least 48 hours prior to departure, so this request falls short of that window. We've referred your inquiry to a supervisor to review the available options.",
      emailSubjectAr: "مهلة حجز الصقور",
      emailIssueAr: "شكراً لطلبكم حجز صقرَين على رحلة تُغادر خلال 24 ساعة.",
      emailResolutionAr: "يجب إتمام حجوزات الصقور قبل 48 ساعة على الأقل من موعد المغادرة، وطلبكم لا يستوفي هذه المهلة. لقد أحلنا استفساركم إلى المشرف لمراجعة الخيارات المتاحة.",
    },
    {
      chatEn: "Good question — no additional baggage allowance is given for seats blocked for falcons, since that's separate from your own baggage entitlement.",
      chatAr: "سؤال جيد - لا يُمنح أي وزن أمتعة إضافي مقابل المقاعد المحجوزة للصقور، حيث يُعد ذلك منفصلاً عن مخصص أمتعتكم الشخصية.",
      emailSubjectEn: "Baggage allowance and falcon seats",
      emailIssueEn: "Thank you for asking about extra baggage allowance for your falcon's seat.",
      emailResolutionEn: "No additional baggage allowance is given for seats blocked for falcons — this is separate from your own personal baggage entitlement, which remains unchanged.",
      emailSubjectAr: "الأمتعة ومقاعد الصقور",
      emailIssueAr: "شكراً لاستفساركم عن مخصص أمتعة إضافي لمقعد صقركم.",
      emailResolutionAr: "لا يُمنح أي وزن أمتعة إضافي مقابل المقاعد المحجوزة للصقور - ويبقى مخصص أمتعتكم الشخصية دون تغيير.",
    },
  ],

  "g9-cargo-trade-support-g9": [
    {
      chatEn: "No problem, we're available around the clock for that — please call the SAS Export Counter at 06-514-1174, it's staffed 24/7.",
      chatAr: "لا مشكلة، نحن متاحون على مدار الساعة لذلك - يرجى الاتصال بكاونتر الشحن للتصدير SAS على الرقم 06-514-1174، وهو مأهول على مدار الساعة.",
      emailSubjectEn: "Export cargo status inquiry",
      emailIssueEn: "Thank you for your inquiry about your export shipment status from Sharjah.",
      emailResolutionEn: "The SAS Export Counter operates 24/7 and can be reached at 06-514-1174 for export status checks at any time, including after hours.",
      emailSubjectAr: "استفسار عن حالة شحنة التصدير",
      emailIssueAr: "شكراً لاستفساركم عن حالة شحنة التصدير الخاصة بكم من الشارقة.",
      emailResolutionAr: "يعمل كاونتر الشحن للتصدير SAS على مدار الساعة ويمكن التواصل معه على الرقم 06-514-1174 للاستفسار عن حالة الشحنة في أي وقت، بما في ذلك خارج أوقات الدوام.",
    },
    {
      chatEn: "For receiving cargo into Sharjah, please contact the SAS Import Counter — they're also available 24/7 on 06-514-1188 or 06-514-1189.",
      chatAr: "لاستلام شحنة إلى الشارقة، يرجى التواصل مع كاونتر الاستيراد SAS - وهو متاح أيضًا على مدار الساعة على الرقمين 06-514-1188 أو 06-514-1189.",
      emailSubjectEn: "Import cargo inquiry",
      emailIssueEn: "Thank you for your inquiry about receiving a shipment into Sharjah.",
      emailResolutionEn: "Please contact the SAS Import Counter, available 24/7 at 06-514-1188 or 06-514-1189, for assistance with receiving your shipment.",
      emailSubjectAr: "استفسار عن شحنة استيراد",
      emailIssueAr: "شكراً لاستفساركم عن استلام شحنة إلى الشارقة.",
      emailResolutionAr: "يرجى التواصل مع كاونتر الاستيراد SAS، المتاح على مدار الساعة على الرقمين 06-514-1188 أو 06-514-1189، للمساعدة في استلام شحنتكم.",
    },
    {
      chatEn: "Happy to point you in the right direction — please reach out to your assigned Sales Team representative, or for general UAE sales support contact trade@airarabia.com or 600 50 8002 (9am–10pm).",
      chatAr: "يسعدني توجيهكم للجهة الصحيحة - يرجى التواصل مع ممثل فريق المبيعات المخصص لكم، أو للدعم العام للمبيعات في الإمارات يمكنكم التواصل عبر trade@airarabia.com أو الرقم 600 50 8002 (من 9 صباحًا حتى 10 مساءً).",
      emailSubjectEn: "Trade support contact details",
      emailIssueEn: "Thank you for reaching out to confirm who handles your travel agency account inquiries.",
      emailResolutionEn: "Please reach out to your assigned Sales Team representative directly. For general UAE sales support, you can also contact trade@airarabia.com or call 600 50 8002, available 9am–10pm.",
      emailSubjectAr: "بيانات التواصل مع فريق دعم الوكالات",
      emailIssueAr: "شكراً لتواصلكم للتأكد من الجهة المسؤولة عن استفسارات حساب وكالة السفريات الخاصة بكم.",
      emailResolutionAr: "يرجى التواصل مباشرة مع ممثل فريق المبيعات المخصص لكم. للدعم العام للمبيعات في الإمارات، يمكنكم أيضًا التواصل عبر trade@airarabia.com أو الاتصال على الرقم 600 50 8002 المتاح من 9 صباحًا حتى 10 مساءً.",
    },
  ],

  "g9-air-arabia-holidays-g9": [
    {
      chatEn: "We can't book Holidays packages directly here, but I'll raise a request now with your passenger count, destination, dates and contact info — our Holidays team will reach out to complete the booking with you.",
      chatAr: "لا يمكننا حجز باقات الرحلات السياحية مباشرة هنا، لكنني سأقدّم طلبًا الآن يتضمن عدد المسافرين والوجهة والتواريخ وبيانات التواصل - سيتواصل معكم فريق الرحلات السياحية لإتمام الحجز.",
      emailSubjectEn: "Your Air Arabia Holidays request",
      emailIssueEn: "Thank you for your interest in an Air Arabia Holidays package (flight + hotel + transfers + tours).",
      emailResolutionEn: "We've raised your request with our Holidays team, who will contact you directly to complete the booking with the destination, dates and passenger details you've provided.",
      emailSubjectAr: "طلبكم لباقة Air Arabia Holidays",
      emailIssueAr: "شكراً لاهتمامكم بباقة Air Arabia Holidays (طيران + فندق + نقل + جولات).",
      emailResolutionAr: "لقد قدّمنا طلبكم إلى فريق الرحلات السياحية لدينا، والذي سيتواصل معكم مباشرة لإتمام الحجز بالوجهة والتواريخ وبيانات المسافرين التي قدّمتموها.",
    },
    {
      chatEn: "I understand you'd prefer to adjust the dates — unfortunately modification isn't permitted on Holiday packages. Cancellation is possible with at least 72 hours' notice, though it results in a credit voucher rather than a refund.",
      chatAr: "أتفهم رغبتكم في تعديل التواريخ - للأسف، التعديل غير مسموح به على باقات الرحلات السياحية. الإلغاء ممكن بإشعار مسبق لا يقل عن 72 ساعة، إلا أنه يؤدي إلى إصدار قسيمة رصيد بدلاً من الاسترداد.",
      emailSubjectEn: "Holiday package date change not available",
      emailIssueEn: "Thank you for your request to change the travel dates on your Holiday package.",
      emailResolutionEn: "Modification is not permitted on Holiday Package bookings. The only option is cancellation, which requires at least 72 hours' notice prior to departure and results in a credit voucher rather than a refund.",
      emailSubjectAr: "عدم توفر تعديل تواريخ باقة الرحلة السياحية",
      emailIssueAr: "شكراً لطلبكم تعديل تواريخ السفر على باقة الرحلة السياحية الخاصة بكم.",
      emailResolutionAr: "التعديل غير متاح على حجوزات باقات الرحلات السياحية. الخيار الوحيد هو الإلغاء، والذي يتطلب إشعارًا مسبقًا لا يقل عن 72 ساعة قبل موعد المغادرة، ويؤدي إلى إصدار قسيمة رصيد بدلاً من الاسترداد.",
    },
    {
      chatEn: "I'm afraid cash back isn't an option here — cancellation of a Holiday Package results only in a credit voucher, valid 1 year and usable for any passenger in the booking.",
      chatAr: "نأسف، الاسترداد النقدي غير متاح هنا - يؤدي إلغاء باقة الرحلة السياحية فقط إلى إصدار قسيمة رصيد سارية لمدة عام واحد ويمكن استخدامها لأي مسافر ضمن الحجز.",
      emailSubjectEn: "Holiday package cancellation — credit voucher only",
      emailIssueEn: "Thank you for asking about cash-back after cancelling your Holiday Package.",
      emailResolutionEn: "Cancellation of a Holiday Package results in a credit voucher only, valid for 1 year from the date of payment and usable for any passenger in the booking — a cash refund is not available.",
      emailSubjectAr: "إلغاء باقة الرحلة السياحية - قسيمة رصيد فقط",
      emailIssueAr: "شكراً لاستفساركم عن الاسترداد النقدي بعد إلغاء باقة الرحلة السياحية.",
      emailResolutionAr: "يؤدي إلغاء باقة الرحلة السياحية إلى إصدار قسيمة رصيد فقط، سارية لمدة عام واحد من تاريخ الدفع ويمكن استخدامها لأي مسافر ضمن الحجز - الاسترداد النقدي غير متاح.",
    },
  ],

  "g9-special-discounts-homat-al-watan-fazaa-waffer-esaad-g9": [
    {
      chatEn: "I'm sorry, but this discount is only valid on departures from Abu Dhabi, RAK or Sharjah — Dubai isn't eligible. You're welcome to visit an Air Arabia Sales Shop in the UAE to explore other options.",
      chatAr: "نأسف، هذا الخصم متاح فقط للمغادرة من أبوظبي أو رأس الخيمة أو الشارقة - دبي غير مؤهلة. يمكنكم زيارة أحد متاجر مبيعات العربية للطيران في الإمارات لاستكشاف خيارات أخرى.",
      emailSubjectEn: "Special discount eligibility",
      emailIssueEn: "Thank you for your interest in the 10% Fazaa discount on your booking.",
      emailResolutionEn: "This discount is valid only on destinations departing from Abu Dhabi, RAK or Sharjah. As your departure is from Dubai, it doesn't qualify — you're welcome to visit an Air Arabia Sales Shop in the UAE to check alternative options.",
      emailSubjectAr: "أهلية الخصم الخاص",
      emailIssueAr: "شكراً لاهتمامكم بخصم فزعة البالغ 10% على حجزكم.",
      emailResolutionAr: "يسري هذا الخصم فقط على الوجهات المغادرة من أبوظبي أو رأس الخيمة أو الشارقة. وبما أن مغادرتكم من دبي، فهو غير مؤهل - يمكنكم زيارة أحد متاجر مبيعات العربية للطيران في الإمارات للاطلاع على خيارات بديلة.",
    },
    {
      chatEn: "Good news — Esaad's family definition includes parents with no age restriction, so this is eligible. I'll raise a Sprinklr case now; please have the original ID and proof of relationship ready to send.",
      chatAr: "خبر سار - يشمل تعريف العائلة في بطاقة إسعاد الوالدين دون قيود عمرية، وبالتالي هذا الطلب مؤهل. سأفتح حالة على Sprinklr الآن؛ يرجى تجهيز الهوية الأصلية وإثبات صلة القرابة لإرسالها.",
      emailSubjectEn: "Esaad discount request for a parent",
      emailIssueEn: "Thank you for your request to redeem the Esaad discount for your parent's ticket.",
      emailResolutionEn: "Esaad's family definition includes parents with no age restriction, so this request is eligible. We've raised a Sprinklr case — please reply with the original ID and proof of relationship so our outbound team can proceed.",
      emailSubjectAr: "طلب خصم إسعاد لأحد الوالدين",
      emailIssueAr: "شكراً لطلبكم استخدام خصم إسعاد لتذكرة أحد والديكم.",
      emailResolutionAr: "يشمل تعريف العائلة في بطاقة إسعاد الوالدين دون قيود عمرية، وبالتالي هذا الطلب مؤهل. لقد فتحنا حالة على Sprinklr - يرجى الرد بالهوية الأصلية وإثبات صلة القرابة ليتمكن فريقنا من المتابعة.",
    },
    {
      chatEn: "I understand, but we can't create an on-hold booking for this — once your Sprinklr case is raised with the discount card and relationship proof, our outbound team will contact you directly to build the booking.",
      chatAr: "أتفهم ذلك، لكن لا يمكننا إنشاء حجز معلّق لهذا الطلب - بمجرد فتح حالة Sprinklr مع نسخة بطاقة الخصم وإثبات صلة القرابة، سيتواصل معكم فريقنا مباشرة لإتمام الحجز.",
      emailSubjectEn: "Discount booking process — no on-hold bookings",
      emailIssueEn: "Thank you for asking us to hold a booking while you gather your discount documents.",
      emailResolutionEn: "We're unable to create an on-hold booking for this. Once your Sprinklr case is raised with a copy of the discount card and proof of relationship, our outbound team will contact you directly to create the booking.",
      emailSubjectAr: "إجراءات حجز الخصم - عدم توفر الحجز المعلّق",
      emailIssueAr: "شكراً لطلبكم تعليق الحجز ريثما تجمعون مستندات الخصم.",
      emailResolutionAr: "لا يمكننا إنشاء حجز معلّق لهذا الطلب. بمجرد فتح حالة Sprinklr مع نسخة من بطاقة الخصم وإثبات صلة القرابة، سيتواصل معكم فريقنا مباشرة لإتمام الحجز.",
    },
  ],

  "3l-early-home-check-in-abu-dhabi-sharjah-airports": [
    {
      chatEn: "Yes, that works — early check-in at YAS Mall opens 24 hours prior to departure, so the day before is fine. It's AED 35 per adult, AED 25 per child, and AED 15 per infant.",
      chatAr: "نعم، هذا ممكن - يُفتح تسجيل الوصول المبكر في YAS Mall قبل 24 ساعة من المغادرة، لذا فإن اليوم السابق مناسب. الرسوم 35 درهمًا للبالغ، و25 درهمًا للطفل، و15 درهمًا للرضيع.",
      emailSubjectEn: "Early check-in at YAS Mall",
      emailIssueEn: "Thank you for asking about checking in luggage the day before your flight at YAS Mall.",
      emailResolutionEn: "Early check-in at YAS Mall opens 24 hours prior to departure, so checking in the day before is within the window. Fees are AED 35 per adult, AED 25 per child up to 12, and AED 15 per infant.",
      emailSubjectAr: "تسجيل الوصول المبكر في YAS Mall",
      emailIssueAr: "شكراً لاستفساركم عن تسجيل وصول الأمتعة قبل يوم من رحلتكم في YAS Mall.",
      emailResolutionAr: "يُفتح تسجيل الوصول المبكر في YAS Mall قبل 24 ساعة من موعد المغادرة، لذا فإن التسجيل قبل يوم يقع ضمن هذه المهلة. الرسوم 35 درهمًا للبالغ، و25 درهمًا للطفل حتى 12 عامًا، و15 درهمًا للرضيع.",
    },
    {
      chatEn: "I'd recommend Home Check-in via MORAFIQ for you — our agents come directly to your location in Abu Dhabi within a 24-hour to 5-hour window before your flight, to check you in and collect your baggage.",
      chatAr: "أنصح بخدمة تسجيل الوصول من المنزل عبر MORAFIQ لكم - يصل موظفونا مباشرة إلى موقعكم في أبوظبي خلال نافذة زمنية تتراوح بين 24 و5 ساعات قبل رحلتكم، لتسجيل وصولكم واستلام أمتعتكم.",
      emailSubjectEn: "Home Check-in via MORAFIQ",
      emailIssueEn: "Thank you for reaching out about avoiding the airport check-in queue due to mobility considerations.",
      emailResolutionEn: "We'd recommend Home Check-in via MORAFIQ. Our agents will come to your location in Abu Dhabi within a 24-hour to 5-hour window before your flight to verify your documents, check you in, and collect your baggage directly.",
      emailSubjectAr: "تسجيل الوصول من المنزل عبر MORAFIQ",
      emailIssueAr: "شكراً لتواصلكم بخصوص تجنب طابور تسجيل الوصول في المطار نظرًا لظروف الحركة.",
      emailResolutionAr: "ننصح بخدمة تسجيل الوصول من المنزل عبر MORAFIQ. سيصل موظفونا إلى موقعكم في أبوظبي خلال نافذة زمنية تتراوح بين 24 و5 ساعات قبل رحلتكم للتحقق من مستنداتكم وتسجيل وصولكم واستلام أمتعتكم مباشرة.",
    },
    {
      chatEn: "I'm sorry, but Sharjah Home Check-in needs to be booked at least 6 hours before departure, so 4 hours out is too late — I'd suggest the standard airport counter, or the free 24-hour early check-in option instead.",
      chatAr: "نأسف، يجب حجز تسجيل الوصول من المنزل في الشارقة قبل 6 ساعات على الأقل من المغادرة، وبالتالي فإن طلبكم قبل 4 ساعات متأخر جدًا - أقترح استخدام الكاونتر المعتاد في المطار، أو خيار تسجيل الوصول المبكر المجاني قبل 24 ساعة.",
      emailSubjectEn: "Home Check-in cut-off time in Sharjah",
      emailIssueEn: "Thank you for your request to book Sharjah Home Check-in 4 hours before departure.",
      emailResolutionEn: "Sharjah Home Check-in can only be booked up to 6 hours prior to departure, so this request falls outside that window. We'd recommend using the standard airport counter, or Sharjah's free 24-hour early check-in option instead.",
      emailSubjectAr: "مهلة تسجيل الوصول من المنزل في الشارقة",
      emailIssueAr: "شكراً لطلبكم حجز تسجيل الوصول من المنزل في الشارقة قبل 4 ساعات من المغادرة.",
      emailResolutionAr: "يمكن حجز تسجيل الوصول من المنزل في الشارقة فقط حتى 6 ساعات قبل المغادرة، وطلبكم يقع خارج هذه المهلة. ننصح باستخدام الكاونتر المعتاد في المطار، أو خيار تسجيل الوصول المبكر المجاني في الشارقة قبل 24 ساعة.",
    },
  ],
};
