import type { ArticleTemplateSet } from "./types";

export const GENERAL_TEMPLATES: Record<string, ArticleTemplateSet> = {
  "general-ticket-types-all-hubs": [
    {
      chatEn: "Great question! Ticket type is based on your child's age exactly on the day of travel — since they'll still be 11 then, they qualify for the Child fare even though they turn 12 the following week.",
      chatAr: "سؤال رائع! يُحدَّد نوع التذكرة بناءً على عمر طفلكم في تاريخ السفر بالتحديد - وبما أنه سيكون لا يزال 11 عامًا في ذلك التاريخ، فهو مؤهل لتذكرة الطفل حتى لو أتم 12 عامًا في الأسبوع التالي.",
      emailSubjectEn: "Ticket type confirmation for your child",
      emailIssueEn: "Thank you for reaching out regarding the correct ticket type for your child's upcoming flight.",
      emailResolutionEn: "Age for ticketing purposes is fixed as of the travel date, not the booking date. Since your child will still be 11 years old on the day of travel, they qualify for the Child fare, even though their 12th birthday falls shortly afterward.",
      emailSubjectAr: "تأكيد نوع تذكرة طفلكم",
      emailIssueAr: "شكراً لتواصلكم معنا بخصوص نوع التذكرة الصحيح لرحلة طفلكم القادمة.",
      emailResolutionAr: "يُحدَّد عمر المسافر لأغراض إصدار التذكرة بناءً على تاريخ السفر وليس تاريخ الحجز. وبما أن طفلكم سيكون لا يزال في الحادية عشرة من عمره في تاريخ السفر، فهو مؤهل لتذكرة الطفل رغم اقتراب عيد ميلاده الثاني عشر.",
    },
    {
      chatEn: "No problem — to book everyone correctly I just need each traveller's age: anyone 12 or older is an Adult, ages 2–11 are Child, and under 2 is Infant. Could you confirm that for me?",
      chatAr: "لا مشكلة، لإتمام الحجز بشكل صحيح أحتاج فقط لعمر كل مسافر: من هم 12 عامًا فأكثر يُحجزون كبالغين، ومن 2 إلى 11 عامًا كأطفال، وأقل من عامين كرضّع. هل يمكنكم تأكيد ذلك؟",
      emailSubjectEn: "A few details needed to complete your booking",
      emailIssueEn: "Thank you for your booking request for multiple travellers.",
      emailResolutionEn: "To classify each passenger correctly, we'll need their ages as of the travel date: 12 years or older is booked as Adult, 2–11 years as Child, and under 2 years as Infant. Please reply with this information so we can finalize your booking accurately.",
      emailSubjectAr: "بيانات إضافية مطلوبة لإتمام حجزكم",
      emailIssueAr: "شكراً لطلب حجزكم لعدة مسافرين.",
      emailResolutionAr: "لتصنيف كل مسافر بشكل صحيح، نحتاج لمعرفة عمر كل منهم في تاريخ السفر: 12 عامًا فأكثر يُحجز كبالغ، ومن 2 إلى 11 عامًا كطفل، وأقل من عامين كرضيع. يرجى الرد بهذه المعلومات لإتمام حجزكم بدقة.",
    },
    {
      chatEn: "I understand the question, but a 2-year-old no longer qualifies as an Infant — that fare applies strictly to passengers under 2 years old. Your child would need to be booked on the Child fare instead.",
      chatAr: "أتفهم استفساركم، إلا أن الطفل البالغ عامين لم يعد مؤهلاً لتذكرة الرضيع، حيث تنطبق هذه الفئة حصراً على من هم أقل من عامين. سيلزم حجز طفلكم على تذكرة الطفل بدلاً من ذلك.",
      emailSubjectEn: "Infant vs. Child ticket clarification",
      emailIssueEn: "Thank you for reaching out to confirm whether your 2-year-old qualifies for the Infant fare.",
      emailResolutionEn: "The Infant fare applies strictly to passengers under 2 years of age. As your child has reached 2 years old, they must be booked on the Child fare (ages 2–11) instead.",
      emailSubjectAr: "توضيح الفرق بين تذكرة الرضيع والطفل",
      emailIssueAr: "شكراً لتواصلكم للاستفسار عمّا إذا كان طفلكم البالغ من العمر عامين مؤهلاً لتذكرة الرضيع.",
      emailResolutionAr: "تنطبق تذكرة الرضيع حصراً على المسافرين الذين تقل أعمارهم عن عامين. وبما أن طفلكم قد أتم عامين، يجب حجزه على تذكرة الطفل (من 2 إلى 11 عامًا) بدلاً من ذلك.",
    },
  ],

  "general-travel-restrictions-children-infants-pregnant-women-all-hubs": [
    {
      chatEn: "I'm afraid a child under 12 can't travel alone — they must be accompanied by an adult aged 16 or older. From age 12 onward they can travel unaccompanied, as long as they meet both countries' immigration rules.",
      chatAr: "نأسف، لا يمكن للطفل دون سن 12 عامًا السفر بمفرده، ويجب أن يرافقه شخص بالغ لا يقل عمره عن 16 عامًا. أما من سن 12 عامًا فما فوق، فيمكنه السفر دون مرافق شريطة استيفاء متطلبات الهجرة في كلا البلدين.",
      emailSubjectEn: "Unaccompanied minor travel policy",
      emailIssueEn: "Thank you for reaching out regarding your child travelling alone.",
      emailResolutionEn: "We understand you'd like your child to travel independently. Please note that children under 12 must be accompanied by an adult aged 16 or older; children 12 and above may travel alone, provided they meet the immigration regulations of both the departing and arriving countries.",
      emailSubjectAr: "سياسة سفر القاصرين دون مرافق",
      emailIssueAr: "شكراً لتواصلكم بخصوص سفر طفلكم بمفرده.",
      emailResolutionAr: "نتفهم رغبتكم في أن يسافر طفلكم بمفرده. يرجى العلم أن الأطفال دون سن 12 عامًا يجب أن يرافقهم شخص بالغ لا يقل عمره عن 16 عامًا، بينما يمكن لمن هم 12 عامًا فأكثر السفر دون مرافق شريطة استيفاء أنظمة الهجرة في بلدي المغادرة والوصول.",
    },
    {
      chatEn: "Thanks for sharing your infant's details. At 4 days old, travel is allowed only with a Fit to Fly certificate signed and stamped by a doctor or hospital — could you arrange that before the flight?",
      chatAr: "شكراً لمشاركتكم بيانات رضيعكم. في عمر 4 أيام، يُسمح بالسفر فقط بوجود شهادة لياقة للسفر موقّعة ومختومة من طبيب أو مستشفى - هل يمكنكم تدبير ذلك قبل موعد الرحلة؟",
      emailSubjectEn: "Fit to Fly certificate required for your infant",
      emailIssueEn: "Thank you for providing your infant's date of birth for this booking.",
      emailResolutionEn: "As your infant is 3–6 days old at the time of travel, a Fit to Fly certificate is required — signed and stamped by a doctor or hospital, and valid for 14 days from issuance. Please have this ready to present at check-in.",
      emailSubjectAr: "شهادة اللياقة للسفر مطلوبة لرضيعكم",
      emailIssueAr: "شكراً لتزويدنا بتاريخ ميلاد رضيعكم لهذا الحجز.",
      emailResolutionAr: "بما أن عمر رضيعكم يتراوح بين 3 و6 أيام في تاريخ السفر، يلزم تقديم شهادة لياقة للسفر موقّعة ومختومة من طبيب أو مستشفى، وسارية المفعول لمدة 14 يومًا من تاريخ إصدارها. يرجى تجهيزها لتقديمها عند تسجيل الوصول.",
    },
    {
      chatEn: "Congratulations on the upcoming trip! For a twin pregnancy at 30 weeks, travel is allowed up to the end of week 32, and a Fit to Fly certificate is required from week 29 onward — happy to help you arrange that.",
      chatAr: "تهانينا على الرحلة القادمة! بالنسبة لحمل التوائم في الأسبوع 30، يُسمح بالسفر حتى نهاية الأسبوع 32، وتُطلب شهادة لياقة للسفر ابتداءً من الأسبوع 29 - يسعدنا مساعدتكم في تدبيرها.",
      emailSubjectEn: "Travel requirements for your pregnancy",
      emailIssueEn: "Thank you for reaching out about travelling while pregnant with twins at 30 weeks.",
      emailResolutionEn: "For a multiple pregnancy, travel is permitted up to the end of the 32nd week, and a Fit to Fly certificate is required from the 29th week onward, stating the number of weeks of pregnancy. Please arrange this certificate ahead of your flight.",
      emailSubjectAr: "متطلبات السفر أثناء الحمل",
      emailIssueAr: "شكراً لتواصلكم بخصوص السفر أثناء الحمل بتوأم في الأسبوع 30.",
      emailResolutionAr: "بالنسبة للحمل المتعدد، يُسمح بالسفر حتى نهاية الأسبوع 32، وتُطلب شهادة لياقة للسفر ابتداءً من الأسبوع 29 موضحاً فيها عدد أسابيع الحمل. يرجى تجهيز هذه الشهادة قبل موعد رحلتكم.",
    },
  ],

  "general-fit-to-fly-certificate-requirements-all-hubs": [
    {
      chatEn: "I'm sorry, but a certificate issued 20 days ago is no longer valid — it's only accepted within 14 days of issuance. Could you please arrange an updated one before travel?",
      chatAr: "نأسف، الشهادة الصادرة قبل 20 يومًا لم تعد سارية، حيث تُقبل فقط خلال 14 يومًا من تاريخ إصدارها. هل يمكنكم تدبير شهادة محدثة قبل السفر؟",
      emailSubjectEn: "Your Fit to Fly certificate has expired",
      emailIssueEn: "Thank you for submitting your Fit to Fly certificate for review.",
      emailResolutionEn: "Unfortunately the certificate provided was issued more than 14 days ago and is no longer valid for travel. Please arrange an updated certificate, signed and stamped by a doctor or hospital, dated within 14 days of your flight.",
      emailSubjectAr: "شهادة اللياقة للسفر منتهية الصلاحية",
      emailIssueAr: "شكراً لتقديم شهادة اللياقة للسفر الخاصة بكم للمراجعة.",
      emailResolutionAr: "للأسف، الشهادة المقدمة صدرت منذ أكثر من 14 يومًا ولم تعد صالحة للسفر. يرجى تدبير شهادة محدثة، موقّعة ومختومة من طبيب أو مستشفى، وبتاريخ لا يتجاوز 14 يومًا من موعد رحلتكم.",
    },
    {
      chatEn: "Thanks for sending this over. Since it doesn't mention the number of weeks of pregnancy, we'll need it reissued with that detail included before we can accept it — sorry for the extra step!",
      chatAr: "شكراً لإرسال الشهادة. بما أنها لا تتضمن عدد أسابيع الحمل، سنحتاج لإعادة إصدارها مع إضافة هذا التفصيل قبل قبولها - نعتذر عن هذه الخطوة الإضافية.",
      emailSubjectEn: "Additional detail needed on your Fit to Fly certificate",
      emailIssueEn: "Thank you for submitting your Fit to Fly certificate ahead of your flight.",
      emailResolutionEn: "As you are travelling while pregnant, the certificate must also state the number of weeks of pregnancy — this detail is currently missing. Please have it reissued to include this information so we can confirm your travel is in order.",
      emailSubjectAr: "بيانات إضافية مطلوبة في شهادة اللياقة للسفر",
      emailIssueAr: "شكراً لتقديم شهادة اللياقة للسفر قبل موعد رحلتكم.",
      emailResolutionAr: "بما أنكم مسافرات أثناء الحمل، يجب أن تتضمن الشهادة أيضًا عدد أسابيع الحمل، وهذا التفصيل غير موجود حاليًا. يرجى إعادة إصدارها لتشمل هذه المعلومة حتى نتمكن من تأكيد جاهزية سفركم.",
    },
    {
      chatEn: "Good question — the certificate must be signed and stamped by a licensed doctor or hospital. A self-declaration or non-medical form unfortunately isn't accepted.",
      chatAr: "سؤال جيد - يجب أن تكون الشهادة موقّعة ومختومة من طبيب مرخّص أو مستشفى. للأسف، لا يُقبل الإقرار الذاتي أو أي نموذج غير طبي.",
      emailSubjectEn: "Who can sign your Fit to Fly certificate",
      emailIssueEn: "Thank you for your question about who is authorized to sign a Fit to Fly certificate.",
      emailResolutionEn: "The certificate must be signed and stamped by a licensed doctor or hospital to be accepted. A self-declaration or a form not issued by a medical professional cannot be used in its place.",
      emailSubjectAr: "الجهة المخوّلة بتوقيع شهادة اللياقة للسفر",
      emailIssueAr: "شكراً لاستفساركم عن الجهة المخوّلة بتوقيع شهادة اللياقة للسفر.",
      emailResolutionAr: "يجب أن تكون الشهادة موقّعة ومختومة من طبيب مرخّص أو مستشفى ليتم قبولها. لا يمكن الاستعاضة عنها بإقرار ذاتي أو نموذج غير صادر عن جهة طبية مختصة.",
    },
  ],

  "general-hand-carry-checked-in-baggage-allowance-all-hubs": [
    {
      chatEn: "Just to let you know, the hand carry allowance is 7kg plus a separate 3kg personal item, so a single 9kg bag is over the limit. You're welcome to redistribute the weight or check the excess in — happy to help either way.",
      chatAr: "للعلم، تبلغ حقيبة اليد المسموح بها 7 كجم بالإضافة إلى قطعة شخصية منفصلة 3 كجم، لذا فإن حقيبة واحدة بوزن 9 كجم تتجاوز الحد المسموح. يمكنكم إعادة توزيع الوزن أو تسجيل الوزن الزائد ضمن الأمتعة المسجّلة - يسعدنا مساعدتكم بأي من الخيارين.",
      emailSubjectEn: "Hand carry weight limit",
      emailIssueEn: "Thank you for reaching out regarding your hand carry baggage weight.",
      emailResolutionEn: "The hand carry allowance is 7kg plus a separate 3kg personal item. As your bag weighs 9kg, it exceeds this limit — you're welcome to redistribute the excess into checked baggage or purchase additional checked allowance.",
      emailSubjectAr: "الحد الأقصى لوزن حقيبة اليد",
      emailIssueAr: "شكراً لتواصلكم بخصوص وزن حقيبة اليد الخاصة بكم.",
      emailResolutionAr: "الحد المسموح لحقيبة اليد هو 7 كجم بالإضافة إلى قطعة شخصية منفصلة بوزن 3 كجم. بما أن حقيبتكم تزن 9 كجم، فهي تتجاوز هذا الحد - يمكنكم إعادة توزيع الوزن الزائد ضمن الأمتعة المسجّلة أو شراء وزن إضافي مسجّل.",
    },
    {
      chatEn: "Good question! Infants don't get a checked baggage allowance — only the accompanying adult's allowance applies. They are entitled to a small 3kg hand-carry bag, though.",
      chatAr: "سؤال جيد! لا يحصل الرضّع على أمتعة مسجّلة مجانية، وتنطبق فقط الحقيبة المسموح بها للبالغ المرافق. لكن يحق للرضيع حقيبة يد صغيرة بوزن 3 كجم.",
      emailSubjectEn: "Baggage allowance for infants",
      emailIssueEn: "Thank you for asking about the checked baggage allowance for your infant.",
      emailResolutionEn: "Infants are not entitled to any checked-in baggage allowance — only the accompanying adult's allowance applies. Infants do receive a small hand-carry allowance of up to 3kg for items needed during the flight.",
      emailSubjectAr: "أمتعة الرضّع",
      emailIssueAr: "شكراً لاستفساركم عن الأمتعة المسجّلة المسموح بها لرضيعكم.",
      emailResolutionAr: "لا يحق للرضّع أي أمتعة مسجّلة مجانية، وتنطبق فقط الحقيبة المسموح بها للبالغ المرافق. يحق للرضيع حقيبة يد صغيرة بحد أقصى 3 كجم للأغراض اللازمة أثناء الرحلة.",
    },
    {
      chatEn: "I see your bag is 35kg as a single piece — since the limit per piece is 32kg, I'd suggest splitting it into two bags, or I can quote you the per-kilo excess baggage charge if you'd rather keep it as one.",
      chatAr: "ألاحظ أن حقيبتكم تزن 35 كجم كقطعة واحدة - وبما أن الحد الأقصى للقطعة الواحدة هو 32 كجم، أقترح تقسيمها إلى حقيبتين، أو يمكنني تزويدكم برسوم الوزن الزائد لكل كيلوغرام إذا فضّلتم إبقاءها كقطعة واحدة.",
      emailSubjectEn: "Checked baggage over the single-piece limit",
      emailIssueEn: "Thank you for reaching out regarding your 35kg checked bag.",
      emailResolutionEn: "Each checked bag must not exceed 32kg per piece. Since your bag is at 35kg, we recommend redistributing the weight into a second piece (additional-piece fees apply), or paying the per-kilo excess baggage charge at the airport if it stays as one piece.",
      emailSubjectAr: "الأمتعة المسجّلة تتجاوز الحد المسموح للقطعة الواحدة",
      emailIssueAr: "شكراً لتواصلكم بخصوص حقيبتكم المسجّلة البالغ وزنها 35 كجم.",
      emailResolutionAr: "يجب ألا يتجاوز وزن كل حقيبة مسجّلة 32 كجم للقطعة الواحدة. وبما أن حقيبتكم تزن 35 كجم، نوصي بإعادة توزيع الوزن إلى قطعة ثانية (تُطبَّق رسوم القطعة الإضافية)، أو دفع رسوم الوزن الزائد لكل كيلوغرام في المطار إذا أبقيتموها كقطعة واحدة.",
    },
  ],

  "general-restricted-items-in-checked-in-baggage-all-hubs": [
    {
      chatEn: "I'm afraid cooking oil is on our restricted items list for checked baggage and can't be accepted, even in small quantities. You'll need to leave it out of your suitcase before check-in.",
      chatAr: "نأسف، زيت الطهي مدرج ضمن قائمة الأصناف المحظورة في الأمتعة المسجّلة ولا يمكن قبوله حتى بكميات صغيرة. يرجى عدم وضعه في حقيبتكم قبل تسجيل الوصول.",
      emailSubjectEn: "Cooking oil is a restricted checked-baggage item",
      emailIssueEn: "Thank you for checking whether cooking oil can be carried in checked baggage.",
      emailResolutionEn: "Cooking oil is on our list of restricted items for checked baggage and cannot be accepted. Please remove it from your luggage before check-in to avoid delays at the airport.",
      emailSubjectAr: "زيت الطهي من الأصناف المحظورة في الأمتعة المسجّلة",
      emailIssueAr: "شكراً لاستفساركم عن إمكانية نقل زيت الطهي ضمن الأمتعة المسجّلة.",
      emailResolutionAr: "زيت الطهي مدرج ضمن قائمة الأصناف المحظورة في الأمتعة المسجّلة ولا يمكن قبوله. يرجى إخراجه من أمتعتكم قبل تسجيل الوصول لتجنب أي تأخير في المطار.",
    },
    {
      chatEn: "Unfortunately not — wet-cell car batteries are classified as corrosive material and are banned from checked baggage for safety reasons.",
      chatAr: "للأسف لا - تُصنَّف بطاريات السيارات السائلة كمواد أكّالة ويُحظر نقلها ضمن الأمتعة المسجّلة لأسباب تتعلق بالسلامة.",
      emailSubjectEn: "Car batteries cannot be checked in",
      emailIssueEn: "Thank you for checking whether a car battery can be carried in checked baggage.",
      emailResolutionEn: "Wet-cell batteries are classified as corrosive materials and are banned from checked baggage for safety reasons. Please arrange alternative transport for this item.",
      emailSubjectAr: "لا يمكن نقل بطاريات السيارات ضمن الأمتعة المسجّلة",
      emailIssueAr: "شكراً لاستفساركم عن إمكانية نقل بطارية سيارة ضمن الأمتعة المسجّلة.",
      emailResolutionAr: "تُصنَّف البطاريات السائلة كمواد أكّالة ويُحظر نقلها ضمن الأمتعة المسجّلة لأسباب تتعلق بالسلامة. يرجى ترتيب وسيلة نقل بديلة لهذا الصنف.",
    },
    {
      chatEn: "Sorry, camping-stove fuel falls under flammable liquids, which aren't allowed in checked baggage. Happy to point you to our full prohibited-items list if you have other items you're unsure about.",
      chatAr: "نأسف، وقود موقد التخييم يندرج ضمن السوائل القابلة للاشتعال، وهي غير مسموح بها في الأمتعة المسجّلة. يسعدنا تزويدكم بقائمة الأصناف المحظورة الكاملة إذا كانت لديكم أصناف أخرى غير متأكدين منها.",
      emailSubjectEn: "Camping-stove fuel is a restricted item",
      emailIssueEn: "Thank you for checking whether camping-stove fuel can be carried in checked baggage.",
      emailResolutionEn: "Flammable liquids such as lighter or heater fuel are restricted items and cannot be carried in checked baggage. Please refer to our full prohibited items list on our website if you have other items to double-check.",
      emailSubjectAr: "وقود موقد التخييم من الأصناف المحظورة",
      emailIssueAr: "شكراً لاستفساركم عن إمكانية نقل وقود موقد التخييم ضمن الأمتعة المسجّلة.",
      emailResolutionAr: "تُعد السوائل القابلة للاشتعال مثل وقود الولاعات أو أجهزة التدفئة من الأصناف المحظورة ولا يمكن نقلها ضمن الأمتعة المسجّلة. يرجى مراجعة قائمة الأصناف المحظورة الكاملة على موقعنا الإلكتروني لأي أصناف أخرى غير متأكدين منها.",
    },
  ],

  "general-special-checked-in-baggage-items-olive-oil-zamzam-water-baby-stroller": [
    {
      chatEn: "For G9 flights, olive oil is only accepted if it's in a steel container placed inside a wrapped wooden box — a plain plastic bottle won't be accepted, I'm afraid.",
      chatAr: "بالنسبة لرحلات G9، يُقبل زيت الزيتون فقط إذا كان داخل وعاء معدني موضوع داخل صندوق خشبي مغلّف - للأسف، لا تُقبل الزجاجة البلاستيكية العادية.",
      emailSubjectEn: "Packaging requirements for carrying olive oil",
      emailIssueEn: "Thank you for checking how to carry olive oil in your checked baggage on your G9 flight.",
      emailResolutionEn: "Olive oil is accepted only when packed in a steel container placed inside a wrapped wooden box. A plastic bottle or other packaging does not meet this requirement and cannot be accepted.",
      emailSubjectAr: "متطلبات تعبئة زيت الزيتون",
      emailIssueAr: "شكراً لاستفساركم عن كيفية نقل زيت الزيتون ضمن أمتعتكم المسجّلة على رحلة G9.",
      emailResolutionAr: "يُقبل زيت الزيتون فقط إذا كان معبأً في وعاء معدني موضوع داخل صندوق خشبي مغلّف. لا تُقبل الزجاجات البلاستيكية أو أي تعبئة أخرى لا تستوفي هذا الشرط.",
    },
    {
      chatEn: "Just one 5-litre bottle of Zamzam water is free per passenger, purchased from an authorized airport shop — a second bottle unfortunately can't be added, even on Zamzam-eligible routes.",
      chatAr: "يُسمح فقط بزجاجة واحدة سعة 5 لتر من ماء زمزم مجانًا لكل مسافر، ويجب شراؤها من متجر معتمد في المطار - للأسف، لا يمكن إضافة زجاجة ثانية حتى على الرحلات المؤهلة لذلك.",
      emailSubjectEn: "Zamzam water allowance",
      emailIssueEn: "Thank you for asking about carrying Zamzam water on your flight.",
      emailResolutionEn: "Passengers travelling from KSA may carry one 5-litre bottle of Zamzam water free of charge as checked baggage, purchased from an authorized airport sale shop. Additional bottles are not permitted.",
      emailSubjectAr: "أمتعة ماء زمزم",
      emailIssueAr: "شكراً لاستفساركم عن نقل ماء زمزم على متن رحلتكم.",
      emailResolutionAr: "يُسمح للمسافرين المغادرين من المملكة العربية السعودية بنقل زجاجة واحدة سعة 5 لتر من ماء زمزم مجانًا ضمن الأمتعة المسجّلة، شريطة شرائها من متجر معتمد في المطار. لا يُسمح بإضافة زجاجات أخرى.",
    },
    {
      chatEn: "Good news — if you use the stroller up to the boarding gate instead of checking it at the counter, it's free of the baggage allowance and will be returned to you with your checked bags on arrival.",
      chatAr: "خبر سار - إذا استخدمتم عربة الأطفال حتى بوابة الصعود بدلاً من تسجيلها عند الكاونتر، فلن تُحتسب ضمن الأمتعة المسموح بها، وستُعاد لكم مع الأمتعة المسجّلة عند الوصول.",
      emailSubjectEn: "Baby stroller allowance",
      emailIssueEn: "Thank you for asking whether your stroller counts toward your baggage allowance.",
      emailResolutionEn: "If your stroller is used up to the boarding gate rather than checked in at the counter, it is not counted against your baggage allowance, and it will be returned to you with your checked baggage on arrival.",
      emailSubjectAr: "أمتعة عربة الأطفال",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كانت عربة الأطفال تُحتسب ضمن الأمتعة المسموح بها.",
      emailResolutionAr: "إذا استُخدمت عربة الأطفال حتى بوابة الصعود دون تسجيلها عند الكاونتر، فلن تُحتسب ضمن الأمتعة المسموح بها، وستُعاد لكم مع الأمتعة المسجّلة عند الوصول.",
    },
  ],

  "general-seating-front-row-benefits-exit-seat-rules-all-hubs": [
    {
      chatEn: "I'd be glad to arrange a front-row seat for you — that's the only row eligible for a baby bassinet. It's subject to availability, so I'll check that for your flight now.",
      chatAr: "يسعدني ترتيب مقعد في الصف الأمامي لكم - وهو الصف الوحيد المؤهل لطلب سرير للطفل الرضيع. يخضع ذلك للتوفر، وسأتحقق من ذلك على رحلتكم الآن.",
      emailSubjectEn: "Baby bassinet seating request",
      emailIssueEn: "Thank you for requesting a bassinet seat for your infant.",
      emailResolutionEn: "Baby bassinets are only available to front-row seated passengers, subject to availability. We've noted your request and will confirm bassinet availability closer to your flight.",
      emailSubjectAr: "طلب مقعد مزوّد بسرير للرضيع",
      emailIssueAr: "شكراً لطلبكم مقعدًا مزوّدًا بسرير لرضيعكم.",
      emailResolutionAr: "تتوفر أسرّة الأطفال الرضّع فقط للمسافرين الجالسين في الصف الأمامي، وتخضع للتوفر. لقد سجّلنا طلبكم وسنؤكد التوفر قبيل موعد رحلتكم.",
    },
    {
      chatEn: "I'm sorry, but pregnant passengers can't be seated in an emergency exit row under our safety rules — I'd be happy to offer you an alternative seat with extra space instead.",
      chatAr: "نأسف، لا يمكن جلوس المسافرات الحوامل في صف مخرج الطوارئ وفقًا لقواعد السلامة لدينا - يسعدني تقديم مقعد بديل بمساحة إضافية لكم.",
      emailSubjectEn: "Exit row seating not available",
      emailIssueEn: "Thank you for your request to be seated in the emergency exit row.",
      emailResolutionEn: "For safety reasons, pregnant passengers are not permitted to occupy an emergency exit seat. We'd be happy to offer an alternative seat with extra legroom — please let us know your preference.",
      emailSubjectAr: "عدم توفر مقاعد صف مخرج الطوارئ",
      emailIssueAr: "شكراً لطلبكم الجلوس في صف مخرج الطوارئ.",
      emailResolutionAr: "لأسباب تتعلق بالسلامة، لا يُسمح للمسافرات الحوامل بشغل مقعد مخرج الطوارئ. يسعدنا تقديم مقعد بديل بمساحة إضافية للأرجل - يرجى إخبارنا بتفضيلاتكم.",
    },
    {
      chatEn: "I appreciate the request, but exit row seating requires passengers to be older than 16, so I'll need to find a different seating arrangement for your family — happy to help with that now.",
      chatAr: "أقدّر طلبكم، إلا أن مقاعد صف مخرج الطوارئ تتطلب أن يتجاوز عمر المسافر 16 عامًا، لذا سأحتاج لإيجاد ترتيب جلوس مختلف لعائلتكم - يسعدني المساعدة في ذلك الآن.",
      emailSubjectEn: "Exit row age requirement",
      emailIssueEn: "Thank you for your seating request for your 15-year-old family member.",
      emailResolutionEn: "Exit row seats require passengers to be older than 16 years of age, so we're unable to seat your 15-year-old there. We'd be glad to arrange an alternative seating arrangement for your family — let us know your preferences.",
      emailSubjectAr: "الحد الأدنى للعمر لصف مخرج الطوارئ",
      emailIssueAr: "شكراً لطلبكم الجلوس لأحد أفراد عائلتكم البالغ من العمر 15 عامًا.",
      emailResolutionAr: "تتطلب مقاعد صف مخرج الطوارئ أن يتجاوز عمر المسافر 16 عامًا، لذا لا يمكننا إجلاس المسافر البالغ 15 عامًا هناك. يسعدنا ترتيب مقاعد بديلة لعائلتكم - يرجى إخبارنا بتفضيلاتكم.",
    },
  ],

  "general-travel-insurance-all-hubs": [
    {
      chatEn: "Good question — your insurance dates don't update automatically when you change your return date. I'd recommend contacting Tune Protect directly to check if your policy can be adjusted.",
      chatAr: "سؤال جيد - لا يتم تحديث تواريخ التأمين تلقائيًا عند تعديل تاريخ العودة. أنصح بالتواصل مباشرة مع شركة Tune Protect للتحقق من إمكانية تعديل بوليصتكم.",
      emailSubjectEn: "Insurance policy dates after a date change",
      emailIssueEn: "Thank you for reaching out about your travel insurance following your return date change.",
      emailResolutionEn: "Please note that your Tune Protect insurance policy is not automatically updated when you change your return date. We'd recommend contacting Tune Protect directly to check whether your policy dates can be adjusted.",
      emailSubjectAr: "تواريخ بوليصة التأمين بعد تعديل الموعد",
      emailIssueAr: "شكراً لتواصلكم بخصوص تأمين السفر الخاص بكم بعد تعديل تاريخ العودة.",
      emailResolutionAr: "يرجى العلم أن بوليصة تأمين Tune Protect الخاصة بكم لا يتم تحديثها تلقائيًا عند تعديل تاريخ العودة. نوصي بالتواصل مباشرة مع Tune Protect للتحقق من إمكانية تعديل تواريخ البوليصة.",
    },
    {
      chatEn: "Baggage delay cover is part of our Platinum plan, so it isn't included on Gold — you're still covered for medical, evacuation and hospital allowance benefits though. Want me to walk you through upgrading?",
      chatAr: "تغطية تأخر الأمتعة جزء من خطة Platinum، وبالتالي فهي غير مشمولة في خطة Gold - لكنكم مغطون بالبنود الطبية وبنود الإخلاء الطبي وبدل الاستشفاء. هل ترغبون بمعرفة تفاصيل الترقية؟",
      emailSubjectEn: "Baggage delay coverage — Gold vs. Platinum",
      emailIssueEn: "Thank you for asking about baggage delay compensation under your Gold insurance plan.",
      emailResolutionEn: "Baggage delay coverage is exclusive to the Platinum plan and is not included in Gold. Your Gold plan still covers medical and sickness reimbursement, hospital allowance, and 24/7 emergency assistance. Let us know if you'd like details on upgrading to Platinum.",
      emailSubjectAr: "تغطية تأخر الأمتعة - الفرق بين Gold وPlatinum",
      emailIssueAr: "شكراً لاستفساركم عن تعويض تأخر الأمتعة ضمن خطة Gold الخاصة بكم.",
      emailResolutionAr: "تُعد تغطية تأخر الأمتعة حصرية لخطة Platinum وغير مشمولة في خطة Gold. تشمل خطة Gold الخاصة بكم التعويض الطبي وبدل الاستشفاء والمساعدة الطارئة على مدار الساعة. يسعدنا إرسال تفاصيل الترقية إلى Platinum إذا رغبتم.",
    },
    {
      chatEn: "For a 100-day trip, coverage only runs to day 91 from your first departure, so the final stretch of your trip wouldn't be insured — happy to help you look at extending or arranging separate cover for those extra days.",
      chatAr: "بالنسبة لرحلة مدتها 100 يوم، تمتد التغطية فقط حتى اليوم 91 من تاريخ المغادرة الأول، وبالتالي فإن الفترة المتبقية من رحلتكم لن تكون مغطاة - يسعدني مساعدتكم في بحث خيارات تمديد التغطية أو ترتيب تأمين منفصل لتلك الأيام.",
      emailSubjectEn: "Insurance coverage duration for your trip",
      emailIssueEn: "Thank you for reaching out about insurance coverage for your 100-day trip.",
      emailResolutionEn: "Coverage runs for a maximum of 90 days from your first departure date; for a 100-day trip, coverage would end on day 91, leaving part of your trip uninsured. We'd recommend contacting Tune Protect to discuss extended or supplementary coverage.",
      emailSubjectAr: "مدة تغطية التأمين لرحلتكم",
      emailIssueAr: "شكراً لتواصلكم بخصوص تغطية التأمين لرحلتكم التي تمتد 100 يوم.",
      emailResolutionAr: "تمتد التغطية بحد أقصى 90 يومًا من تاريخ المغادرة الأول؛ وبالنسبة لرحلة مدتها 100 يوم، ستنتهي التغطية في اليوم 91، تاركةً جزءًا من رحلتكم دون تغطية. نوصي بالتواصل مع Tune Protect لبحث خيارات التغطية الممتدة أو الإضافية.",
    },
  ],

  "general-wheelchair-assistance-all-hubs": [
    {
      chatEn: "I'm afraid personal wheelchairs can't be used within the airport — wheelchair assistance is provided by the airport's own service team, and any applicable charge is assessed at check-in.",
      chatAr: "نأسف، لا يمكن استخدام الكرسي المتحرك الشخصي داخل المطار - تُقدَّم خدمة الكرسي المتحرك من قبل فريق خدمات المطار، وتُحدَّد أي رسوم عند تسجيل الوصول.",
      emailSubjectEn: "Wheelchair assistance policy",
      emailIssueEn: "Thank you for reaching out about using your own wheelchair at the airport.",
      emailResolutionEn: "Personal wheelchairs cannot be used within the airport. Wheelchair assistance is instead provided by the airport's own service provider, with any applicable charge assessed at check-in based on your situation.",
      emailSubjectAr: "سياسة خدمة الكرسي المتحرك",
      emailIssueAr: "شكراً لتواصلكم بخصوص استخدام كرسيكم المتحرك الشخصي في المطار.",
      emailResolutionAr: "لا يمكن استخدام الكرسي المتحرك الشخصي داخل المطار. تُقدَّم خدمة الكرسي المتحرك بدلاً من ذلك من قبل مزوّد خدمات المطار، وتُحدَّد أي رسوم عند تسجيل الوصول وفقًا لحالتكم.",
    },
    {
      chatEn: "It depends on your situation, so I can't promise it's completely free — the airport service provider assesses this and any charge is collected at check-in.",
      chatAr: "يعتمد ذلك على حالتكم، لذا لا يمكنني تأكيد أنها مجانية بالكامل - يقيّم مزوّد خدمات المطار ذلك، وتُحصَّل أي رسوم عند تسجيل الوصول.",
      emailSubjectEn: "Wheelchair assistance charges",
      emailIssueEn: "Thank you for asking whether wheelchair assistance is free of charge.",
      emailResolutionEn: "Wheelchair assistance charges depend on the passenger's situation as assessed by the airport service provider, and may be collected at check-in. We'd recommend confirming the exact charge, if any, when you arrive.",
      emailSubjectAr: "رسوم خدمة الكرسي المتحرك",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كانت خدمة الكرسي المتحرك مجانية.",
      emailResolutionAr: "تعتمد رسوم خدمة الكرسي المتحرك على حالة المسافر وفقًا لتقييم مزوّد خدمات المطار، وقد تُحصَّل عند تسجيل الوصول. نوصي بتأكيد الرسوم بالضبط، إن وجدت، عند وصولكم.",
    },
    {
      chatEn: "Wheelchair assistance is arranged directly through the airport's own service provider rather than through us — I'd recommend requesting it as early as possible ahead of your flight.",
      chatAr: "تُرتَّب خدمة الكرسي المتحرك مباشرة عبر مزوّد خدمات المطار وليس عبرنا - أنصح بطلبها في أقرب وقت ممكن قبل موعد رحلتكم.",
      emailSubjectEn: "How to arrange wheelchair assistance",
      emailIssueEn: "Thank you for asking who to contact to arrange wheelchair assistance in advance.",
      emailResolutionEn: "Wheelchair assistance is arranged directly through the airport's own service provider rather than through Air Arabia. We recommend requesting it as early as possible, ideally at the time of booking or check-in.",
      emailSubjectAr: "كيفية ترتيب خدمة الكرسي المتحرك",
      emailIssueAr: "شكراً لاستفساركم عن الجهة التي يمكن التواصل معها لترتيب خدمة الكرسي المتحرك مسبقًا.",
      emailResolutionAr: "تُرتَّب خدمة الكرسي المتحرك مباشرة عبر مزوّد خدمات المطار وليس عبر العربية للطيران. نوصي بطلبها في أقرب وقت ممكن، ويفضّل عند الحجز أو تسجيل الوصول.",
    },
  ],

  "general-ancillary-cut-off-times-all-hubs": [
    {
      chatEn: "I'm sorry, but 3O meal requests need 48 hours' notice, so at 6 hours out we're past that window and can't add it — you're still welcome to purchase a meal at the airport if available.",
      chatAr: "نأسف، تتطلب طلبات الوجبات على رحلات 3O إشعارًا مسبقًا بـ 48 ساعة، وبما أننا الآن قبل 6 ساعات من الرحلة، فقد تجاوزنا هذه المهلة - يمكنكم شراء وجبة من المطار إذا كانت متوفرة.",
      emailSubjectEn: "Meal cut-off time has passed",
      emailIssueEn: "Thank you for your request to add a meal to your 3O booking.",
      emailResolutionEn: "Meal requests on 3O must be made at least 48 hours prior to departure. As your flight is closer than that, we're unable to add a meal through this channel — a meal may still be available for purchase at the airport, subject to availability.",
      emailSubjectAr: "انتهت مهلة إضافة الوجبة",
      emailIssueAr: "شكراً لطلبكم إضافة وجبة إلى حجزكم على رحلة 3O.",
      emailResolutionAr: "يجب تقديم طلبات الوجبات على رحلات 3O قبل 48 ساعة على الأقل من موعد المغادرة. وبما أن موعد رحلتكم أقرب من ذلك، لا يمكننا إضافة وجبة عبر هذه القناة - قد تتوفر وجبة للشراء في المطار حسب التوفر.",
    },
    {
      chatEn: "Unfortunately G9 baggage additions need 12 hours' notice, and we're inside that window now — I'd suggest purchasing the excess baggage directly at the airport instead.",
      chatAr: "للأسف، تتطلب إضافة الأمتعة على رحلات G9 إشعارًا مسبقًا بـ 12 ساعة، ونحن الآن ضمن هذه المهلة - أقترح شراء الوزن الزائد مباشرة من المطار.",
      emailSubjectEn: "Baggage cut-off time has passed",
      emailIssueEn: "Thank you for your request to add checked baggage to your G9 booking.",
      emailResolutionEn: "Baggage additions on G9 must be made at least 12 hours prior to departure. As your flight is inside that window, we recommend purchasing the excess baggage directly at the airport instead.",
      emailSubjectAr: "انتهت مهلة إضافة الأمتعة",
      emailIssueAr: "شكراً لطلبكم إضافة أمتعة مسجّلة إلى حجزكم على رحلة G9.",
      emailResolutionAr: "يجب تقديم طلبات إضافة الأمتعة على رحلات G9 قبل 12 ساعة على الأقل من موعد المغادرة. وبما أن موعد رحلتكم ضمن هذه المهلة، نوصي بشراء الوزن الزائد مباشرة من المطار.",
    },
    {
      chatEn: "3O wheelchair requests need 24 hours' notice, so at 12 hours out I can't guarantee it through this channel — I'd recommend contacting the airport directly to arrange it.",
      chatAr: "تتطلب طلبات الكرسي المتحرك على رحلات 3O إشعارًا مسبقًا بـ 24 ساعة، وبما أننا الآن قبل 12 ساعة من الرحلة، لا يمكنني ضمان ذلك عبر هذه القناة - أنصح بالتواصل مباشرة مع المطار لترتيب ذلك.",
      emailSubjectEn: "Wheelchair request cut-off time",
      emailIssueEn: "Thank you for your request to add wheelchair assistance to your 3O booking.",
      emailResolutionEn: "Wheelchair requests on 3O require 24 hours' notice. As your flight is inside that window, we can't guarantee this request through the Call Center — please contact the airport directly to arrange assistance.",
      emailSubjectAr: "مهلة طلب خدمة الكرسي المتحرك",
      emailIssueAr: "شكراً لطلبكم إضافة خدمة الكرسي المتحرك إلى حجزكم على رحلة 3O.",
      emailResolutionAr: "تتطلب طلبات الكرسي المتحرك على رحلات 3O إشعارًا مسبقًا بـ 24 ساعة. وبما أن موعد رحلتكم ضمن هذه المهلة، لا يمكننا ضمان هذا الطلب عبر مركز الاتصال - يرجى التواصل مباشرة مع المطار لترتيب المساعدة.",
    },
  ],

  "general-check-in-timings-all-hubs": [
    {
      chatEn: "Good news — 9P Domestic counters close 45 minutes before departure, so at 50 minutes out you're still fine. I'd recommend heading there right away just to be safe.",
      chatAr: "خبر سار - تُغلق كاونترات رحلات 9P الداخلية قبل 45 دقيقة من المغادرة، وبما أنكم على بعد 50 دقيقة، فلا يزال الوقت كافيًا. أنصح بالتوجه إلى هناك فورًا للاطمئنان.",
      emailSubjectEn: "9P Domestic check-in counter timing",
      emailIssueEn: "Thank you for checking whether you can still make it to the check-in counter.",
      emailResolutionEn: "9P Domestic check-in counters close 45 minutes prior to departure, so arriving with 50 minutes to spare is within the window. We'd still recommend heading to the counter immediately to allow extra time.",
      emailSubjectAr: "مواعيد كاونتر تسجيل وصول رحلات 9P الداخلية",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كان لا يزال بإمكانكم الوصول إلى كاونتر تسجيل الوصول.",
      emailResolutionAr: "تُغلق كاونترات تسجيل وصول رحلات 9P الداخلية قبل 45 دقيقة من موعد المغادرة، وبالتالي فإن الوصول قبل 50 دقيقة يقع ضمن هذه المهلة. ننصح مع ذلك بالتوجه إلى الكاونتر فورًا لضمان وقت إضافي.",
    },
    {
      chatEn: "You can head to the counter as early as 3 hours before your G9 flight — arriving with some buffer time is always a good idea!",
      chatAr: "يمكنكم التوجه إلى الكاونتر قبل 3 ساعات من موعد رحلة G9 - ومن الأفضل دائمًا الوصول قبل ذلك بوقت إضافي!",
      emailSubjectEn: "Check-in counter opening time",
      emailIssueEn: "Thank you for asking how early you can check in for your G9 flight.",
      emailResolutionEn: "Standard check-in counters open 3 hours prior to scheduled departure. We recommend arriving within that window, with some buffer time in case of queues.",
      emailSubjectAr: "موعد فتح كاونتر تسجيل الوصول",
      emailIssueAr: "شكراً لاستفساركم عن الموعد الذي يمكنكم فيه تسجيل الوصول لرحلة G9.",
      emailResolutionAr: "تُفتح كاونترات تسجيل الوصول قبل 3 ساعات من موعد المغادرة المحدد. نوصي بالوصول ضمن هذه المهلة مع بعض الوقت الإضافي تحسبًا للازدحام.",
    },
    {
      chatEn: "For an international 9P sector, the standard 1-hour closing rule applies rather than the domestic 45-minute exception — at 50 minutes out, I'm afraid the counter has likely already closed. Let me check what options are available.",
      chatAr: "بالنسبة لقطاع 9P الدولي، تُطبَّق قاعدة الإغلاق القياسية قبل ساعة واحدة بدلاً من استثناء الرحلات الداخلية البالغ 45 دقيقة - وبعد 50 دقيقة، من المرجح أن الكاونتر قد أُغلق بالفعل. دعوني أتحقق من الخيارات المتاحة.",
      emailSubjectEn: "International sector check-in closing time",
      emailIssueEn: "Thank you for reaching out about check-in for your international 9P flight.",
      emailResolutionEn: "International 9P sectors follow the standard 1-hour closing rule, not the 45-minute domestic exception. As you're inside that window, the counter has likely closed — we're escalating this to the airport team to check what options remain.",
      emailSubjectAr: "موعد إغلاق تسجيل الوصول للقطاع الدولي",
      emailIssueAr: "شكراً لتواصلكم بخصوص تسجيل الوصول لرحلة 9P الدولية.",
      emailResolutionAr: "تُطبَّق على قطاعات 9P الدولية قاعدة الإغلاق القياسية قبل ساعة واحدة، وليس استثناء الرحلات الداخلية البالغ 45 دقيقة. وبما أنكم ضمن هذه المهلة، فمن المرجح أن الكاونتر قد أُغلق - نقوم بتصعيد الأمر لفريق المطار للتحقق من الخيارات المتاحة.",
    },
  ],

  "general-online-check-in-all-hubs": [
    {
      chatEn: "No need to worry — that just means the destination airport doesn't accept online boarding passes. Please head to the check-in counter with your booking reference to collect the physical one.",
      chatAr: "لا داعي للقلق - هذا يعني فقط أن مطار الوصول لا يقبل بطاقات الصعود الإلكترونية. يرجى التوجه إلى كاونتر تسجيل الوصول ببيانات الحجز للحصول على البطاقة الورقية.",
      emailSubjectEn: "Boarding pass not received after online check-in",
      emailIssueEn: "Thank you for reaching out about not receiving a boarding pass after completing online check-in.",
      emailResolutionEn: "A successful check-in message with no boarding pass simply means your destination airport does not accept online boarding passes. Please proceed to the check-in counter with your booking reference to collect the physical boarding pass.",
      emailSubjectAr: "عدم استلام بطاقة الصعود بعد تسجيل الوصول الإلكتروني",
      emailIssueAr: "شكراً لتواصلكم بخصوص عدم استلام بطاقة الصعود بعد إتمام تسجيل الوصول الإلكتروني.",
      emailResolutionAr: "رسالة تسجيل الوصول الناجح دون استلام بطاقة صعود تعني فقط أن مطار الوصول لا يقبل بطاقات الصعود الإلكترونية. يرجى التوجه إلى كاونتر تسجيل الوصول ببيانات الحجز للحصول على البطاقة الورقية.",
    },
    {
      chatEn: "Online check-in only opens 48 hours before departure, so at 50 hours out it isn't quite open yet — please try again once you're within that window.",
      chatAr: "يُفتح تسجيل الوصول الإلكتروني قبل 48 ساعة فقط من المغادرة، وبما أنكم على بعد 50 ساعة، فلم يُفتح بعد - يرجى المحاولة مجددًا عند الوصول ضمن هذه المهلة.",
      emailSubjectEn: "Online check-in not yet open",
      emailIssueEn: "Thank you for trying to check in online ahead of your flight.",
      emailResolutionEn: "Online check-in opens 48 hours prior to departure. As your attempt was made outside that window, please try again once you're within 48 hours of your flight.",
      emailSubjectAr: "تسجيل الوصول الإلكتروني لم يُفتح بعد",
      emailIssueAr: "شكراً لمحاولتكم تسجيل الوصول إلكترونيًا قبل موعد رحلتكم.",
      emailResolutionAr: "يُفتح تسجيل الوصول الإلكتروني قبل 48 ساعة من موعد المغادرة. وبما أن محاولتكم كانت خارج هذه المهلة، يرجى المحاولة مجددًا عند الوصول إلى هذه المهلة.",
    },
    {
      chatEn: "Online check-in closes 3 hours before departure, so at 2 hours out it's already closed — please head straight to the airport check-in counter instead.",
      chatAr: "يُغلق تسجيل الوصول الإلكتروني قبل 3 ساعات من المغادرة، وبما أنكم على بعد ساعتين، فقد أُغلق بالفعل - يرجى التوجه مباشرة إلى كاونتر تسجيل الوصول في المطار.",
      emailSubjectEn: "Online check-in window has closed",
      emailIssueEn: "Thank you for trying to check in online ahead of your flight.",
      emailResolutionEn: "Online check-in closes 3 hours prior to departure. As this window has passed, please proceed directly to the airport check-in counter to complete your check-in.",
      emailSubjectAr: "انتهت مهلة تسجيل الوصول الإلكتروني",
      emailIssueAr: "شكراً لمحاولتكم تسجيل الوصول إلكترونيًا قبل موعد رحلتكم.",
      emailResolutionAr: "يُغلق تسجيل الوصول الإلكتروني قبل 3 ساعات من موعد المغادرة. وبما أن هذه المهلة قد انتهت، يرجى التوجه مباشرة إلى كاونتر تسجيل الوصول في المطار لإتمام تسجيل وصولكم.",
    },
  ],

  "general-no-show-airport-taxes-all-hubs": [
    {
      chatEn: "I'm sorry to hear you missed your flight. Since 3O doesn't auto-credit no-show taxes, but you're asking directly, I'll go ahead and raise the request to process your airport tax credit now.",
      chatAr: "يؤسفنا سماع أنكم فاتتكم الرحلة. بما أن رحلات 3O لا تُرصد ضرائب المطار تلقائيًا في حالة عدم الحضور، وبما أنكم تطلبون ذلك مباشرة، سأقوم بتقديم طلب معالجة رصيد ضرائب المطار الآن.",
      emailSubjectEn: "No-show airport tax credit request",
      emailIssueEn: "We're sorry to hear you were unable to make your 3O flight, and thank you for reaching out regarding your airport taxes.",
      emailResolutionEn: "Unlike G9, E5 and 9P, 3O does not automatically initiate a no-show tax credit. As you've requested it directly, we've raised the request to process your airport tax credit — it will be kept under your name and valid for up to 1 year from the date of payment.",
      emailSubjectAr: "طلب رصيد ضرائب المطار لعدم الحضور",
      emailIssueAr: "يؤسفنا عدم تمكنكم من اللحاق برحلة 3O، ونشكركم على تواصلكم بخصوص ضرائب المطار الخاصة بكم.",
      emailResolutionAr: "خلافًا لرحلات G9 وE5 و9P، لا تُبادر رحلات 3O تلقائيًا برصد ضريبة عدم الحضور. وبما أنكم طلبتم ذلك مباشرة، قمنا بتقديم طلب معالجة رصيد ضرائب المطار، والذي سيُحفظ باسمكم وسيكون ساري المفعول لمدة تصل إلى عام واحد من تاريخ الدفع.",
    },
    {
      chatEn: "Good news — your credit from 8 months ago is still valid, since it lasts up to 1 year from the date of payment. Let me check its status in the system and apply it to your new booking.",
      chatAr: "خبر سار - رصيدكم من قبل 8 أشهر لا يزال ساريًا، حيث يستمر لمدة تصل إلى عام واحد من تاريخ الدفع. دعوني أتحقق من حالته في النظام وأطبّقه على حجزكم الجديد.",
      emailSubjectEn: "Applying your no-show tax credit",
      emailIssueEn: "Thank you for reaching out about using the airport tax credit from your missed flight 8 months ago.",
      emailResolutionEn: "This credit remains valid, as it is usable for up to 1 year from the date of payment. We've checked its status in Accel Aero and can apply it toward your new booking.",
      emailSubjectAr: "تطبيق رصيد ضريبة عدم الحضور",
      emailIssueAr: "شكراً لتواصلكم بخصوص استخدام رصيد ضريبة المطار من رحلتكم الفائتة قبل 8 أشهر.",
      emailResolutionAr: "لا يزال هذا الرصيد ساري المفعول، حيث يمكن استخدامه لمدة تصل إلى عام واحد من تاريخ الدفع. لقد تحققنا من حالته عبر نظام Accel Aero ويمكننا تطبيقه على حجزكم الجديد.",
    },
    {
      chatEn: "I understand you'd prefer a cash refund rather than credit — since you're insisting, I can go ahead and process a refund of your airport taxes instead.",
      chatAr: "أتفهم رغبتكم في استرداد نقدي بدلاً من الرصيد - وبما أنكم تصرّون على ذلك، يمكنني المضي قدمًا في معالجة استرداد ضرائب المطار الخاصة بكم.",
      emailSubjectEn: "Airport tax refund request",
      emailIssueEn: "Thank you for confirming you would like a cash refund of your airport taxes rather than a credit.",
      emailResolutionEn: "As per your request, we've processed a refund of your airport taxes instead of the default credit. Please allow the standard processing time for this to reflect on your original payment method.",
      emailSubjectAr: "طلب استرداد ضرائب المطار",
      emailIssueAr: "شكراً لتأكيدكم رغبتكم في استرداد نقدي لضرائب المطار بدلاً من الرصيد.",
      emailResolutionAr: "بناءً على طلبكم، قمنا بمعالجة استرداد ضرائب المطار بدلاً من الرصيد الافتراضي. يرجى مراعاة مدة المعالجة القياسية حتى تنعكس القيمة على وسيلة الدفع الأصلية.",
    },
  ],

  "general-flight-rescheduling-flexibility-rules-all-hubs": [
    {
      chatEn: "I completely understand the frustration. For a 3-hour delay, you're entitled to free rebooking and free cancellation, though not a free refund — would you like me to go ahead with either option?",
      chatAr: "أتفهم تمامًا شعوركم بالإحباط. بالنسبة لتأخير مدته 3 ساعات، يحق لكم إعادة الحجز والإلغاء مجانًا، لكن دون استرداد مجاني - هل ترغبون بأن أمضي قدمًا بأحد هذين الخيارين؟",
      emailSubjectEn: "Your entitlements for a 3-hour flight delay",
      emailIssueEn: "We're sorry for the inconvenience caused by the delay to your flight, and thank you for reaching out about your options.",
      emailResolutionEn: "A delay of 2–4 hours entitles you to free rebooking and free cancellation, though not a free refund. Please let us know which option you'd like us to proceed with.",
      emailSubjectAr: "استحقاقاتكم عند تأخر الرحلة 3 ساعات",
      emailIssueAr: "نعتذر عن الإزعاج الناتج عن تأخر رحلتكم، ونشكركم على تواصلكم بخصوص الخيارات المتاحة.",
      emailResolutionAr: "يمنحكم التأخير بين 2 و4 ساعات الحق في إعادة الحجز والإلغاء مجانًا، دون استرداد مجاني. يرجى إخبارنا بالخيار الذي ترغبون أن نمضي به.",
    },
    {
      chatEn: "I'm very sorry for the disruption to your travel plans. Since this was a force majeure cancellation on a 9P Domestic flight, you're entitled to free rebooking, cancellation, and a full refund.",
      chatAr: "نعتذر بشدة عن الاضطراب في خطط سفركم. وبما أن هذا الإلغاء ناتج عن ظروف قاهرة على رحلة 9P داخلية، فيحق لكم إعادة الحجز والإلغاء والاسترداد الكامل مجانًا.",
      emailSubjectEn: "Your entitlements for a force majeure cancellation",
      emailIssueEn: "We're very sorry for the disruption caused by the cancellation of your 9P Domestic flight due to severe weather.",
      emailResolutionEn: "Force majeure cancellations entitle you to free rebooking and free cancellation across all hubs, and because your flight is 9P Domestic specifically, you're also entitled to a free refund. Please let us know how you'd like to proceed.",
      emailSubjectAr: "استحقاقاتكم عند الإلغاء بسبب ظروف قاهرة",
      emailIssueAr: "نأسف بشدة للاضطراب الناتج عن إلغاء رحلتكم الداخلية على 9P بسبب سوء الأحوال الجوية.",
      emailResolutionAr: "يمنحكم الإلغاء بسبب الظروف القاهرة حق إعادة الحجز والإلغاء مجانًا في جميع مراكز التشغيل، وبما أن رحلتكم داخلية على 9P تحديدًا، فيحق لكم أيضًا استرداد كامل مجاني. يرجى إخبارنا بكيفية رغبتكم في المتابعة.",
    },
    {
      chatEn: "I hear you, but free rebooking only applies within ±7 days of your original date — a 10-day shift falls outside that, so a fare difference would apply. Want me to check the exact amount for you?",
      chatAr: "أتفهم طلبكم، إلا أن إعادة الحجز المجانية تنطبق فقط ضمن ± 7 أيام من التاريخ الأصلي - وبما أن التغيير المطلوب 10 أيام، فهو يقع خارج هذا النطاق وستُطبَّق رسوم فرق السعر. هل ترغبون أن أتحقق من المبلغ الدقيق لكم؟",
      emailSubjectEn: "Rebooking beyond the free ±7-day window",
      emailIssueEn: "Thank you for your request to rebook your flight 10 days later than originally booked.",
      emailResolutionEn: "Free rebooking applies only within ±7 days of your original travel date. As 10 days falls outside that window, only the fare difference would apply rather than a free change. Let us know if you'd like us to proceed and quote the fare difference.",
      emailSubjectAr: "إعادة الحجز خارج نطاق الـ 7 أيام المجاني",
      emailIssueAr: "شكراً لطلبكم إعادة حجز رحلتكم بعد 10 أيام من التاريخ الأصلي.",
      emailResolutionAr: "تنطبق إعادة الحجز المجانية فقط ضمن ± 7 أيام من تاريخ السفر الأصلي. وبما أن 10 أيام تقع خارج هذا النطاق، ستُطبَّق فقط رسوم فرق السعر بدلاً من تغيير مجاني. يرجى إخبارنا إذا رغبتم أن نمضي قدمًا ونحدد فرق السعر.",
    },
  ],

  "general-cai-cairo-flights-business-class-basic-ultimate-economy-all-hubs": [
    {
      chatEn: "Just to let you know, Cairo Economy only offers Basic and Ultimate bundles — Value isn't available on this route. I'd be happy to compare Basic and Ultimate for you.",
      chatAr: "للعلم، تتوفر على درجة السياحية لرحلات القاهرة باقتا Basic وUltimate فقط - باقة Value غير متاحة على هذا المسار. يسعدني مقارنة الباقتين لكم.",
      emailSubjectEn: "Available bundles for Cairo flights",
      emailIssueEn: "Thank you for your interest in booking the Value bundle for your Cairo flight.",
      emailResolutionEn: "Cairo Economy only offers Basic and Ultimate bundles — the Value bundle is not available on this route. We'd be happy to walk you through what's included in Basic and Ultimate so you can choose the best fit.",
      emailSubjectAr: "الباقات المتاحة لرحلات القاهرة",
      emailIssueAr: "شكراً لاهتمامكم بحجز باقة Value لرحلتكم إلى القاهرة.",
      emailResolutionAr: "تتوفر على درجة السياحية لرحلات القاهرة باقتا Basic وUltimate فقط، ولا تتوفر باقة Value على هذا المسار. يسعدنا توضيح ما تتضمنه كل من باقتي Basic وUltimate لمساعدتكم على الاختيار الأنسب.",
    },
    {
      chatEn: "No problem — since you've already used your 2 free modifications on the Ultimate bundle, this next change will only cost the fare difference, no extra modification fee.",
      chatAr: "لا مشكلة - بما أنكم استخدمتم بالفعل التعديلين المجانيين ضمن باقة Ultimate، فإن هذا التعديل التالي سيكلّف فقط فرق السعر دون أي رسوم تعديل إضافية.",
      emailSubjectEn: "Modification on your Ultimate bundle booking",
      emailIssueEn: "Thank you for your modification request on your Cairo Ultimate bundle booking.",
      emailResolutionEn: "As you've already used your 2 free modifications, this change will only incur the fare difference — no additional modification fee applies. Please confirm if you'd like us to proceed.",
      emailSubjectAr: "تعديل حجزكم على باقة Ultimate",
      emailIssueAr: "شكراً لطلبكم تعديل حجزكم على باقة Ultimate لرحلة القاهرة.",
      emailResolutionAr: "بما أنكم استخدمتم بالفعل تعديلَيكم المجانيَّين، فإن هذا التعديل سيكلّف فقط فرق السعر دون أي رسوم تعديل إضافية. يرجى تأكيد رغبتكم في المتابعة.",
    },
    {
      chatEn: "I'm afraid the middle seat is always blocked in Business Class on Cairo flights, so it can't be occupied — I can offer your family adjoining aisle and window seats within the free-selection rows instead.",
      chatAr: "نأسف، المقعد الأوسط محجوب دائمًا في الدرجة الأولى على رحلات القاهرة ولا يمكن شغله - يمكنني تقديم مقاعد ممر ونافذة متجاورة لعائلتكم ضمن الصفوف المتاحة للاختيار المجاني.",
      emailSubjectEn: "Middle seat policy in Business Class",
      emailIssueEn: "Thank you for your request to seat your family together, including the middle seat, in Business Class.",
      emailResolutionEn: "The middle seat is always kept empty in Business Class on Cairo flights and cannot be occupied. We'd be glad to offer adjoining aisle and window seats within the free-selection rows for your family instead.",
      emailSubjectAr: "سياسة المقعد الأوسط في الدرجة الأولى",
      emailIssueAr: "شكراً لطلبكم إجلاس عائلتكم معًا، بما في ذلك المقعد الأوسط، في الدرجة الأولى.",
      emailResolutionAr: "يبقى المقعد الأوسط محجوبًا دائمًا في الدرجة الأولى على رحلات القاهرة ولا يمكن شغله. يسعدنا تقديم مقاعد ممر ونافذة متجاورة لعائلتكم ضمن الصفوف المتاحة للاختيار المجاني.",
    },
  ],
};
