import type { ArticleTemplateSet } from "./types";

export const NEW_CATEGORY_TEMPLATES: Record<string, ArticleTemplateSet> = {
  "airrewards-loyalty-program-all-hubs-1783838668534": [
    {
      chatEn: "Not directly, I'm afraid — a child aged 2–11 must be linked to a family head account, and that family head must already be an existing AirRewards member. Passengers 12 and above can register and earn/redeem on their own.",
      chatAr: "للأسف لا، بشكل مباشر - يجب ربط الطفل بين 2 و11 عامًا بحساب رب الأسرة، ويجب أن يكون رب الأسرة عضوًا مسجلاً بالفعل في AirRewards. يمكن لمن هم 12 عامًا فأكثر التسجيل وكسب النقاط واستبدالها بشكل مستقل.",
      emailSubjectEn: "AirRewards registration for a child",
      emailIssueEn: "Thank you for asking whether your 10-year-old can register for their own AirRewards account.",
      emailResolutionEn: "A child aged 2–11 cannot register independently — they must be linked to a family head account, and that family head must already be an existing AirRewards member. Only passengers 12 and above can register and earn/redeem points on their own.",
      emailSubjectAr: "تسجيل طفل في برنامج AirRewards",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كان بإمكان طفلكم البالغ 10 أعوام التسجيل في حساب AirRewards خاص به.",
      emailResolutionAr: "لا يمكن للطفل بين 2 و11 عامًا التسجيل بشكل مستقل - يجب ربطه بحساب رب الأسرة، ويجب أن يكون رب الأسرة عضوًا مسجلاً بالفعل. يمكن فقط لمن هم 12 عامًا فأكثر التسجيل وكسب واستبدال النقاط بشكل مستقل.",
    },
    {
      chatEn: "That's expected — the family head account doesn't earn points directly from its own travel in this scenario; it earns 50% of each linked passenger's points instead. Happy to walk you through your account's full point breakdown.",
      chatAr: "هذا متوقع - لا يكسب حساب رب الأسرة نقاطًا مباشرة من سفره الخاص في هذه الحالة؛ بل يكسب 50% من نقاط كل مسافر مرتبط به. يسعدني توضيح تفاصيل النقاط الكاملة لحسابكم.",
      emailSubjectEn: "How family head points are calculated",
      emailIssueEn: "Thank you for asking why your family head account shows 0 points after a linked family member's flight.",
      emailResolutionEn: "This is expected behaviour — the family head account earns 50% of each linked passenger's points from their flights (the other 50% is forfeited), rather than a separate balance from the family head's own travel. Let us know if you'd like a full breakdown of your account.",
      emailSubjectAr: "كيفية احتساب نقاط رب الأسرة",
      emailIssueAr: "شكراً لاستفساركم عن سبب ظهور 0 نقطة في حساب رب الأسرة بعد رحلة أحد أفراد العائلة المرتبطين.",
      emailResolutionAr: "هذا سلوك متوقع - يكسب حساب رب الأسرة 50% من نقاط كل مسافر مرتبط به من رحلاته (وتُفقد الـ50% الأخرى)، بدلاً من رصيد منفصل من سفر رب الأسرة نفسه. يرجى إخبارنا إذا رغبتم بتفاصيل كاملة لحسابكم.",
    },
    {
      chatEn: "No minimum applies for seat, meal, insurance or airport service redemptions — the 3,000-point minimum is only for fare or baggage redemption. I'll go ahead and process your seat redemption now.",
      chatAr: "لا يوجد حد أدنى لاستبدال النقاط مقابل المقعد أو الوجبة أو التأمين أو خدمات المطار - الحد الأدنى 3,000 نقطة ينطبق فقط على استبدال الأجرة أو الأمتعة. سأمضي قدمًا في معالجة استبدال المقعد الآن.",
      emailSubjectEn: "Redeeming points for a seat",
      emailIssueEn: "Thank you for your request to redeem 2,000 points against a seat selection.",
      emailResolutionEn: "No minimum applies to seat, meal, insurance or airport service redemptions — the 3,000-point minimum only applies to fare or baggage redemption. We're processing your seat redemption now.",
      emailSubjectAr: "استبدال النقاط مقابل مقعد",
      emailIssueAr: "شكراً لطلبكم استبدال 2,000 نقطة مقابل اختيار مقعد.",
      emailResolutionAr: "لا يوجد حد أدنى لاستبدال النقاط مقابل المقعد أو الوجبة أو التأمين أو خدمات المطار - الحد الأدنى البالغ 3,000 نقطة ينطبق فقط على استبدال الأجرة أو الأمتعة. نقوم بمعالجة استبدال مقعدكم الآن.",
    },
  ],

  "payment-channels-charges-all-hubs-1783838668718": [
    {
      chatEn: "Yes, there is a small charge — paying at our Kuwait office costs KWD 5.00 per passenger. Just wanted to make sure you're aware of that before we proceed.",
      chatAr: "نعم، توجد رسوم بسيطة - تبلغ رسوم الدفع في مكتبنا في الكويت 5.00 دنانير كويتية لكل مسافر. أردت فقط التأكد من إطلاعكم على ذلك قبل المتابعة.",
      emailSubjectEn: "Payment charge at our Kuwait office",
      emailIssueEn: "Thank you for asking whether there's a fee to pay for your call-center booking in Kuwait.",
      emailResolutionEn: "Yes — paying at the Kuwait office costs KWD 5.00 per passenger. We're required to disclose this charge to you before you proceed with payment.",
      emailSubjectAr: "رسوم الدفع في مكتبنا في الكويت",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كانت هناك رسوم للدفع مقابل حجزكم عبر مركز الاتصال في الكويت.",
      emailResolutionAr: "نعم - تبلغ رسوم الدفع في مكتب الكويت 5.00 دنانير كويتية لكل مسافر. نحن ملزمون بإعلامكم بهذه الرسوم قبل إتمام الدفع.",
    },
    {
      chatEn: "It depends on direction — EGP 250 per passenger for flights departing Egypt, EGP 500 per passenger for flights arriving into Egypt. Also worth knowing, Fawry is currently suspended as a payment option.",
      chatAr: "يعتمد ذلك على الاتجاه - 250 جنيهًا مصريًا لكل مسافر للرحلات المغادرة من مصر، و500 جنيه مصري لكل مسافر للرحلات الواصلة إلى مصر. يجدر بالذكر أيضًا أن خدمة فوري معلّقة حاليًا كخيار دفع.",
      emailSubjectEn: "Payment fee for your Egypt booking",
      emailIssueEn: "Thank you for asking about the payment fee for your flight departing from vs. arriving into Cairo.",
      emailResolutionEn: "It depends on direction: EGP 250 per passenger for flights from Egypt, EGP 500 per passenger for flights to Egypt. Please also note that Fawry is currently suspended as a payment option.",
      emailSubjectAr: "رسوم الدفع لحجزكم في مصر",
      emailIssueAr: "شكراً لاستفساركم عن رسوم الدفع للرحلة المغادرة من القاهرة مقارنة بالرحلة الواصلة إليها.",
      emailResolutionAr: "يعتمد ذلك على الاتجاه: 250 جنيهًا مصريًا لكل مسافر للرحلات من مصر، و500 جنيه مصري لكل مسافر للرحلات إلى مصر. يرجى العلم أيضًا أن خدمة فوري معلّقة حاليًا كخيار دفع.",
    },
    {
      chatEn: "Yes, absolutely — iDeal is available for customers in the Netherlands for direct online bank transfers. I can set that up as your payment method now.",
      chatAr: "نعم بالتأكيد - تتوفر خدمة iDeal للعملاء في هولندا للتحويلات المصرفية المباشرة عبر الإنترنت. يمكنني تفعيل ذلك كوسيلة دفع لكم الآن.",
      emailSubjectEn: "iDeal payment for Netherlands customers",
      emailIssueEn: "Thank you for asking whether you can pay via direct bank transfer.",
      emailResolutionEn: "Yes — iDeal is available for customers in the Netherlands for direct online bank transfers. Let us know if you'd like this set up as your payment method.",
      emailSubjectAr: "الدفع عبر iDeal للعملاء في هولندا",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كان بإمكانكم الدفع عبر تحويل مصرفي مباشر.",
      emailResolutionAr: "نعم - تتوفر خدمة iDeal للعملاء في هولندا للتحويلات المصرفية المباشرة عبر الإنترنت. يرجى إخبارنا إذا رغبتم باعتمادها وسيلة دفع لكم.",
    },
  ],

  "using-credit-vouchers-for-a-new-booking-all-hubs-1783838668831": [
    {
      chatEn: "I noticed a small spelling difference between your new booking and the original PNR — credit can only be matched with an exact spelling match, so let's correct that first before applying it.",
      chatAr: "لاحظت اختلافًا بسيطًا في الإملاء بين حجزكم الجديد وحجزكم الأصلي - يمكن مطابقة الرصيد فقط عند تطابق الإملاء تمامًا، فلنقم بتصحيح ذلك أولاً قبل تطبيقه.",
      emailSubjectEn: "Spelling must match to apply your credit",
      emailIssueEn: "Thank you for your request to apply your credit voucher to this new booking.",
      emailResolutionEn: "Credit can only be matched to the exact same passenger spelling as the original PNR. We noticed a slight difference — please confirm the correct spelling so we can apply the credit successfully.",
      emailSubjectAr: "تطابق الإملاء مطلوب لتطبيق رصيدكم",
      emailIssueAr: "شكراً لطلبكم تطبيق قسيمة الرصيد الخاصة بكم على هذا الحجز الجديد.",
      emailResolutionAr: "يمكن مطابقة الرصيد فقط عند تطابق إملاء اسم المسافر تمامًا مع الحجز الأصلي. لاحظنا اختلافًا بسيطًا - يرجى تأكيد الإملاء الصحيح حتى نتمكن من تطبيق الرصيد بنجاح.",
    },
    {
      chatEn: "I've applied your credit, and it covers 70% of the new fare — I'll send a payment link for the remaining balance now. Please complete that promptly, as an unpaid balance can trigger cancellation charges.",
      chatAr: "لقد طبّقت رصيدكم، وهو يغطي 70% من الأجرة الجديدة - سأرسل رابط دفع للمبلغ المتبقي الآن. يرجى إتمام الدفع في أقرب وقت، حيث قد يؤدي عدم السداد إلى رسوم إلغاء.",
      emailSubjectEn: "Remaining balance after your credit was applied",
      emailIssueEn: "Thank you for using your credit voucher toward your new booking.",
      emailResolutionEn: "Your credit has been applied and covers part of the new fare. We've sent a payment link for the remaining balance — please complete this promptly, as an unpaid balance can result in cancellation charges.",
      emailSubjectAr: "الرصيد المتبقي بعد تطبيق قسيمتكم",
      emailIssueAr: "شكراً لاستخدامكم قسيمة الرصيد الخاصة بكم على حجزكم الجديد.",
      emailResolutionAr: "تم تطبيق رصيدكم وهو يغطي جزءًا من الأجرة الجديدة. لقد أرسلنا رابط دفع للمبلغ المتبقي - يرجى إتمام السداد في أقرب وقت، حيث قد يؤدي عدم السداد إلى رسوم إلغاء.",
    },
    {
      chatEn: "Good question — your credit voucher stays valid for 1 year from the date of payment, and it can only be used by the same passenger it was issued to.",
      chatAr: "سؤال جيد - تبقى قسيمة رصيدكم سارية لمدة عام واحد من تاريخ الدفع، ويمكن استخدامها فقط من قبل المسافر الذي صدرت باسمه.",
      emailSubjectEn: "Credit voucher validity period",
      emailIssueEn: "Thank you for asking how long your credit voucher remains valid.",
      emailResolutionEn: "Your credit is valid for 1 year from the date of payment, and can only be used for the same passenger it was issued to.",
      emailSubjectAr: "مدة صلاحية قسيمة الرصيد",
      emailIssueAr: "شكراً لاستفساركم عن مدة صلاحية قسيمة رصيدكم.",
      emailResolutionAr: "يبقى رصيدكم ساريًا لمدة عام واحد من تاريخ الدفع، ويمكن استخدامه فقط للمسافر الذي صدر باسمه.",
    },
  ],

  "caller-verification-all-hubs-1783838668928": [
    {
      chatEn: "I'm sorry, but I'm not able to proceed without all 3 verification details confirmed correctly — could you please double check the flight destination and date, and the contact detail on the booking?",
      chatAr: "نأسف، لا يمكنني المتابعة دون تأكيد جميع بيانات التحقق الثلاثة بشكل صحيح - هل يمكنكم التحقق مجددًا من وجهة الرحلة وتاريخها، وبيانات التواصل المسجّلة على الحجز؟",
      emailSubjectEn: "Unable to proceed without full verification",
      emailIssueEn: "Thank you for your request to modify this booking.",
      emailResolutionEn: "For your security, we're unable to take any action on a paid booking until all 3 verification questions are answered correctly: passenger name, flight destination & date, and one contact detail. Please provide the missing detail so we can assist further.",
      emailSubjectAr: "تعذّر المتابعة دون التحقق الكامل",
      emailIssueAr: "شكراً لطلبكم تعديل هذا الحجز.",
      emailResolutionAr: "لحماية بياناتكم، لا يمكننا اتخاذ أي إجراء على حجز مدفوع حتى يتم الإجابة الصحيحة على أسئلة التحقق الثلاثة: اسم المسافر، ووجهة الرحلة وتاريخها، وأحد بيانات التواصل. يرجى تزويدنا بالبيانات الناقصة لنتمكن من مساعدتكم.",
    },
    {
      chatEn: "No problem at all — for a general flight timing question I don't need to verify the PNR, since you may not be the passenger. Let me check that flight for you right away.",
      chatAr: "لا مشكلة إطلاقًا - بالنسبة لاستفسار عام عن موعد الرحلة، لا أحتاج للتحقق من رقم الحجز، فقد لا تكونون المسافر نفسه. دعوني أتحقق من الرحلة لكم فورًا.",
      emailSubjectEn: "Flight status — no verification needed",
      emailIssueEn: "Thank you for reaching out about a flight's arrival time.",
      emailResolutionEn: "For a general flight status question, no PNR or verification is required, since the person asking may not be the passenger. Here's the current status of your flight.",
      emailSubjectAr: "حالة الرحلة - لا حاجة للتحقق",
      emailIssueAr: "شكراً لتواصلكم بخصوص موعد وصول إحدى الرحلات.",
      emailResolutionAr: "بالنسبة لاستفسار عام عن حالة الرحلة، لا حاجة لرقم الحجز أو التحقق، حيث إن السائل قد لا يكون المسافر نفسه. فيما يلي الحالة الحالية لرحلتكم.",
    },
    {
      chatEn: "I'm afraid that contact detail doesn't match what's on file, so I'm unable to share the booking details or make changes — I'd recommend having the passenger or account holder reach out directly.",
      chatAr: "نأسف، بيانات التواصل هذه لا تتطابق مع المسجّل لدينا، لذا لا يمكنني مشاركة تفاصيل الحجز أو إجراء أي تعديلات - أنصح بأن يتواصل معنا المسافر أو صاحب الحساب مباشرة.",
      emailSubjectEn: "Contact detail does not match our records",
      emailIssueEn: "Thank you for reaching out regarding this booking.",
      emailResolutionEn: "The contact detail provided does not match what's on file for this booking, so we're unable to share details or process changes at this time. We'd recommend that the passenger or account holder contact us directly.",
      emailSubjectAr: "بيانات التواصل غير مطابقة لسجلاتنا",
      emailIssueAr: "شكراً لتواصلكم بخصوص هذا الحجز.",
      emailResolutionAr: "بيانات التواصل المقدمة لا تتطابق مع المسجّل لدينا لهذا الحجز، لذا لا يمكننا مشاركة التفاصيل أو معالجة أي تعديلات في الوقت الحالي. نوصي بأن يتواصل معنا المسافر أو صاحب الحساب مباشرة.",
    },
  ],

  "visa-applications-visa-change-bookings-all-hubs-1783838669014": [
    {
      chatEn: "Since this same-day return is for a visa run, I'll need to flag it as a visa-change booking — this type has to be completed at one of our offices rather than over the phone. I can point you to your nearest one.",
      chatAr: "بما أن هذا الحجز لرحلة ذهاب وعودة في اليوم نفسه لغرض تجديد التأشيرة، سأحتاج إلى تصنيفه كحجز تغيير تأشيرة - يجب إتمام هذا النوع في أحد مكاتبنا وليس عبر الهاتف. يمكنني إرشادكم لأقرب مكتب.",
      emailSubjectEn: "Visa-change bookings require an office visit",
      emailIssueEn: "Thank you for your request to book a same-day return ticket for a visa run.",
      emailResolutionEn: "This must be booked as a visa-change (VFR) ticket, which cannot be created over the phone. Please visit an Air Arabia office to complete this booking.",
      emailSubjectAr: "حجوزات تغيير التأشيرة تتطلب زيارة المكتب",
      emailIssueAr: "شكراً لطلبكم حجز تذكرة ذهاب وعودة في اليوم نفسه لغرض تجديد التأشيرة.",
      emailResolutionAr: "يجب حجز هذا النوع كتذكرة تغيير تأشيرة (VFR)، ولا يمكن إنشاؤها عبر الهاتف. يرجى زيارة أحد مكاتب العربية للطيران لإتمام هذا الحجز.",
    },
    {
      chatEn: "I'm sorry, but visa-change bookings can't be modified or cancelled from the Call Center — you'll need to visit an Air Arabia office to make this change.",
      chatAr: "نأسف، لا يمكن تعديل أو إلغاء حجوزات تغيير التأشيرة عبر مركز الاتصال - ستحتاجون لزيارة أحد مكاتب العربية للطيران لإجراء هذا التعديل.",
      emailSubjectEn: "Visa-change bookings cannot be modified remotely",
      emailIssueEn: "Thank you for your request to modify the return date on your visa-change booking.",
      emailResolutionEn: "Visa-change bookings cannot be modified or cancelled through the Call Center. Please visit an Air Arabia office to complete this change.",
      emailSubjectAr: "لا يمكن تعديل حجوزات تغيير التأشيرة عن بُعد",
      emailIssueAr: "شكراً لطلبكم تعديل تاريخ العودة على حجز تغيير التأشيرة الخاص بكم.",
      emailResolutionAr: "لا يمكن تعديل أو إلغاء حجوزات تغيير التأشيرة عبر مركز الاتصال. يرجى زيارة أحد مكاتب العربية للطيران لإتمام هذا التعديل.",
    },
    {
      chatEn: "We're not able to process visa applications directly, I'm afraid — for a Schengen visa, I'd recommend reaching out to the relevant consulate or embassy.",
      chatAr: "للأسف، لا يمكننا معالجة طلبات التأشيرة مباشرة - بالنسبة لتأشيرة شنغن، أنصح بالتواصل مع القنصلية أو السفارة المعنية.",
      emailSubjectEn: "Visa applications are handled by the consulate/embassy",
      emailIssueEn: "Thank you for reaching out about assistance with a Schengen visa application.",
      emailResolutionEn: "Air Arabia does not process visa applications directly. For any visa other than the UAE, please contact the relevant consulate or embassy for guidance.",
      emailSubjectAr: "طلبات التأشيرة تُعالَج عبر القنصلية أو السفارة",
      emailIssueAr: "شكراً لتواصلكم بخصوص المساعدة في طلب تأشيرة شنغن.",
      emailResolutionAr: "لا تقوم العربية للطيران بمعالجة طلبات التأشيرة مباشرة. بالنسبة لأي تأشيرة غير الإماراتية، يرجى التواصل مع القنصلية أو السفارة المعنية للحصول على التوجيه اللازم.",
    },
  ],

  "modification-cancellation-checklists-all-hubs-1783838669091": [
    {
      chatEn: "Before I confirm the new fare, let me just check whether your previously selected ancillaries have carried forward to the new flight — one moment please.",
      chatAr: "قبل تأكيد الأجرة الجديدة، دعوني أتحقق مما إذا كانت الخدمات الإضافية التي اخترتموها سابقًا قد انتقلت إلى الرحلة الجديدة - لحظة من فضلكم.",
      emailSubjectEn: "Confirming your modified booking",
      emailIssueEn: "Thank you for confirming the modification to your flight.",
      emailResolutionEn: "We've recapped your new flight details and checked whether your ancillaries carried forward. Your previous date has been cancelled, the new date is confirmed, and payment is due before the new segment can be used.",
      emailSubjectAr: "تأكيد تعديل حجزكم",
      emailIssueAr: "شكراً لتأكيدكم تعديل رحلتكم.",
      emailResolutionAr: "قمنا بمراجعة تفاصيل رحلتكم الجديدة والتحقق من انتقال الخدمات الإضافية. تم إلغاء التاريخ السابق وتأكيد التاريخ الجديد، ويستحق السداد قبل استخدام القطاع الجديد.",
    },
    {
      chatEn: "All done — your cancellation has been processed. I'll also send you a written confirmation by email with the credit amount and its expiry date for your records.",
      chatAr: "تم إنجاز الطلب - تمت معالجة إلغاء حجزكم. سأرسل لكم أيضًا تأكيدًا كتابيًا عبر البريد الإلكتروني يتضمن قيمة الرصيد وتاريخ انتهاء صلاحيته لسجلاتكم.",
      emailSubjectEn: "Your cancellation confirmation",
      emailIssueEn: "Thank you for confirming the cancellation of your booking.",
      emailResolutionEn: "Your cancellation has been processed. Your credit amount and its expiry date are confirmed below — please keep this email for your records.",
      emailSubjectAr: "تأكيد إلغاء حجزكم",
      emailIssueAr: "شكراً لتأكيدكم إلغاء حجزكم.",
      emailResolutionAr: "تمت معالجة إلغاء حجزكم. فيما يلي تأكيد قيمة الرصيد وتاريخ انتهاء صلاحيته - يرجى الاحتفاظ بهذا البريد الإلكتروني لسجلاتكم.",
    },
    {
      chatEn: "Here's the breakdown you asked for — the balance shown is per passenger, and I've also added the total amount due for everyone on the booking.",
      chatAr: "إليكم التفاصيل التي طلبتموها - المبلغ المعروض هو للفرد الواحد، وقد أضفت أيضًا إجمالي المبلغ المستحق لجميع المسافرين على الحجز.",
      emailSubjectEn: "Charges breakdown for your booking",
      emailIssueEn: "Thank you for asking for a breakdown of the charges on your modification.",
      emailResolutionEn: "Here is the charges breakdown: the balance shown is per passenger, followed by the total amount due for all passengers on the booking.",
      emailSubjectAr: "تفاصيل الرسوم لحجزكم",
      emailIssueAr: "شكراً لطلبكم تفاصيل الرسوم المترتبة على تعديلكم.",
      emailResolutionAr: "فيما يلي تفاصيل الرسوم: المبلغ المعروض هو للفرد الواحد، يليه إجمالي المبلغ المستحق لجميع المسافرين على الحجز.",
    },
  ],

  "group-booking-requests-inquiries-all-hubs-1783838669189": [
    {
      chatEn: "I'm sorry, but ancillary changes like meal preferences can't be processed on a group booking through the Call Center — I'd recommend reaching out to our Groups team directly for this request.",
      chatAr: "نأسف، لا يمكن معالجة تعديلات الخدمات الإضافية مثل تفضيلات الوجبات على حجز جماعي عبر مركز الاتصال - أنصح بالتواصل مباشرة مع فريق الحجوزات الجماعية لهذا الطلب.",
      emailSubjectEn: "Ancillary changes not available on group bookings",
      emailIssueEn: "Thank you for your request to change a passenger's meal preference on your group booking.",
      emailResolutionEn: "Ancillary changes cannot be processed on group bookings through the Call Center, regardless of the size of the change. Please contact our Groups team directly for this request.",
      emailSubjectAr: "تعديلات الخدمات الإضافية غير متاحة على الحجوزات الجماعية",
      emailIssueAr: "شكراً لطلبكم تعديل تفضيل الوجبة لأحد المسافرين على حجزكم الجماعي.",
      emailResolutionAr: "لا يمكن معالجة تعديلات الخدمات الإضافية على الحجوزات الجماعية عبر مركز الاتصال، بغض النظر عن حجم التعديل. يرجى التواصل مباشرة مع فريق الحجوزات الجماعية لهذا الطلب.",
    },
    {
      chatEn: "I'm afraid this flight doesn't qualify as a group booking — we'd need more than 70 available seats in the sector. I'd suggest checking other flight options or booking individually.",
      chatAr: "نأسف، هذه الرحلة لا تستوفي شروط الحجز الجماعي - نحتاج لأكثر من 70 مقعدًا متاحًا في هذا القطاع. أقترح التحقق من خيارات رحلات أخرى أو الحجز بشكل فردي.",
      emailSubjectEn: "Flight does not meet group booking eligibility",
      emailIssueEn: "Thank you for your request to book 12 seats as a group on this flight.",
      emailResolutionEn: "This flight doesn't qualify as a group booking, as it requires more than 70 available seats in the sector, and only 40 remain. We'd recommend checking other flight options or booking individually.",
      emailSubjectAr: "الرحلة لا تستوفي شروط أهلية الحجز الجماعي",
      emailIssueAr: "شكراً لطلبكم حجز 12 مقعدًا كحجز جماعي على هذه الرحلة.",
      emailResolutionAr: "هذه الرحلة لا تستوفي شروط الحجز الجماعي، حيث تتطلب أكثر من 70 مقعدًا متاحًا في القطاع، بينما تبقى 40 مقعدًا فقط. نوصي بالتحقق من خيارات رحلات أخرى أو الحجز بشكل فردي.",
    },
    {
      chatEn: "I'm sorry, but I can't share PNR details unless verification is completed for all passengers, flight details, and one contact detail — could you please provide the full information?",
      chatAr: "نأسف، لا يمكنني مشاركة تفاصيل الحجز إلا بعد إتمام التحقق من جميع أسماء المسافرين وتفاصيل الرحلة وأحد بيانات التواصل - هل يمكنكم تزويدنا بالمعلومات الكاملة؟",
      emailSubjectEn: "Full verification required for group PNR details",
      emailIssueEn: "Thank you for reaching out regarding your group booking.",
      emailResolutionEn: "We're unable to share PNR details until verification is completed for all passenger names, flight details, and one contact detail. Please provide the full information so we can proceed.",
      emailSubjectAr: "التحقق الكامل مطلوب لمشاركة تفاصيل الحجز الجماعي",
      emailIssueAr: "شكراً لتواصلكم بخصوص حجزكم الجماعي.",
      emailResolutionAr: "لا يمكننا مشاركة تفاصيل الحجز حتى يتم التحقق الكامل من جميع أسماء المسافرين وتفاصيل الرحلة وأحد بيانات التواصل. يرجى تزويدنا بالمعلومات الكاملة لنتمكن من المتابعة.",
    },
  ],

  "skytime-onboard-entertainment-all-hubs-1783838669295": [
    {
      chatEn: "No download needed at all — after take-off just connect your device's Wi-Fi to the SkyTime network and log in with your email and seat number. It's all free!",
      chatAr: "لا حاجة لأي تحميل مسبق - بعد الإقلاع، فقط قوموا بتوصيل جهازكم بشبكة SkyTime عبر الواي فاي وسجّلوا الدخول باستخدام بريدكم الإلكتروني ورقم المقعد. كل ذلك مجانًا!",
      emailSubjectEn: "How to access SkyTime",
      emailIssueEn: "Thank you for asking whether you need to download anything before your flight for SkyTime.",
      emailResolutionEn: "No pre-flight download is needed. After take-off, simply connect your device's Wi-Fi to the SkyTime network and log in with your email address and seat number to enjoy free entertainment.",
      emailSubjectAr: "كيفية الوصول إلى SkyTime",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كنتم بحاجة لتحميل أي شيء قبل رحلتكم لاستخدام SkyTime.",
      emailResolutionAr: "لا حاجة لأي تحميل مسبق. بعد الإقلاع، ما عليكم سوى توصيل جهازكم بشبكة SkyTime عبر الواي فاي وتسجيل الدخول ببريدكم الإلكتروني ورقم مقعدكم للاستمتاع بالترفيه المجاني.",
    },
    {
      chatEn: "No worries — you can rent a power bank onboard for a small extra charge, then connect once your device has enough battery to enjoy SkyTime.",
      chatAr: "لا داعي للقلق - يمكنكم استئجار بطارية شحن متنقلة على متن الطائرة مقابل رسوم بسيطة، ثم الاتصال بمجرد توفر شحن كافٍ لجهازكم للاستمتاع بـ SkyTime.",
      emailSubjectEn: "Low battery — power banks available onboard",
      emailIssueEn: "Thank you for asking how to watch something on SkyTime if your phone battery is low.",
      emailResolutionEn: "Power banks are available onboard for a small additional charge — once your device has enough battery, you can connect to SkyTime as usual.",
      emailSubjectAr: "بطارية منخفضة - تتوفر بطاريات شحن متنقلة على متن الطائرة",
      emailIssueAr: "شكراً لاستفساركم عن كيفية مشاهدة محتوى SkyTime في حال انخفاض بطارية هاتفكم.",
      emailResolutionAr: "تتوفر بطاريات شحن متنقلة على متن الطائرة مقابل رسوم بسيطة إضافية - وبمجرد توفر شحن كافٍ لجهازكم، يمكنكم الاتصال بـ SkyTime كالمعتاد.",
    },
    {
      chatEn: "Yes, SkyTime itself is completely free! Only optional extras like power banks and headsets carry a small additional charge if you'd like them.",
      chatAr: "نعم، خدمة SkyTime مجانية بالكامل! فقط الإضافات الاختيارية مثل بطاريات الشحن المتنقلة وسماعات الرأس تخضع لرسوم بسيطة إضافية إذا رغبتم بها.",
      emailSubjectEn: "SkyTime is free of charge",
      emailIssueEn: "Thank you for asking whether SkyTime is free.",
      emailResolutionEn: "Yes, SkyTime is completely free. Only optional extras such as power banks and headsets carry a small additional charge.",
      emailSubjectAr: "خدمة SkyTime مجانية",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كانت خدمة SkyTime مجانية.",
      emailResolutionAr: "نعم، خدمة SkyTime مجانية بالكامل. فقط الإضافات الاختيارية مثل بطاريات الشحن المتنقلة وسماعات الرأس تخضع لرسوم بسيطة إضافية.",
    },
  ],

  "handling-complaints-all-hubs-1783838669372": [
    {
      chatEn: "I'm really sorry for the trouble this has caused. Let me look into this properly for you right now — can you walk me through exactly what happened so I make sure we fix the right thing?",
      chatAr: "أعتذر بشدة عن هذا الإزعاج. دعوني أتحقق من الأمر بشكل صحيح الآن - هل يمكنكم إخباري بما حدث بالتفصيل حتى أتأكد من حل المشكلة الصحيحة؟",
      emailSubjectEn: "We're looking into your payment issue",
      emailIssueEn: "We're very sorry to hear your payment was debited without receiving a booking confirmation.",
      emailResolutionEn: "Please allow up to 2 hours in case the payment is still processing. If it remains unresolved after that, we'll run an advanced search for any generated PNR, raise a Sprinklr payment-issues request on your behalf, and extend the booking time limit by at least 24 hours.",
      emailSubjectAr: "نحن نبحث في مشكلة الدفع الخاصة بكم",
      emailIssueAr: "يؤسفنا سماع أنه تم خصم المبلغ من حسابكم دون استلام تأكيد للحجز.",
      emailResolutionAr: "يرجى الانتظار حتى ساعتين في حال كانت عملية الدفع لا تزال قيد المعالجة. إذا استمرت المشكلة بعد ذلك، سنقوم بإجراء بحث متقدم عن أي حجز تم إنشاؤه، وفتح طلب على Sprinklr بخصوص مشكلة الدفع نيابةً عنكم، وتمديد مهلة الحجز لمدة 24 ساعة على الأقل.",
    },
    {
      chatEn: "I completely understand your frustration, and I apologize for the wrong information you received. Let me raise this as a quality case so it's reviewed and addressed properly.",
      chatAr: "أتفهم تمامًا استياءكم، وأعتذر عن المعلومات الخاطئة التي تلقيتموها. دعوني أفتح هذا كطلب جودة ليتم مراجعته ومعالجته بشكل صحيح.",
      emailSubjectEn: "Your Call Center complaint has been logged",
      emailIssueEn: "Thank you for letting us know that a previous agent gave you incorrect modification fee information.",
      emailResolutionEn: "We're sorry for this experience. We've raised this as a quality case under Complaints > Call Center Complaints, and it will be reviewed by our quality team to ensure it doesn't happen again.",
      emailSubjectAr: "تم تسجيل شكواكم بخصوص مركز الاتصال",
      emailIssueAr: "شكراً لإبلاغنا بأن أحد ممثلي خدمة العملاء زوّدكم بمعلومات خاطئة حول رسوم التعديل.",
      emailResolutionAr: "نأسف لهذه التجربة. لقد سجّلنا هذا كطلب جودة ضمن الشكاوى > شكاوى مركز الاتصال، وسيتم مراجعته من قبل فريق الجودة لدينا لضمان عدم تكراره.",
    },
    {
      chatEn: "I hear you, and I'm sorry this has been so frustrating. Please take your time — I'm listening, and once you've walked me through everything we'll work on the best way forward together.",
      chatAr: "أتفهم شعوركم، وأعتذر عن هذا الإزعاج الكبير. خذوا وقتكم من فضلكم - أنا أستمع إليكم، وبعد أن تخبروني بكل التفاصيل سنعمل معًا على إيجاد أفضل حل.",
      emailSubjectEn: "We're here to help resolve this",
      emailIssueEn: "We're very sorry for the frustration caused by your flight cancellation.",
      emailResolutionEn: "We understand how disruptive this has been, and we want to make it right. Please share the full details of what happened, and our team will review your case and follow up with the best available solution.",
      emailSubjectAr: "نحن هنا لمساعدتكم في حل هذا الأمر",
      emailIssueAr: "نأسف بشدة للإزعاج الناتج عن إلغاء رحلتكم.",
      emailResolutionAr: "نتفهم مدى الإزعاج الذي سببه هذا الأمر، ونرغب في تصحيحه. يرجى مشاركة كافة تفاصيل ما حدث، وسيقوم فريقنا بمراجعة حالتكم والمتابعة بأفضل حل متاح.",
    },
  ],

  "baggage-claims-all-hubs-1783838669489": [
    {
      chatEn: "I'm sorry to hear about your damaged suitcase. Since baggage damage needs to be reported at the arrival airport at the time of arrival, I'd recommend checking with that airport's baggage services desk directly, even now.",
      chatAr: "يؤسفنا سماع تعرّض حقيبتكم للضرر. بما أنه يجب الإبلاغ عن تلف الأمتعة في مطار الوصول وقت الوصول، أنصح بالتواصل مباشرة مع مكتب خدمات الأمتعة في ذلك المطار، حتى الآن.",
      emailSubjectEn: "Reporting baggage damage after leaving the airport",
      emailIssueEn: "We're sorry to hear about the damage to your suitcase reported a couple of days after landing.",
      emailResolutionEn: "Baggage damage must be reported at the arrival airport at the time of arrival. As this report is coming in after you've left the airport, we'd recommend contacting that airport's baggage services desk directly to check what options remain available.",
      emailSubjectAr: "الإبلاغ عن تلف الأمتعة بعد مغادرة المطار",
      emailIssueAr: "يؤسفنا سماع تعرّض حقيبتكم للضرر، والذي تم الإبلاغ عنه بعد يومين من الهبوط.",
      emailResolutionAr: "يجب الإبلاغ عن تلف الأمتعة في مطار الوصول وقت الوصول. وبما أن هذا البلاغ يصل بعد مغادرتكم المطار، ننصح بالتواصل مباشرة مع مكتب خدمات الأمتعة في ذلك المطار للتحقق من الخيارات المتاحة.",
    },
    {
      chatEn: "Good, since you're still at the airport, please head to the baggage services counter right away so they can log the delayed baggage report immediately.",
      chatAr: "جيد، بما أنكم لا تزالون في المطار، يرجى التوجه فورًا إلى كاونتر خدمات الأمتعة حتى يتم تسجيل بلاغ تأخر الأمتعة على الفور.",
      emailSubjectEn: "Report your delayed baggage now",
      emailIssueEn: "Thank you for letting us know your bag didn't arrive on your flight.",
      emailResolutionEn: "As you're still at the airport, please report this immediately at the arrival airport's baggage services counter so it can be logged and tracked without delay.",
      emailSubjectAr: "بلّغوا عن تأخر أمتعتكم الآن",
      emailIssueAr: "شكراً لإبلاغنا بعدم وصول حقيبتكم مع رحلتكم.",
      emailResolutionAr: "بما أنكم لا تزالون في المطار، يرجى الإبلاغ عن ذلك فورًا في كاونتر خدمات الأمتعة في مطار الوصول حتى يتم تسجيل البلاغ ومتابعته دون تأخير.",
    },
    {
      chatEn: "I'm sorry, but photos by email can't substitute for reporting at the airport — damage, loss and delay all need to be reported at the arrival airport at the time of arrival for us to process a claim.",
      chatAr: "نأسف، لا يمكن أن تحل الصور المرسلة عبر البريد الإلكتروني محل الإبلاغ في المطار - يجب الإبلاغ عن التلف أو الفقدان أو التأخر في مطار الوصول وقت الوصول لمعالجة المطالبة.",
      emailSubjectEn: "Photos alone cannot replace an airport report",
      emailIssueEn: "Thank you for offering to send photos of your damaged luggage.",
      emailResolutionEn: "Unfortunately, damage, loss, and delay all need to be reported at the arrival airport at the time of arrival — this cannot be substituted with an email report after the fact.",
      emailSubjectAr: "الصور وحدها لا تُغني عن الإبلاغ في المطار",
      emailIssueAr: "شكراً لعرضكم إرسال صور لأمتعتكم التالفة.",
      emailResolutionAr: "للأسف، يجب الإبلاغ عن التلف أو الفقدان أو التأخر في مطار الوصول وقت الوصول - ولا يمكن الاستعاضة عن ذلك ببلاغ لاحق عبر البريد الإلكتروني.",
    },
  ],

  "contact-center-systems-overview-accel-aero-sprinklr-caesar-teams-1783838669574": [
    {
      chatEn: "Let me check your flight status directly for you — no need for your PNR for this, I'll just need the flight number and date.",
      chatAr: "دعوني أتحقق من حالة رحلتكم مباشرة - لا حاجة لرقم الحجز لهذا الاستفسار، أحتاج فقط لرقم الرحلة وتاريخها.",
      emailSubjectEn: "Your flight status",
      emailIssueEn: "Thank you for reaching out about your flight's departure and arrival timing.",
      emailResolutionEn: "We've checked your flight status directly using the flight number and date — please see the confirmed timing below, and let us know if you have any other questions.",
      emailSubjectAr: "حالة رحلتكم",
      emailIssueAr: "شكراً لتواصلكم بخصوص موعد مغادرة ووصول رحلتكم.",
      emailResolutionAr: "لقد تحققنا من حالة رحلتكم مباشرة باستخدام رقم الرحلة والتاريخ - يرجى الاطلاع على الموعد المؤكد أدناه، وإخبارنا إذا كانت لديكم أي استفسارات أخرى.",
    },
    {
      chatEn: "I've raised a case for your request in our system so our specialist team can review it — you'll receive an update as soon as it's processed.",
      chatAr: "لقد فتحت حالة لطلبكم في نظامنا حتى يتمكن فريقنا المختص من مراجعته - ستصلكم رسالة تحديث بمجرد معالجته.",
      emailSubjectEn: "Your request has been logged as a case",
      emailIssueEn: "Thank you for your request, which requires review by our specialist team.",
      emailResolutionEn: "We've raised a case in our system for your request, and it will be reviewed by the relevant team. You'll receive a follow-up once it's been processed.",
      emailSubjectAr: "تم تسجيل طلبكم كحالة",
      emailIssueAr: "شكراً لطلبكم، والذي يتطلب مراجعة من فريقنا المختص.",
      emailResolutionAr: "لقد فتحنا حالة في نظامنا لطلبكم، وسيتم مراجعته من قبل الفريق المختص. ستصلكم رسالة متابعة بمجرد معالجته.",
    },
    {
      chatEn: "Just a moment while I check the correct system for this — thanks for your patience, I want to make sure I give you the most accurate answer.",
      chatAr: "لحظة من فضلكم بينما أتحقق من النظام الصحيح لهذا الاستفسار - شكرًا لصبركم، أريد التأكد من تزويدكم بالإجابة الأدق.",
      emailSubjectEn: "Following up on your request",
      emailIssueEn: "Thank you for your patience while we confirmed the correct information for your request.",
      emailResolutionEn: "We've now checked the appropriate system and can confirm the details for your request — please see the information below.",
      emailSubjectAr: "متابعة طلبكم",
      emailIssueAr: "شكراً لصبركم بينما تحققنا من المعلومات الصحيحة لطلبكم.",
      emailResolutionAr: "لقد تحققنا الآن من النظام المناسب ويمكننا تأكيد تفاصيل طلبكم - يرجى الاطلاع على المعلومات أدناه.",
    },
  ],

  "airport-shuttle-bus-services-g9-3l-1783838669661": [
    {
      chatEn: "Your best free option is the City Centre Al Shindagha to Sharjah Airport bus, operated by Air Arabia — the Ras Al Khaimah office route is also available for AED 30 if that's more convenient.",
      chatAr: "أفضل خيار مجاني لكم هو حافلة City Centre Al Shindagha إلى مطار الشارقة، التي تديرها العربية للطيران - كما يتوفر مسار مكتب رأس الخيمة مقابل 30 درهمًا إذا كان أنسب لكم.",
      emailSubjectEn: "Free bus to Sharjah Airport",
      emailIssueEn: "Thank you for asking about a free bus option to Sharjah Airport from Dubai.",
      emailResolutionEn: "The City Centre Al Shindagha to Sharjah Airport bus is free of charge and operated by Air Arabia. The Ras Al Khaimah office route is also available for AED 30, if more convenient for your location.",
      emailSubjectAr: "حافلة مجانية إلى مطار الشارقة",
      emailIssueAr: "شكراً لاستفساركم عن خيار حافلة مجانية إلى مطار الشارقة من دبي.",
      emailResolutionAr: "حافلة City Centre Al Shindagha إلى مطار الشارقة مجانية ومُدارة من قبل العربية للطيران. يتوفر أيضًا مسار مكتب رأس الخيمة مقابل 30 درهمًا، إذا كان أنسب لموقعكم.",
    },
    {
      chatEn: "I'm afraid there's no reservation option — the Ras Al Khaimah Airport bus is first come, first served, subject to availability, so I'd recommend arriving with some buffer time.",
      chatAr: "نأسف، لا يوجد خيار للحجز المسبق - تعمل حافلة مطار رأس الخيمة على مبدأ الأسبقية حسب التوفر، لذا أنصح بالوصول قبل الموعد بوقت كافٍ.",
      emailSubjectEn: "No reservations on the RAK Airport shuttle",
      emailIssueEn: "Thank you for asking whether you can reserve a seat in advance on the RAK Airport bus.",
      emailResolutionEn: "This service is first come, first served, subject to availability, with no reservation option. We'd recommend arriving with some buffer time to ensure a seat.",
      emailSubjectAr: "لا يوجد حجز مسبق لحافلة مطار رأس الخيمة",
      emailIssueAr: "شكراً لاستفساركم عمّا إذا كان بإمكانكم حجز مقعد مسبقًا على حافلة مطار رأس الخيمة.",
      emailResolutionAr: "تعمل هذه الخدمة على مبدأ الأسبقية حسب التوفر، دون خيار للحجز المسبق. ننصح بالوصول قبل الموعد بوقت كافٍ لضمان الحصول على مقعد.",
    },
    {
      chatEn: "The 3L bus runs hourly between Ibn Battuta Mall and Abu Dhabi International Airport, operated by Abu Dhabi Airport — you can purchase your ticket at the bus station before departure, subject to availability.",
      chatAr: "تعمل حافلة 3L كل ساعة بين Ibn Battuta Mall ومطار أبوظبي الدولي، وتديرها مطارات أبوظبي - يمكنكم شراء التذكرة من محطة الحافلة قبل المغادرة، حسب التوفر.",
      emailSubjectEn: "Bus schedule to Abu Dhabi Airport",
      emailIssueEn: "Thank you for asking about the bus schedule to Abu Dhabi Airport from Dubai.",
      emailResolutionEn: "The 3L bus runs hourly between Ibn Battuta Mall and Abu Dhabi International Airport, operated by Abu Dhabi Airport. Tickets are purchased at the bus station before departure, subject to availability.",
      emailSubjectAr: "جدول الحافلات إلى مطار أبوظبي",
      emailIssueAr: "شكراً لاستفساركم عن جدول الحافلات إلى مطار أبوظبي من دبي.",
      emailResolutionAr: "تعمل حافلة 3L كل ساعة بين Ibn Battuta Mall ومطار أبوظبي الدولي، وتديرها مطارات أبوظبي. تُشترى التذاكر من محطة الحافلة قبل المغادرة، حسب التوفر.",
    },
  ],
};
